### ISSUE TITLE
[ISSUE] Import of databricks_mount not working

### ISSUE THREAD

**Issue by piotrwieckiewicz** [databrickslabs/terraform-provider-databricks#1018]
During importing existing Databricks infrastructure to Terraform it is not possible to import mounts.  I have a mount to the S3 bucket on AWS which is as follows: `dbfs:/mnt/copyprod`. According to the official documentation of databricks provider this command should work:

`$ terraform import databricks_mount.this <mount_name>`

but it is not.

### Steps to Reproduce
1. Prepare placeholder resource such as:
```hcl
resource "databricks_mount" "copyprod" {
}
```
2. Run `terraform import databricks_mount.copyprod copyprod`

### Expected Behavior
Mount should be imported into .tfstate file.

### Actual Behavior

Got error

```
databricks_mount.copyprod: Importing from ID "copyprod"...
databricks_mount.copyprod: Import prepared!
  Prepared databricks_mount for import
databricks_mount.copyprod: Refreshing state... [id=copyprod]
╷
│ Error: value of name is not specified or empty
```

### Debug Output
[Full DEBUG outputs](https://gist.github.com/piotrwieckiewicz/9ac29ee5c91c576b011788352aac43f8)

### Terraform and provider versions

```
Terraform v1.0.9
on windows_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.4.2
```

### Important Factoids
[StackOverflow related question](https://stackoverflow.com/questions/70540635/how-to-import-databricks-mount-using-terraform)
@alexott

**Comment by alexott** [comment]
You need to provide all necessary parameters, like, `name`, `s3`, etc. (it wasn't clear from your question)  Import won't generate it for you - that's the task of the [exporter](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/guides/experimental-exporter).

But let have this issue open because import doesn't work for quite a long time (I've tested with 0.3.10 & 0.3.5)

**Comment by pw-bitpeak** [comment]
I understand - I wanted to build full _.tf_ files based on imported resources from **import** function. Is this bad practice?

**Comment by piotrwieckiewicz** [comment]
I understand - I wanted to build full **.tf** files based on imported resources from **import** and **plan** functions. Is this bad practice?

**Comment by alexott** [comment]
It’s not a bad practice, but it’s how terraform works - import requires full definition, it doesn’t generate full definition - that’s why we have a separate exporter functionality

**Comment by nfx** [comment]
@piotrwieckiewicz please don't mix `terraform add` and `terraform import` functionalities ;)

**Comment by piotrwieckiewicz** [comment]
To be honest, I do not understand.
When I use EXPORT command it work and it creates mounts.tf file with 

```hcl
resource "databricks_mount" "copyprod" {
  name = "copyprod"
  s3 {
    bucket_name      = "<my_bucket_name>"
    instance_profile =  "<my_instance_profile>"
  }
}
```

but when I try to use **import** with this newly created rescources the error is still the same as it was, even when all necessary arguments to the resource are defined. Moreover, this import.sh file, which was created by the EXPORT gives the same errors.

**Comment by nfx** [comment]
So, technically we _could consider fixing_ it by introducing a special syntax that is relied upon some sort of url encoding for ID in the command line (or JSON - doesn't really matter that much). Terraform state imports are called in two phases: the ResourceImporter.StateContext callback with ID_1 and then 
![image](https://user-images.githubusercontent.com/259697/147830285-36ef7a10-658e-42d4-be60-3ffcd84c0d9e.png)

though this approach will confuse the users and we'll start getting support tickets for this rarely used functionality. So the decision here, for now, is to drop support for importing mounts. Users can always re-create them as one-off action.
