### ISSUE TITLE
[ISSUE] Azure Active Directory credentials error when trying to create repository in databricks from azure pipelines

### ISSUE THREAD

**Issue by iskandersauma** [databrickslabs/terraform-provider-databricks#1022]
Hi there,

I tried to add a repo to databricks by running the code in a pipeline in azure. The terraform code I use is as seen below

provider "databricks" {
  host = azurerm_databricks_workspace.myworkspace.workspace_url
}

resource "databricks_repo" "nutter_in_home" {
  url = var.git_url
  git_provider="azureDevOpsServices"
}

### Expected Behavior
What should have happened?
It should create a repository in databricks from azure devops repo.

### Actual Behavior
What actually happened?
It returns this error:
Error: Encountered an error with your Azure Active Directory credentials. Please try logging out of Azure Active Directory (https://portal.azure.com) and logging back in. Alternatively, you may also visit User Settings > Git Integration to set up an Azure DevOps personal access token.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions
provider registry.terraform.io/databrickslabs/databricks v0.3.11

Please paste the output of `terraform version`. If version of `databricks` provider is not the latest (https://github.com/databrickslabs/terraform-provider-databricks/releases), please make sure to use the latest one.

### Debug Output
Please add turn on logging, e.g. `TF_LOG=DEBUG terraform apply` and run command again, paste it to gist & provide the link to gist. If you're still willing to paste in log output, make sure you provide only relevant log lines with requests.

It would make it more readable, if you pipe the log through `| grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'`, e.g.:

```
TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
```

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
Are there anything atypical about your accounts that we should know?

**Comment by alexott** [comment]
You need to setup Azure DevOps token as described in [documentation](https://docs.microsoft.com/en-us/azure/databricks/repos#--configure-your-git-integration-with-azure-databricks)

**Comment by iskandersauma** [comment]
@alexott does that not require that I add the token manually? The idea is that the repository should be added with as little manual labour as possible

**Comment by iskandersauma** [comment]
@alexott I assume this is an issue with pipelines? Because I dont get the error if I run the code locally.

**Comment by alexott** [comment]
when you run code in the workspace, workspace is forwarding AAD token to DevOps. But this won't happen when you run it via terraform

**Comment by iskandersauma** [comment]
@alexott I am quite new to pipelines so I dont follow. You mean databricks tries to forward AAD token to azure devops, and this is where the error occur?

**Comment by alexott** [comment]
are you using service principal to execute a pipeline?

**Comment by iskandersauma** [comment]
@alexott I am fairly sure that I do

**Comment by alexott** [comment]
in this case it explains it - right now you can't set DevOps token for service principal, and without that token, it won't able to create repo

**Comment by iskandersauma** [comment]
@alexott okay! I understand. Thanks for the help. Much appreciated
