### ISSUE TITLE
[ISSUE] Provider enhancement request -> additional filters on `databricks_node_type` to control VM version in Azure

### ISSUE THREAD

**Issue by yergi** [databrickslabs/terraform-provider-databricks#1030]
Hi there,

My team is investigating using Terraform to better manage the clusters within our DBX workspaces. One issue we've run into is around the search for the  `databricks_node_type` Data Source. Within Azure, there could be _many_ VM types that match the search criteria we're able to apply, and it seems the provider will return the lowest version of VM family that matches the criteria, instead of the highest (or letting the user somehow control it.

### Configuration
```hcl
data "databricks_node_type" "node" {
    category = "Compute Optimized"
    min_cores = 16
}
```

### Expected Behavior
Returned node type id is "Standard_F16s_v2"

### Actual Behavior
Returned node type id is "Standard_F16s"

### Steps to Reproduce
1. `terraform apply`

### Terraform and provider versions

Terraform v1.1.3
on windows_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.4.4

**Comment by nfx** [comment]
@yergi Why don't you specify node type directly in the cluster then?

**Comment by yergi** [comment]
That’s what we’re attempting to do now by creating a map variable that has the list of exact VMs we want to create pools for. Just thought this might be a helpful enhancement as typically the later versions of VM sizes in Azure have better performance for the same or lower cost. So returning those would likely be more helpful.

Sent from my iPhone

On Jan 10, 2022, at 3:46 PM, Serge Smertin ***@***.***> wrote:

﻿

@yergi<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyergi&data=04%7C01%7C%7C2732eb0d295e4a11382d08d9d47a5651%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774444167668640%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=JrLk9XoLEGlpVV4jBSMBWYGYXffvR5xSbDb%2FOLwuktc%3D&reserved=0> Why don't you specify node type directly in the cluster then?

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdatabrickslabs%2Fterraform-provider-databricks%2Fissues%2F1030%23issuecomment-1009328524&data=04%7C01%7C%7C2732eb0d295e4a11382d08d9d47a5651%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774444167668640%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=fLMF7vFzPoxYyhTTPqIYfRbwaeN11eCS3K6OVBaO0F0%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABZIHL45GYP673QXOX2MWO3UVNAT3ANCNFSM5LUTF2XQ&data=04%7C01%7C%7C2732eb0d295e4a11382d08d9d47a5651%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774444167824903%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=1V9Ry6GqGJt1bozMKjD7Y6stLqIzPSyjWXOweqKceU0%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C2732eb0d295e4a11382d08d9d47a5651%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774444167824903%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=3vgNceGL%2FcRjf%2Bf0%2BjHmW8UNWpvNysarlaruJXYpxQ0%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C2732eb0d295e4a11382d08d9d47a5651%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637774444167824903%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=XtxVK6I5U01LzZkZeWk2XTzV0VdkYfwsTzAIQaFqdeo%3D&reserved=0>.

**Comment by nfx** [comment]
@yergi please try other filters for this data resource from documentation.

**Comment by nfx** [comment]
no general customer interest for 2 weeks, closing the issue.
