### ISSUE TITLE
Creating databricks groups with æøå does not work

### ISSUE THREAD

**Issue by troyel** [databrickslabs/terraform-provider-databricks#1034]
**databricks provider:** 0.4.4
**Issue:** creating groups containing special characters (for example æøå ) gets wrong/different encoding in Databricks Workspace.

Example:
resource "databricks_group" "æøå-test" {
  display_name          = "æøå"
}

causes issue:
```
{
    "@level": "warn",
    "@message": "Provider \"provider[\\\"registry.terraform.io/databrickslabs/databricks\\\"]\" produced an unexpected new value for databricks_group.æøå-test, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .display_name: was cty.StringVal(\"æøå\"), but now cty.StringVal(\"Ã¦Ã¸Ã¥\")",
    "@timestamp": "2022-01-13T12:30:04.589586Z"
}
```

Making the name not match between configuration and Databricks Workspace deployed groups and configuration providing changes on every plan:
```
  # databricks_group.æøå-test must be replaced
-/+ resource "databricks_group" "æøå-test" {
      ~ display_name               = "Ã¦Ã¸Ã¥" -> "æøå" # forces replacement
      ~ id                         = "944677071884272" -> (known after apply)
        # (5 unchanged attributes hidden)
    }
```

**Comment by nfx** [comment]
@troyel this is a configuration drift issue, as unicode characters are returned in a different way from platform and not the issue with provider. please raise a support case.

**Comment by troyel** [comment]
Are you sure @nfx ? This works using the http rest endpoint and the characters are also wrong, e.g. Ã¦Ã¸Ã¥" in stead of "æøå" on the actual created group from Terraform. This works well for the Azure SCIM enterprise application and we just did the same group creation using the Databricks SCIM REST API using ordinary http post. 

Wouldn't that point to some issue with the terraform provider?

**Comment by troyel** [comment]
We have confirmed that we can create groups containing æøå by using the Azure SCIM 2.0 API. Also the terraform provider correctly reads æøå in groups where this is created outside of the provider. But any attempt to create a group with æøå using the Terraform provider does not work (as characters are replaced). 

@nfx could you please elaborate on where to direct this bug, specifically? Is this an Azure issue or Databricks issue?

**Comment by alexott** [comment]
I'm looking into it right now, most probably will fix tomorrow morning

**Comment by troyel** [comment]
Thanks for the swift pick-up @alexott !

**Comment by alexott** [comment]
it's really more a platform issue as SCIM API was treating UTF-8 payload with some default encoding, but this only happens when content type is set to `application/scim+json`, but mostly we're using `application/json` for which this problem didn't happen
