### ISSUE TITLE
[ISSUE] Azure DevOps private repo synchronisation fails with the resource `databricks_repo`

### ISSUE THREAD

**Issue by morufajibike** [databrickslabs/terraform-provider-databricks#1035]
Hi there,

I'm having problems using the `databricks_repo` resource to sync a repo to databricks workspace. It is not clear from the resource [documentation](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/repo) if we can use this resource to clone a private repo or not. 

### Configuration
```
# private Azure DevOps repo
resource "databricks_repo" "this" {
  url = "https://<OrgName>@dev.azure.com/<OrgName>/<ProjectName>/_git/<RepoName>"
  git_provider = "azureDevOpsServices"
  path = "/Repos/Development/"
}
```

### Expected Behavior
Repo should be created in databricks workspace under the specified path.

### Actual Behavior
Deployment failing with the error 203.

### Steps to Reproduce
1. `terraform apply`

### Terraform and provider versions
```
Terraform 0.13.2
Databricks == .terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.3.11/linux_amd64/terraform-provider-databricks_v0.3.11
```

### Debug Output
```
2022/01/13 15:20:08 [ERROR] eval: *terraform.evalReadDataRefresh, err: HTTP request error. Response code: 203
2022/01/13 15:20:08 [ERROR] eval: *terraform.EvalSequence, err: HTTP request error. Response code: 203
```

### Important Factoids
Can we use the `databricks_repo` resource to sync a private repo?

How is the authentication with the code management repos done? 

Through a PAT that must be supplied with the username in the repo url i.e `https://<Username>:<PAT_Token>@dev.azure.com/<OrgName>/<ProjectName>/_git/<RepoName>` or something else?

**Comment by nfx** [comment]
@alexott can you have a look?

**Comment by alexott** [comment]
You need to set DevOps PAT in the Databricks UI -> Settings -> User Settings. ([doc](https://docs.microsoft.com/en-us/azure/databricks/repos#--configure-your-git-integration-with-azure-databricks))

**Comment by alexott** [comment]
Not yet. This option relies on the user's AAD token forwarding and this doesn't exist when you use API. Unfortunately, right now, PAT is only the way

**Comment by morufajibike** [comment]
When you say a "user's AAD token", which user are you referring to? A databricks user or the deployment user/spn?

The resource is being created through a CI/CD pipeline.

**Comment by alexott** [comment]
it's a token of a user who works in workspace interactively, so its token is captured by the platform and could be forwarded to DevOps.
Also, please note that we don't have API for setting that DevOps PAT (yet), so it's impossible to set PAT for service principal

**Comment by faisaleem-na** [comment]
@alexott 
quick question
if i set the PAT in my user settings that would still mean that i would need to use my user account to run my pipeline to deploy the repo to the workspace, correct?
i.e if i set a PAT for userA but my terraform pipeline is being run by serviceprincipalB it would still not be able to deploy the repo resource?
thanks

**Comment by alexott** [comment]
yes, that is correct.

**Comment by alexott** [comment]
Dev team is working on adding that API

**Comment by faisaleem-na** [comment]
is there an issue i can subscribe to for that?

**Comment by alexott** [comment]
No, it's internal thing. As soon as API is available, it will be immediately added to terraform

**Comment by nfx** [comment]
Fixed in https://github.com/databrickslabs/terraform-provider-databricks/pull/1114
