### ISSUE TITLE
[ISSUE] Provider enhancement request: Terminate table-acl-cluster immediately after running ACL commands

### ISSUE THREAD

**Issue by marijncv** [databrickslabs/terraform-provider-databricks#1052]
The terraform-table-acl cluster that is created to run the `databricks_sql_permission` privilege assignments auto-terminates after 10 minutes. However, could the cluster not be terminated immediately after running the ACL commands?

### Expected Behavior
The terraform-table-acl runs the ACL commands, then immediately terminates.

### Actual Behavior
The terraform-table-acl runs the ACL commands, then sits for 10 minutes doing nothing before terminating.

**Comment by nfx** [comment]
@marijncv Unfortunately this can't be done, as there might be thousands of tables to set permissions to and starting thousands of clusters makes no sense. 10 minute auto termination is a reasonable tradeoff.

But in general, you don't have to worry about that, as Unity Catalog  has proper API and databricks_grants set's data object privileges instantaneously (and without this tech cluster workaround).
