### ISSUE TITLE
force ignore existing groups - like for users

### ISSUE THREAD

**Issue by universam1** [databrickslabs/terraform-provider-databricks#1066]
Federation using SCIM can pre create  groups that will cause TF to fail if they exist.
The provider should have the `force` option for **groups** to ignore `cannot create group: ... already exists` errors and implicitly import the specific group into Terraform state.

Same problem, accepted and solved via #1048 for **users**, should be solved same way for **groups** as well.

Using `data "databricks_group"` data provider is not possible if the existence of the group is not known upfront. The data provider should also gracefully fail.

### Expected Behavior

allowing to ignore that case and implicitly import the specific group into Terraform state.

### Actual Behavior
erroring out

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions

v0.4.2

**Comment by nfx** [comment]
This is a feature request rather than an issue. For now - please remove groups from workspaces and let them be managed via Terraform exclusively, to guarantee expected semantics.

**Comment by universam1** [comment]
> This is a feature request rather than an issue. 

Sorry, adjusted the description

> For now - please remove groups from workspaces and let them be managed via Terraform exclusively, to guarantee expected semantics

This is impossible being a fundamental concept of SCIM to manage groups. With other words disabling SCIM is the other option which is not acceptable unfortunately

**Comment by nfx** [comment]
@universam1 So ideally one should use either scim or terraform for user provisioning. If you need to refer give group a permission - simple name reference is enough. If you need to add member to a group - use data source to retrieve id by name. What specific use case other than these two do you have?

**Comment by universam1** [comment]
@nfx Thank you for your response. This is what we have set up - which is fine for day:1 operations, but fails on day:2.
IdP groups are managed out of band and they appear or vanish apart from TF setup, which causes to this provider to fail hard if assumptions of groups are not given.

Two options:

1. look up a group and link using data source: This concept I agree is semantically correct but is broken because the data source fails hard if the group is removed or not added yet. I believe this is a bug in this provider because it should either return 
 a list of all existing groups to iterate/filter over, or fail gracefully if a given one is not found. I can open another issue if you like @nfx

2. let groups be created if missing and ignore if they exist: Not a clean solution, but since I see you going that route for users in #1048 I assume this is the workaround you prefer...

**Comment by universam1** [comment]
Thank you @nfx for this quick solution!

**Comment by nfx** [comment]
@universam1 it's @nkvuong to thank ;)

**Comment by universam1** [comment]
👏🏻 Thank you @nkvuong this fast solution is appreciated!
