### ISSUE TITLE
[ISSUE] Databricks workspace gets created in failed state when created using terraform

### ISSUE THREAD

**Issue by hrdamani** [databrickslabs/terraform-provider-databricks#1068]
Hi there,

@alistair-segment and I am trying to create a databricks workspace using terraform. The workspace is created successfully but in a failed state. Thus, we cannot launch the workspace. This will cause an hinderance to create and run a cluster in azure datalakes using terraform.

### Configuration
```hcl
# resource "azurerm_databricks_workspace" "segment_databricks_workspace" {
  name                = "tf-databricks-workspace"
  location            = "westus2"
  resource_group_name = "stage-datalake"
  sku                 = "standard"
}
```

### Expected Behavior
<img width="1191" alt="Screen Shot 2022-01-28 at 9 25 11 AM" src="https://user-images.githubusercontent.com/87546021/151484639-23233270-128b-4f58-a947-6676e9e230d2.png">

### Actual Behavior
<img width="1195" alt="Screen Shot 2021-11-22 at 3 25 39 PM (1)" src="https://user-images.githubusercontent.com/87546021/151484479-390e80ec-d99a-4519-88fb-26d827d87e82.png">

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions

```Terraform v0.14.1```

### Debug Output
```
module.segment_data_lake_databricks_cluster.azurerm_databricks_workspace.segment_databricks_workspace: Creation complete after 2m23s [id=/subscriptions/d51ceb2a-6052-44e5-bde6-2e491819e019/resourceGroups/stage-datalake/providers/Microsoft.Databricks/workspaces/tf-databricks-workspace]
```

**Comment by nfx** [comment]
this issue is related to `azurerm` provider, not this one. please create it in appropriate repo
