### ISSUE TITLE
[FEAT] Data Resource Request for Jobs

### ISSUE THREAD

**Issue by rondefreitas** [databrickslabs/terraform-provider-databricks#1075]
Hello,

I've been attempting to switch some of my team's workflows from leveraging DBX for job deployment to leveraging the Terraform provider. One difference I've noticed is that there is a mismatch in provider behavior between the two. DBX will attempt to match jobs based on their name, while Terraform will only match them based on their IDs. This means that to migrate my jobs over I'm having to manually refresh each job definition based on the IDs.

DBX is a stateless deployment tool which exclusively uses job names for matching for deployment and configuration update, and has fairly robust name-based support for some other attributes, which could be useful for our deployment environment. The list can be found here: https://dbx.readthedocs.io/en/latest/named_properties.html

In our environment, I'm hoping to facilitate this repo structure using purely terraform instead of both terraform and DBX:

- **base_repo**
  - scripts/tf (workspace configuration via Terraform)
  - src/\*/scala/\* (code files)
- **project_repo**
  - scripts/tf (job deployment ONLY, replaces scripts/dbx)
  - src/\*/scala/\* (code for individual jobs)

The lack of name-based matching however, appears to force me to either use the databricks cli to acquire the list of jobs, profiles, etc and pass them in as variables to the *project_repo* terraform scripts via a wrapper script, or continue to use dbx for those projects.

Is there a good way to facilitate what I'm looking for using the terraform provider alone?

**Comment by rondefreitas** [comment]
@nfx I agree that Terraform is the way to go.
In fact, if there were a data source for instance pools and jobs, I could reproduce almost anything I was previously doing in DBX.

**Comment by nfx** [comment]
Please create a separate issue for instance pool data resource and rename this one to data resource request.

**Comment by nfx** [comment]
@nkvuong curious to try making a data resource? 😜

**Comment by rondefreitas** [comment]
I believe the other required change to get this functionality is to allow the Job ID to be specified in the job definition

**Comment by nfx** [comment]
We can't specify id in the job because id is something that's computed.

**Comment by rondefreitas** [comment]
If that's the case, and there's no way to override it, there's no benefit
whatsoever to this feature.

**Comment by nfx** [comment]
@rondefreitas This is just how terraform works :)

Can you please describe how you use dbx with code samples?
