### ISSUE TITLE
[FEATURE] Optimize Mount Points refresh

### ISSUE THREAD

**Issue by pgrandjean** [databrickslabs/terraform-provider-databricks#1077]
Hi there,

Being able to manage a few mount points with the Databricks provider is a bliss. However, when there are more than hundreds of mount points to manage, the refresh time becomes huge!

The problem is that for each mount point, a new WS request is made. Each request/response takes anywhere from 10 to 60 seconds! So for 300 mount points (my case), it may take up to 5 hours to refresh the terraform state!

The aim of this request is to ask for an optimized implementation where - internally - mount points would be validated in batches rather than one-by-one. This would greatly improve the performance when refreshing mount point states.

Best,
Patrick.

**Comment by alexott** [comment]
Terraform has no notion of batches, each resource of the same type is independent...

**Comment by pgrandjean** [comment]
OK. Nevertheless, I wonder how this can be optimized. For instance, I see a lot of `dbutils.fs.refreshMounts()`. Would it be possible to remove these calls or optionally switch them off?

**Comment by nfx** [comment]
@pgrandjean The only way to speed up mounts is through proper API, that doesn't exist at the moment. Currently terraform plugin is using technical cluster to perform mounting.
