### ISSUE TITLE
[FEATURE] Add a data source to get information about current workspace

### ISSUE THREAD

**Issue by alexott** [databrickslabs/terraform-provider-databricks#1079]
It would be useful to have a data source that would return information about current workspace, such as, workspace URL - this information isn't provided directly if you use Databricks CLI, or environment variables, but would be useful, for example, when using MLflow webhooks.

**Comment by nfx** [comment]
Why not adding it to current_user?

**Comment by nfx** [comment]
@alexott also look at the X-Databricks-Workspace-Id response header.
