### ISSUE TITLE
[ISSUE] The databricks_group_member resource shouldn't allow you to add users to the "users" group

### ISSUE THREAD

**Issue by Xophmeister** [databrickslabs/terraform-provider-databricks#1088]
### Configuration

```hcl
data "databricks_group" "users" {
  display_name = "users"
}

resource "databricks_user" "test" {
  user_name    = "test@example.com"
  display_name = "Testy McTestface"
}

resource "databricks_group_member" "membership" {
  group_id  = data.databricks.users.id
  member_id = databricks_user.test.id
}
```

### Expected Behavior

The `users` group is a pseudogroup of all users in Databricks, which you should never explicitly add users to. The provider should forbid this.

### Actual Behavior

This works fine. The problem comes when you try to destroy the membership resource: The Databricks API forbids this and so `terraform destroy` will fail.

### Steps to Reproduce

1. `terraform apply`
2. `terraform destroy`

### Terraform and provider versions

```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.4.7
```

**Comment by nfx** [comment]
`databricks_group_member` knows nothing of system groups - it operates purely on IDs.
