### ISSUE TITLE
[FEATURE] Hashicorp Vault Support

### ISSUE THREAD

**Issue by ekhaydarov** [databrickslabs/terraform-provider-databricks#1096]
Hi there,

Looking at Databricks own blog post [here](https://databricks.com/blog/2020/09/11/announcing-databricks-labs-terraform-integration-on-aws-and-azure.html) it claims that Hashicorp Vault is already supported. Yet looking around this provider it seems only Azure Key Vault is supported.  Am I missing something or is this feature not supported yet? If not would it be reasonable ot expect it to be supported soon?

Thanks

**Comment by nfx** [comment]
@ekhaydarov you can use Hashicorp Vault to store secrets, but then you have to copy secret from `vault_generic_secret` into `databricks_secret`.
