### ISSUE TITLE
[ISSUE] external_id for databricks_user with force=true isn't set

### ISSUE THREAD

**Issue by pietern** [databrickslabs/terraform-provider-databricks#1097]
### Configuration
```hcl
resource "databricks_user" "foo" {
  user_name = "foo@bar.com"
  force     = true
}
```

### Expected Behavior

Upon apply, the pre-existing user is imported into TF state, and running `apply` again doesn't show state skew.

### Actual Behavior

The next `apply` shows state skew showing that the `external_id` property should be set to `null`.

When applied, this doesn't happen. I suspect `external_id` must be set as `computed`, or must be imported if is isn't set.

### Terraform and provider versions

0.4.7

**Comment by nfx** [comment]
@pietern try adding `tf:"suppress_diff"` tag on `external_id` field. should help. slack me if it doesn't.
