### ISSUE TITLE
[feat] Create data resource to get tables/views within a Unity Catalog database

### ISSUE THREAD

**Issue by vadivelselvaraj** [databrickslabs/terraform-provider-databricks#1105]
Currently, to grant permissions for tables and views associated with a **Unity Catalog** a hard-coded list of them has to be maintained in Terraform which is far from ideal. It'd be great to have a data resource like the below which can be then referenced during the grant phase.

```hcl
data "databricks_tables" "db1_tables" {
  catalog_id = databricks_catalog.main.id
  schema_id = databricks_schema.schema.id
}

data "databricks_views" "db1_views" {
  catalog_id = databricks_catalog.main.id
  schema_id = databricks_schema.schema.id
}

resource "databricks_grants" "table_read_grants" {
  for_each = databricks_tables.db1_tables.table_name
  table  = each.key

  grant {
    principal  = "db1_read_user_group"
    privileges = ["SELECT"]
  }
}

resource "databricks_grants" "view_read_grants" {
  for_each = databricks_tables.db1_tables.table_name
  view  = each.key

  grant {
    principal  = "db1_read_user_group"
    privileges = ["SELECT"]
  }
}
```

**Comment by nfx** [comment]
@vadivelselvaraj Interesting feature suggestion. Just in case - schema id already has catalog name in it https://github.com/databrickslabs/terraform-provider-databricks/blob/59c12c785dcd28d96218860ff493d49ea8c98f13/catalog/resource_schema.go#L60

Let's keep it open for a week or few to collect votes.

**Comment by ebarault** [comment]
Hi @nfx,
I tested the data source, it works great, thank-you.
Do you foresee a way/opportunity to add support for regex based filtering of tables from a schema?

**Comment by nfx** [comment]
@ebarault nope. i don't want to support that, as we have https://www.terraform.io/language/functions as part of HCL.

**Comment by ebarault** [comment]
@nfx fair enough

**Comment by vadivelselvaraj** [comment]
@nfx couple of questions.

1. Will this work for views within UC? I don't see a terraform resource for it. I wonder if they're just listed as tables.
2. Can this data source be used for tables/views within a local hive_metastore?

Thanks!
