### ISSUE TITLE
[DOC] Incorrect example for Create table

### ISSUE THREAD

**Issue by sridharitv** [databrickslabs/terraform-provider-databricks#1113]
Hi there,

### Affected Resource(s)
https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/table#example-usage

### Expected Details
N/A

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] schema_name attribute of databricks_table.thing should be passed `databricks_schema.things.name` instead of `databricks_schema.things.id`
- [ ] Following the example given in the documentation gives `Missing cloud file system scheme` error in Terraform v0.14.11

**Comment by nfx** [comment]
@sridharitv currently we have no cycles for this issue, but PRs are very welcome
