### ISSUE TITLE
[ISSUE] The provider allows creating single-node clusters with two nodes

### ISSUE THREAD

**Issue by moredatapls** [databrickslabs/terraform-provider-databricks#1118]
### Configuration

Here's my (simplified) configuration; note the `num_workers = 1` in the cluster definition:

```hcl
locals {
  databricks_spark_version = "10.1.x-scala2.12"

  default_single_node_config = {
    "spark.databricks.cluster.profile" = "singleNode"
    "spark.master"                     = "local[*]"
  }
}

resource "databricks_instance_pool" "nodes_d13" {
  instance_pool_name = "D13"
  min_idle_instances = 0
  max_capacity       = 20
  node_type_id       = "Standard_D13_v2"

  idle_instance_autotermination_minutes = 15

  preloaded_spark_versions = [
    local.databricks_spark_version
  ]

  azure_attributes {
    availability = "SPOT_AZURE"
  }
}

resource "databricks_cluster" "interactive" {
  cluster_name = "Interactive cluster"

  spark_version    = local.databricks_spark_version
  instance_pool_id = databricks_instance_pool.nodes_d13.id

  spark_conf = local.default_single_node_config

  custom_tags = {
    "ResourceClass" = "SingleNode"
  }

  num_workers = 1

  autotermination_minutes = 10
}
```

### Expected Behavior

The provider should've failed to create the cluster (or created an instance with only a single node).

### Actual Behavior

The provider ended up creating a cluster in single-node configuration with two workers attached, which is a configuration that the Databricks workspace UI does not permit. That's how it ended up looking like in our Databricks workspace:

![Screenshot 2022-02-15 at 13 59 04](https://user-images.githubusercontent.com/11437312/154067899-67385e15-e374-4fac-82d5-e4953771e833.png)

Notice the DBU, one D13 should consume 2 DBU/h:

![Screenshot 2022-02-15 at 13 58 53](https://user-images.githubusercontent.com/11437312/154067905-4709df79-1e8f-4cfd-abf4-fbf35bfce81e.png)

When I try to edit the cluster, this happens:

![Screenshot 2022-02-15 at 13 59 15](https://user-images.githubusercontent.com/11437312/154067933-5e31cff7-2a7c-4672-af87-875fbefed59f.png)

It allocated two nodes, but the jobs were only executed on one of the nodes.

### Steps to Reproduce

Apply the Terraform definition above in some workspace.

### Terraform and provider versions

Terraform v1.1.5
on darwin_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.4.9
+ provider registry.terraform.io/hashicorp/azurerm v2.95.0

**Comment by nfx** [comment]
Please consult with resource documentation and support teams for the right resource configuration.
