### ISSUE TITLE
[FEATURE] Pinned Cluster Support

### ISSUE THREAD

**Issue by nfx** [databrickslabs/terraform-provider-databricks#113]
SDK has support for pinning/unpinning the cluster, though it's not available through the resource. 

We should add `is_pinned = true/false` to resource and make sure cluster deletion would unpin the cluster before doing so, as `Cannot delete pinned cluster 0000-111222-abcd0. Please ask an admin to unpin the cluster first.` errors are appearing in current version.

**Comment by alexott** [comment]
I can grab that feature.  For deletion - should we always unpin cluster when deleting, or should we have a separate flag to unpin?

**Comment by nfx** [comment]
@alexott deletion already works - https://github.com/databrickslabs/terraform-provider-databricks/blob/master/compute/clusters.go#L200
