### ISSUE TITLE
[ISSUE] Provider issue: Git Integration and Workspace Settings

### ISSUE THREAD

**Issue by wesleyemery** [databrickslabs/terraform-provider-databricks#1134]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Configuration
```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "= 2.63"
    }
    databricks = {
      source = "databrickslabs/databricks"
      version = "0.5.0"
    }
  }
}

provider "azurerm" {
  features {}
  skip_provider_registration = true
}

data "azurerm_databricks_workspace" "this" {
  name                = "databricks-instance"
  resource_group_name = "db-rg"
}

provider "databricks" {
  azure_workspace_resource_id = data.azurerm_databricks_workspace.this.id
}
resource "databricks_repo" "sweet_test" {
  url = "https://github.com/user/demo.git"
}
```

### Expected Behavior
What should have happened?
- I want to be able to add the `git integration` to add my `PAT` under `user setting` using terraform 
- Also, under workspace setting, I would like to set: `DBFS File Browser: Enabled` and `Files in Repos: Enabled` using terraform
Is this possible?

### Actual Behavior
What actually happened?
``` 
│ Error: cannot create repo: Missing Git provider credentials. Go to User Settings > Git Integration to add your personal access token. Using azure-cli auth: host=https: azure_workspace_resource_id=/
``` 
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions
```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "= 2.63"
    }
    databricks = {
      source = "databrickslabs/databricks"
      version = "0.5.0"
    }
  }
}
```

Please paste the output of `terraform version`. If version of `databricks` provider is not the latest (https://github.com/databrickslabs/terraform-provider-databricks/releases), please make sure to use the latest one.
```
# terraform version
Terraform v1.0.11
on darwin_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.5.0
+ provider registry.terraform.io/hashicorp/azurerm v2.63.0

Your version of Terraform is out of date! The latest version
is 1.1.6. You can update by downloading from https://www.terraform.io/downloads.html
```
### Debug Output
Please add turn on logging, e.g. `TF_LOG=DEBUG terraform apply` and run command again, paste it to gist & provide the link to gist. If you're still willing to paste in log output, make sure you provide only relevant log lines with requests.

It would make it more readable, if you pipe the log through `| grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'`, e.g.:

```
TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
```

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
Are there anything atypical about your accounts that we should know?

**Comment by alexott** [comment]
The item 1 is [clearly documented](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/repo):

> To create a Repo from a private repository you need to configure Git token as described in the [documentation](https://docs.databricks.com/repos.html#configure-your-git-integration-with-databricks). Right now this is possible only via Databricks UI **due lack of corresponding REST API**. For the same reason, it also doesn't work for Service Principals.

For both questions please connect to Customer Success Engineer assigned to your account.

**Comment by wesleyemery** [comment]
how about the workspace setting using terraform?

Are there any plans on adding a corresponding API? Have you worked with Microsoft on that being that this will be a common configuration option? 
 I've contacted the account rep and he is going to contact your team. 

thanks for your support on this.

**Comment by nfx** [comment]
@wesleyemery terraform resource is in private preview. please reach out to your Databricks representative - Solutions Architect or CSE
