### ISSUE TITLE
[ISSUE] Terraform Meta Block "timeouts" Reporting as Unsupported 

### ISSUE THREAD

**Issue by HamiltonHord** [databrickslabs/terraform-provider-databricks#1142]
Hi there,

### Configuration
```hcl
resource "databricks_sql_endpoint" "endpoint" {
  name                 = "endpoint"
  cluster_size         = "2X-Large"
  min_num_clusters     = 0
  max_num_clusters     = 7
  auto_stop_mins       = 30
  spot_instance_policy = "COST_OPTIMIZED"

  enable_serverless_compute = true

  instance_profile_arn = databricks_instance_profile.iam_profiles["example"].id

  timeouts {
    create = "30m"
  }
}
```

### Expected Behavior
Should have used the extra Terraform resource meta argument and extended the creation timeout built into terraform.

### Actual Behavior
Error message from terraform:

```
Error: Unsupported block type

  on modules/east1_workspace/sql_endpoints.tf line 24, in resource "databricks_sql_endpoint" "looker_e1":
  24:   timeouts {

Blocks of type "timeouts" are not expected here.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

### Terraform and provider versions

$ terraform -v
Terraform v0.13.7
+ provider registry.terraform.io/databrickslabs/databricks v0.5.0
+ provider registry.terraform.io/hashicorp/aws v3.74.0

### Debug Output
Please add turn on logging, e.g. `TF_LOG=DEBUG terraform apply` and run command again, paste it to gist & provide the link to gist. If you're still willing to paste in log output, make sure you provide only relevant log lines with requests.

It would make it more readable, if you pipe the log through `| grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'`, e.g.:

```
TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
```

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
Are there anything atypical about your accounts that we should know? 
N/A

**Comment by kuntalkumarbasu** [comment]
> there is no support for such block in SQL Endpoints - refer to [documentation](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/sql_endpoint) for supported parameters. The [Terraform documentation](https://www.terraform.io/language/resources/syntax#operation-timeouts) says that "some resources" support it, not "all resources" support it.
> 
> 
> 
> Please file feature request, or better, PR if you need such functionality.

As per the document you shared the timeout is supported. Can you please double check

**Comment by nfx** [comment]
@kuntalkumarbasu we'll investigate this as soon as we can. stay tuned.
