### ISSUE TITLE
[ISSUE] UC default catalog name is not applied

### ISSUE THREAD

**Issue by ebarault** [databrickslabs/terraform-provider-databricks#1147]
### Configuration
```hcl
resource "databricks_metastore" "this" {
  name          = var.name
  storage_root  = "s3://${local.bucket_name}"
  owner         = var.owner
  force_destroy = true
}

resource "databricks_metastore_assignment" "this" {
  for_each     = toset(var.workspaces)
  metastore_id = databricks_metastore.this.id
  workspace_id = each.value
  default_catalog_name = "default"
}
```

### Expected Behavior
What should have happened?

When created, and assigned to a workspace, the default catalog which is created automatically should be named after the value of the `default_catalog_name` attribute. 

### Actual Behavior
The name of the default catalog is **"main"** no matter the value of the `default_catalog_name` attribute.

### Steps to Reproduce
1. `terraform apply` with `default_catalog_name` set to **"default"**
2. Navigate the UC in a Databricks workspace and check the name of the default catalog.

### Terraform and provider versions

terraform 1.1.0
databricks provider 0.5.0

### Important Factoids
I can't figure why the `default_catalog_name` attribute is at the `databricks_metastore_assignment`module level rather than at the `databricks_metastore` module level.

**Comment by nfx** [comment]
@ebarault it's `hive_metastore` and not `main` as default catalog

**Comment by ebarault** [comment]
hi @nfx i have it in before my eyes, and i'm positive it's "main"

in the following screenshot, "rd" is the name of a catalog i created, "main" was automatically created when creating a Unity Catalog metastore, and "hive_metastore" is the name of the worskspace's local metastore.
<img width="168" alt="image" src="https://user-images.githubusercontent.com/12000935/157042720-d030d983-eddc-452c-b4b2-55e50c943945.png">

**Comment by nfx** [comment]
@ebarault these are all limitations/designs of Unity Catalog platform. escalate it to your Databricks representative :) i've done everything reasonably possible within TF plugin for it to make sense for infra as a code. can't do more :P

**Comment by nfx** [comment]
@ebarault and please update to the latest version.
