### ISSUE TITLE
[ISSUE] `databricks_service_principal` not accepting a "known after apply" `application_id`

### ISSUE THREAD

**Issue by alex-davies** [databrickslabs/terraform-provider-databricks#1165]
`databricks_service_principal` is failing to validate the `application_id` if it is derived from a dependant resource (i.e. Known after apply). 

When creating an `azuread_application` and `databricks_service_principal` in the same plan/apply, the `databricks_service_principal` fails to recognize an `application_id` has been set

if the `azuread_application`  is applied first. Then the `databricks_service_principal` is applied separately. Then the issue does not occur

### Configuration
```hcl
data "azurerm_client_config" "current" {}

resource "azuread_application" "service" {
  display_name     = "my-ad-app"
  sign_in_audience = "AzureADMyOrg"
  owners           = [data.azurerm_client_config.current.object_id]
}

resource "databricks_service_principal" "service" {
  display_name          = azuread_application.service.display_name
  application_id        = azuread_application.service.application_id
}
```

### Expected Behavior
1. Azure AD app is created
2. Databricks principal is created linked to the azure app

### Actual Behavior

When planning an `Error: application_id is required for service principals in Azure Databricks` is output

### Steps to Reproduce
This can be reproduced using a azure databricks. Error is produced when running `terraform plan`

### Terraform and provider versions
```
Terraform v1.0.5
on windows_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.5.2
+ provider registry.terraform.io/hashicorp/azuread v2.18.0
+ provider registry.terraform.io/hashicorp/azurerm v2.96.0
```

**Comment by nfx** [comment]
@alex-davies Databricks Platform API on Azure will throw an error if `application_id` is not specified. can you build the provider locally and comment out these and see what happens:

https://github.com/databrickslabs/terraform-provider-databricks/blob/17a67b140bda8c54f095122f006051ce2cff832d/scim/resource_service_principal.go#L88-L91

well-tested PRs are welcome.
