### ISSUE TITLE
[ISSUE] databricks_mount with Azure AD passthrough is slow and leads to expired tokens

### ISSUE THREAD

**Issue by dvasdekis** [databrickslabs/terraform-provider-databricks#1168]
### Configuration
```hcl
...
resource "databricks_mount" "mymount" {
  name       = "mymount"
  cluster_id = databricks_cluster.dbcluster.id
  uri = "abfss://mymount@project_data_lake_storage_account_name.dfs.core.windows.net"
  extra_configs = {
    "fs.azure.account.auth.type" : "CustomAccessToken",
    "fs.azure.account.custom.token.provider.class" : "{{sparkconf/spark.databricks.passthrough.adls.gen2.tokenProviderClassName}}",
  }
}
...
```

### Expected Behavior
It works within a second or so.

### Actual Behavior
It takes forever to work - around 5-10 minutes in my testing. But it does work very nicely!

### Steps to Reproduce
`terraform apply`

### Terraform and provider versions
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.5.2
+ provider registry.terraform.io/hashicorp/azuread v2.18.0
+ provider registry.terraform.io/hashicorp/azurerm v2.96.0

### Important Factoids
The new AD passthrough mounts work great and they are a key part of our Terraform now! But because we've used about 25 of them in total, our terraform apply has ground to a halt and now takes about 30 minutes, instead of the 1-5 mins that it used to.
We want to create more but we're at the point where token expiry starts to become an issue.

**Comment by alexott** [comment]
It's impossible to do fast because there is no corresponding API, and mount is done by spinning up the cluster, and then executing commands on it. Token expiration is more concerning, can you provide a log as described in issue template

**Comment by nfx** [comment]
Please start switching to Unity Catalog external locations & storage credentials.
