### ISSUE TITLE
[ISSUE] Unity Catalog delta managed tables are not actually created

### ISSUE THREAD

**Issue by ebarault** [databrickslabs/terraform-provider-databricks#1174]
**Note**: we're using AWS S3 as the storage backend for Unity Catalog metastore

### Configuration
```hcl
resource "databricks_table" "this" {
  name               = "test"
  
  catalog_name       = "main"
  schema_name        = "default"
  
  table_type         = "MANAGED"
  data_source_format = "DELTA"

  column {
    name      = "id"
    position  = 0
    type_name = "INT"
    type_text = "int"
    type_json = "{\"name\":\"id\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{}}"
  }
}
```

### Expected Behavior
When creating a delta managed table with terraform, a new folder should be created in the S3 metastore bucket, containing the delta table metadata. The table should be available for writes from a cluster.

### Actual Behavior
No new folder is created in S3.
When describing the table from a cluster the following error is returned telling that the table location does not exist:
```
DESCRIBE TABLE EXTENDED main.default.test;
```
```
Error in SQL statement: AnalysisException: mcfs-s3://t-03884b36-c9e6-4046-90f1-383c8104bcf5+***REDACTED_BUCKET_NAME***/0d044fdc-c22f-418d-8cc1-9eec37d31ce5/tables/03884b36-c9e6-4046-90f1-383c8104bcf5 doesn't exist;
DescribeRelation true, [col_name#91, data_type#92, comment#93]
+- ResolvedTable com.databricks.sql.managedcatalog.UnityCatalogV2Proxy@380caeb, default.test, DeltaTableV2(org.apache.spark.sql.SparkSession@744649c5,mcfs-s3://t-03884b36-c9e6-4046-90f1-383c8104bcf5+***REDACTED_BUCKET_NAME***/tables/03884b36-c9e6-4046-90f1-383c8104bcf5,Some(CatalogTable(
Database: datalake
Table: test
Owner: ***REDACTED_OWNER***
Created Time: Thu Mar 10 22:44:45 UTC 2022
Last Access: UNKNOWN
Created By: Spark 
Type: MANAGED
Provider: delta
Location: mcfs-s3://t-03884b36-c9e6-4046-90f1-383c8104bcf5+***REDACTED_BUCKET_NAME***0d044fdc-c22f-418d-8cc1-9eec37d31ce5/tables/03884b36-c9e6-4046-90f1-383c8104bcf5
Schema: root
 |-- id: integer (nullable = true)
)),Some(rd.datalake.test),None,Map(),org.apache.spark.sql.util.CaseInsensitiveStringMap@1f)
```

When Trying to insert data, the following error is returned:
```
INSERT INTO rd.datalake.test VALUES (10);
```
```
com.databricks.backend.common.rpc.DatabricksExceptions$SQLExecutionException: org.apache.spark.sql.AnalysisException: `main`.`default` is not a Delta table.
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. `DESCRIBE TABLE EXTENDED main.default.test;`
3. `INSERT INTO main.default.test VALUES (10);`

### Terraform and provider versions

Databricks provider 0.5.2
Terraform 1.1.0

**Comment by nfx** [comment]
So, this is limitation of the underlying functionality: you can't really create a table without underlying data. I'm closing this provider issue, please open up a private preview bug with your Databricks representative (you have one, as it was them requesting enablement of UC).

**Comment by ebarault** [comment]
@nfx so yes, I've been digging a bit around this one, and I will communicate with our representative to raise an issue.
However: there would solutions to deal with this and make it working:

- no change in the underlying functionality: use a cluster to manage the table creation right inside the terraform module, just as the dbfs mount module workk
- with changes : have the control plane create the required delta metadata files on the S3 bucket (the control plane has full access to the bucket)
- with changes : finalize the table creation by spark based on the UC metadata at the first operation triggered from a cluster

**Comment by nfx** [comment]
@ebarault i already saw your issue and added relevant engineering team representatives to the thread. 

on a side note, UC is pretty bleeding-edge preview product and it may take some time to add relevant validations into all places across the stack.

**Comment by ebarault** [comment]
@nfx thank you, just doing my best to help here
