### ISSUE TITLE
[ISSUE] Project with cluster terminated 30+ days ago made unusable.

### ISSUE THREAD

**Issue by dugernierg** [databrickslabs/terraform-provider-databricks#1177]
Hi there,

It appears there might be an issue with terraform projects containing unpinned clusters that have been terminated 30+ days ago. Indeed, because the cluster has been permanently removed from the workspace, the provider, upon calling the Cluster API, will get an error message and won't progress further.

Such a resource seemingly can't be deleted by being removed from the project declaration, and the provider won't try to recreate it either, it will simply return the following error message:

> │ Error: cannot read cluster: Cannot access cluster that was terminated or unpinned more than 30 days ago.
> │ Error: Cannot access cluster <cluster_id> that was terminated or unpinned more than 30 days ago.

This, as far as I can tell, essentially bricks the project.

### Configuration

though probably not that relevant, here is my cluster configuration:

```hcl
resource "databricks_cluster" "project_etl_cluster" {
  cluster_name            = "project_ETL"
  spark_version           = "9.1.x-scala2.12"
  node_type_id            = "i3.4xlarge"
  driver_node_type_id     = "i3.xlarge"
  autotermination_minutes = 20
  enable_local_disk_encryption = true

  spark_env_vars          = {
    PYSPARK_PYTHON = "/databricks/python3/bin/python3"
  }
  spark_conf              = {
    "spark.databricks.hive.metastore.glueCatalog.enabled": true
    "spark.databricks.adaptive.autoOptimizeShuffle.enabled": true
    "spark.sql.adaptive.optimizeSkewedJoin.enabled": true
    "spark.databricks.io.cache.enabled": true
    "spark.databricks.io.cache.maxDiskUsage": "50g"
    "spark.databricks.delta.schema.autoMerge.enabled": true    
    "spark.databricks.io.cache.maxMetaDataCache": "2g"    
  }
  autoscale {
    min_workers = 1
    max_workers = 8
  }
  aws_attributes {
    instance_profile_arn    = local.instance_profile_arn
    availability            = "SPOT_WITH_FALLBACK"
    first_on_demand         = 1
    spot_bid_price_percent  = 100
    zone_id                 = "eu-west-1"
  }

  library {
    pypi {
      package = "Shapely>=1.7.0"
    }
  }

   library {
    pypi {
      package = "libgeohash>=0.1.1"
    }
  }
```

### Expected Behavior
Ideally, the provider should probably treat that specific error message as a "create" when the command `terraform plan` is ran, and  recreate a new cluster with the same configurations and name on `terraform apply`. It shouldn't generate any conflict since the previous one is long destroyed.

### Actual Behavior
Seemingly permanently bricked pipeline?

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Have a terraform project with an unpinned cluster terminated 30+ days ago and thus deleted.
2. `terraform plan`

### Terraform and provider versions

Terraform v1.0.1
Provider V0.5.2

### Factoids

If I would have to guess, I would say it's related on how [resourceClusterRead manages error on clusterAPI.Get() 
](https://github.com/databrickslabs/terraform-provider-databricks/blob/43b4996851ed5df75f97c4eb2bb4174432532b10/clusters/resource_cluster.go#L187).

Thanks for your time and help!

**Comment by nfx** [comment]
Should be part of Monday release

**Comment by nfx** [comment]
For now you can "break the glass" and "terraform state rm" that resource to unbrick the pipeline.

**Comment by dugernierg** [comment]
@nfx Wow thanks for the super fast reply!

Also as a side note, I apologize for the radio silence on the fork I made a couple months. I couldn't make the testing script work on Windows, and couldn't afford the time on the clock to investigate it further.

**Comment by nfx** [comment]
by the way, your delta cache size could be increased, like 4x or something.

**Comment by dugernierg** [comment]
Reopening the thread because it seems the latest release didn't quite fix the issue.

See the error below:

```Initializing provider plugins...
- Finding databrickslabs/databricks versions matching "~> 0.5.3"...
- Finding hashicorp/random versions matching "3.1.0"...
- Finding hashicorp/local versions matching "2.1.0"...
- Finding latest version of hashicorp/aws...
- Installing hashicorp/random v3.1.0...
- Installed hashicorp/random v3.1.0 (signed by HashiCorp)
- Installing hashicorp/local v2.1.0...
- Installed hashicorp/local v2.1.0 (signed by HashiCorp)
- Installing hashicorp/aws v4.5.0...
- Installed hashicorp/aws v4.5.0 (signed by HashiCorp)
- Installing databrickslabs/databricks v0.5.3... 
- Installed databrickslabs/databricks v0.5.3 (signed by a HashiCorp partner, key ID ##############)
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections it made above. Include this file in your version control repository
so that Terraform can guarantee to make the same selections by default when
you run "terraform init" in the future.
Terraform has been successfully initialized!
You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.
If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
╷
│ Error: Cannot access cluster ####-######-######## that was terminated or unpinned more than 30 days ago.
│ 

╵
time=[202](https://gitlab.#####.com/#######/-/jobs/########)2-03-15T09:24:36Z level=error msg=1 error occurred:
	* exit status 1
Cleaning up project directory and file based variables
00:00
ERROR: Job failed: command terminated with exit code 1```

**Comment by nfx** [comment]
@dugernierg please create a new issue and provide debug logs as stated in the instructions
