### ISSUE TITLE
[FEATURE] Add support for importing dashboards, queries, widgets and visualizations

### ISSUE THREAD

**Issue by allebacco** [databrickslabs/terraform-provider-databricks#1181]
Hi there,

I have multiple SQL dashboards, with queries, widgets and visualizations in my project. I would like to save them using Terraform in a way that it will be easy to restore them if erroneous changes happens on the UI. Moreover, in this way I can store them on a git repository.

### Expected Behavior

The resources `databricks_sql_dashboard`, `databricks_sql_query`, `databricks_sql_visualization` and `databricks_sql_widget` should be importable with a command like:

```bash
terraform import databricks_sql_dashboard.this <dashboard-id>
```

### Actual Behavior

The documentation of the version 0.5.2 states that:

> Importing this resource is not currently supported.

in the _import_ section.

### Terraform and provider versions

Terraform provider 0.5.2.

**Comment by nfx** [comment]
@allebacco almost all resources of this provider are importable by default. did you try `terraform import databricks_sql_dashboard.this <dashboard-id>`?

**Comment by allebacco** [comment]
@nfx It works, thanks.

I have not tried the execution before creating the issue because the documentation at (https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/sql_dashboard#import) states that import is not supported.

So it seems to be only a problem with documentation, not the provider itself.

**Comment by nfx** [comment]
@allebacco pull requests are welcome ;)

**Comment by nfx** [comment]
@allebacco Any updates on the PR?

**Comment by allebacco** [comment]
No, I have no time to improve the documentation now. Could we leave the issue open so i could refer to it when opening a PR? Probably we need to update the title to reflect that the feature should be present, but the documentation is not up to date.

**Comment by nfx** [comment]
v0.5.5 gets automated configuration generator for this :)
