### ISSUE TITLE
Issue with adding gitlab credentials to the databricks for "Git integration"

### ISSUE THREAD

**Issue by greatemouse** [databrickslabs/terraform-provider-databricks#1182]
Hi,

we have configured our infrastructure by terraform, now we want to config GitLab integration with databriks to automate notebook and job deployment. I sow that now this step is available only via databricks UI interface, can you share some estimate, when it's will be available for the terraform or API. Or may you share some other options?

Thank you!

**Comment by alexott** [comment]
There is no API for that yet, but you can contact solution architect, or account executive, or customer success engineer who is assigned to your account and ask them about that issue.

**Comment by greatemouse** [comment]
Unfortunately, we haven't specific databricks manager or customer success engineer, because we use Azure Databricks.

**Comment by nfx** [comment]
then you should wait for official public preivew of the feature :)

**Comment by greatemouse** [comment]
> then you should wait for official public preview of the feature :)

I know, but maybe someone has some estimate for it...

**Comment by nfx** [comment]
very soon =) if you can't wait - you can look at sources ;)

**Comment by alexott** [comment]
Look for databricks_git_credential resource - its now documented
