### ISSUE TITLE
[ISSUE] is_pinned 20 limit

### ISSUE THREAD

**Issue by jordancparker** [databrickslabs/terraform-provider-databricks#1184]
Hi Databricks, 

We have noticed that our databricks_cluster is deleting after 30 days, what we want to do is pin all our clusters, however i noticed that in your docs there is a limit of 20, however the offical docs say 70 as can be seen following the databricks documentation. 

Terraform Docs
[is_pinned](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster#is_pinned) - (Optional) boolean value specifying if cluster is pinned (not pinned by default). You must be a Databricks administrator to use this. The pinned clusters' maximum number is [limited to 20](https://docs.databricks.com/clusters/clusters-manage.html#pin-a-cluster), so apply may fail if you have more than that.

Databricks Docs
https://docs.databricks.com/clusters/clusters-manage.html

I would like to understand is this based on the internal Databricks limit on the dataplane, or is this hard coded in terraform, this is because we as a customer could request a higher limit, and subsquently an abotori limit in the terraform would restrict us. 

please clarify so that we can plan accordingly

Kind Regards

**Comment by alexott** [comment]
the docs should be fixed

**Comment by jordancparker** [comment]
Amazing thanks All, 

I guess i'm write to assume there is not hardcoded limit and just reference the documentation limits held by the Databricks API Plane.
