### ISSUE TITLE
[ISSUE] service_principal resource errors out after 0.5.3 upgrade

### ISSUE THREAD

**Issue by vadivelselvaraj** [databrickslabs/terraform-provider-databricks#1193]
After upgrading from databricks provider from **0.4.9** to **0.5.3**, I see the below error during the planning phase.

```
Error: application_id is not allowed for service principals in Databricks on AWS
with databricks_service_principal.deployment_user
on service_principals.tf line 1, in resource "databricks_service_principal" "deployment_user":
resource "databricks_service_principal" "deployment_user" {
```

Below is my config. And this doesn't include `application_id` as the error states.
```hcl
resource "databricks_service_principal" "deployment_user" {
  display_name         = "deployment-user"
  allow_cluster_create = true
}
```
This is an AWS Databricks deployment btw.

Any suggestion on how to fix this?

**Comment by vadivelselvaraj** [comment]
@nfx Likely linked to your changes in https://github.com/databrickslabs/terraform-provider-databricks/issues/1165

**Comment by nfx** [comment]
@vadivelselvaraj More like because of this https://github.com/databrickslabs/terraform-provider-databricks/commit/8c0a19e86bace08e8d28dfba6ecb50912aa17f8b

Need to remove validation completely and defer it to API

**Comment by nfx** [comment]
@vadivelselvaraj please build from master to get a fix before next release.
