### ISSUE TITLE
[ISSUE] No GCS storage handler for clusters api InitScriptStorageInfo and 

### ISSUE THREAD

**Issue by costaspiliotis** [databrickslabs/terraform-provider-databricks#1203]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Configuration
```hcl
  init_scripts {
    gs {
       destination="gs://databricks-shared/init_jars2.sh"
    }
  }
```

### Expected Behavior
GCS is an acceptable source for init scripts as per the databricks cluster ui on GCP: 
![image](https://user-images.githubusercontent.com/101852495/158931927-637b2d3b-4126-4f61-9908-e52d141aa680.png)

### Actual Behavior
 Error: Unsupported block type

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions

Terraform 1.1.7
Provider 0.5.2

### Debug Output
It's probably not needed given that there is no GCS storage option in the golang code.  
 
### Important Factoids

It still appears to be a missing format in the code at this point [here](https://github.com/databrickslabs/terraform-provider-databricks/blob/87709cd7c811d99eca15eefec03931d410918837/clusters/clusters_api.go#L201)  in InitScriptStorageInfo however databricks clusters does support GCS as an init script source, but it also appears undocumented:

https://docs.gcp.databricks.com/dev-tools/api/latest/clusters.html#clusterclusterinitscriptinfo

**Comment by alexott** [comment]
I'll look into it in the next days.

**Comment by nfx** [comment]
@alexott any updates?

**Comment by icherian** [comment]
@alexott  Do you have any updates to this issue?

**Comment by alexott** [comment]
not yet
