### ISSUE TITLE
[FEATURE] Add data source for SPNs and identify if current user is a SPN

### ISSUE THREAD

**Issue by rondefreitas** [databrickslabs/terraform-provider-databricks#1208]
Summary says it all...

I have a couple of uses cases where it's helpful to identify if the script is being run under the scope of a service principal (easily facilitated by checking if the current user has an application id), as well as being able to query for an existing service principal.

I've submitted a PR to this effect #1207 . It's my first time writing go, so please go easy on me :)

**Comment by nfx** [comment]
Following up - is this issue still relevant?
