### ISSUE TITLE
[Feature Request] Provide a flag to not start Cluster after deploying a cluster definition

### ISSUE THREAD

**Issue by eddylu1s** [databrickslabs/terraform-provider-databricks#1213]
Hi there,

I would like to request a feature that is currently not implemented yet at the time of writing (0.5.4). 
When you have multiple clusters defined in your code, Terraform will start the cluster after deploying (running terraform apply) the cluster definition within the Databricks workspace. However, in some cases you might have more cluster definitions than what the size of the subnet allows you to have simultaneously turned on. Consider a Databricks workspace with a /26 subnet (59 available IP's), if you have more then 29 clusters defined, it would try to start each cluster after defining the cluster on the terraform apply run. This would become problematic with the 30th cluster as it would have started each cluster with 2 NIC's and thus IP's occupied. In some (and our) use case, you expect never to have all the clusters running at the same time, but you do want them defined in your workspace (e.g. if you have one cluster per user). 

### Configuration
resource "databricks_cluster" "first_cluster" {
  cluster_name            = "first cluster"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 20
  autoscale {
    min_workers = 1
    max_workers = 50
  }
}

resource "databricks_cluster" "second_cluster" {
  cluster_name            = "second cluster"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 20
  autoscale {
    min_workers = 1
    max_workers = 50
  }
}

Etc... where n is the **nth** number (normally this would be done in a for_each of course)
resource "databricks_cluster" "n_cluster" {
  cluster_name            = "n cluster"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 20
  autoscale {
    min_workers = 1
    max_workers = 50
  }
}

### Expected Behavior
Add an argument like "start_cluster = false" (with default set to true), with the cluster **not** to be turned on (Running state) after running terraform apply.  Or if it needs to per se to validate the deployment by turning on the cluster, to add an argument like "stop_inmediately = true". Databricks does allow you to define more clusters (with NIC's) then the amount of available IP's if you do this from the UI portal. They just could not be started all at the same time.  

### Actual Behavior
Cluster will be always turned on after running terraform apply. 

### Steps to Reproduce
1. Have a Databricks instance with a /26 subnet and 58-59 available IP's for your clusters. 
2.  Define more clusters (29+ with 2 IP's each (one for worker, one for driver)) in your code.
3. `terraform apply`

### Terraform and provider versions
Terraform version: 1.1.4
Databricks provider: 0.5.4 (latest)
Please paste the output of `terraform version`. If version of `databricks` provider is not the latest (https://github.com/databrickslabs/terraform-provider-databricks/releases), please make sure to use the latest one.

**Comment by nfx** [comment]
@eddylu1s This feature might make the resource a bit more fragile than it is now. How can we guarantee that cluster is properly configured, if we don't start it and wait till running (or failing) status?

I'm not willing to prioritize this for core maintainer team, but would be happy to review and merge PR with this from community.

**Comment by eddylu1s** [comment]
@nfx first of all thank you for your quick reply. 
I understand that it in most cases you would want to validate if the cluster actually runs, therefore I suggested the optional flag.  Also perhaps another option would be to add an _stop_cluster_inmediately_after_ argument to stop the cluster right after successfully having it validated through the 'running' status.

**Comment by nfx** [comment]
@eddylu1s Probably it can work with optional "stopped" property, that would only affect Create part of the resource. Please make a pull request if you would like this feature in provider. You can find instructions in contributing.md

**Comment by nfx** [comment]
closing issue due to lack of interest from customer community
