### ISSUE TITLE
[DOC] databricks_sql_permissions Resource to be deprecated ?

### ISSUE THREAD

**Issue by ebarault** [databrickslabs/terraform-provider-databricks#1215]
Hi, 

### Affected Resource(s)
databricks_sql_permissions
https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/sql_permissions

### Expected Details
The doc states:
> Please switch to [databricks_grants](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/grants) with Unity Catalog to manage data access, which provides better and faster way for managing data security. databricks_grants resource doesn't require a technical cluster to perform operations. **databricks_sql_permissions will be removed, once Unity Catalog is Generally Available.**

I don't see why the need for this ressource would be totally nulled when Unity Catalog is GA.

Can we manage the privileges on the workspace-local hive_metastore with the databricks_grants Resource ? https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/grants ressource

**Comment by ebarault** [comment]
@nfx 
```
resource "databricks_grants" "this" {
  catalog = "hive_metastore"
  grant {
    principal  = "hive_metastore_users"
    privileges = ["USAGE", "CREATE", "SELECT", "MODIFY"]
  }
}
```
> Error: cannot create grants: Catalog 'hive_metastore' does not exist.
│ 
│   with databricks_grants.sandbox,
│   on main.tf line 42, in resource "databricks_grants" "this":
│   42: resource "databricks_grants" "this" {

**Comment by Triamus** [comment]
I don't see any indication in the docs that databricks_sql_permissions Resource is deprecated. Only a recommendation to use grants if one uses Unity. We explicitly have decided not to use Unity as it has too many limitations and things to be desired (probably will be added over the years). I hope there is no forced deprecation. It again would indicate that Databricks is trying to force customers into Unity as it does with features like SQL Python UDFs which require Unity but no-one in Databricks could explain to me why that is.
