### ISSUE TITLE
[ISSUE] Can't manage hive_metastore with databricks_grants

### ISSUE THREAD

**Issue by ebarault** [databrickslabs/terraform-provider-databricks#1217]
Hi,

### Configuration
```hcl
resource "databricks_grants" "this" {
  catalog = "hive_metastore"
  grant {
    principal  = "hive_metastore_users"
    privileges = ["USAGE", "CREATE", "SELECT", "MODIFY"]
  }
}
```

### Expected Behavior
As proposed in https://github.com/databrickslabs/terraform-provider-databricks/issues/1215#issuecomment-1076470896, I tried using **databricks_grants** to manage the permissions on a workspace's hive metastore.

### Actual Behavior

> │ Error: cannot create grants: Catalog 'hive_metastore' does not exist.
│ 
│   with databricks_grants.sandbox,
│   on main.tf line 42, in resource "databricks_grants" "sandbox":
│   42: resource "databricks_grants" "sandbox" {

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions

databricks provider 0.5.4

### Debug Output
(coming)
```
TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
```

**Comment by nfx** [comment]
just checked with relevant team - UC permissions and Table ACLs for hive metastore are two different things.

**Comment by ebarault** [comment]
yes @nfx i'm not surprised, as this resource works without a cluster. That leaves us with the continued need for sql_permission resource as stated in https://github.com/databrickslabs/terraform-provider-databricks/issues/1215#issuecomment-1076470896
