### ISSUE TITLE
[ISSUE] Database and Table access privileges are revoked when defined separately

### ISSUE THREAD

**Issue by vadivelselvaraj** [databrickslabs/terraform-provider-databricks#1236]
Currently when I create database, table grants using the below code the grants get deleted and re-created endlessly.

```hcl
resource "databricks_sql_permissions" "database_permissions" {
  database = "foo"

  privilege_assignments {
    principal  = "user1"
    privileges = local.database_read_privileges
  }
}

resource "databricks_sql_permissions" "database_permissions" {
  database = "foo"

  privilege_assignments {
    principal  = "user2"
    privileges = local.database_read_write_privileges
  }
}
```

Instead if it's written as below the re-creation doesn't happen.

```hcl
resource "databricks_sql_permissions" "database_permissions" {
  database = "foo"

  privilege_assignments {
    principal  = "user1"
    privileges = local.database_read_privileges
  }
  
  privilege_assignments {
    principal  = "user2"
    privileges = local.database_read_write_privileges
  }  
}
```

I believe this is happening because the resources are grouped by the id(database or table name) in the TF state file and hence the deletion happens for either user1 or user2 depending upon what was created in the previous TF apply.

I also wonder if there is a limit on the number of `privilege_assignments` that can exist within a `databricks_sql_permissions` TF resource. If there is one, support for the first approach is needed.

### Configuration
_Databricks terraform provider version:_ 0.4.9
_Terraform core version:_ 1.0.2

The same is true for Unity Catalog grants(catalog, external location, schema, storage_credentials, database, tables) post 0.5.x. I'd to downgrade to 0.4.9 to fix this behavior.

If this behavior is intended, can this be documented? Otherwise, please fix this. Thanks!

**Comment by nfx** [comment]
Works as intended. If all permissions for a table/db are not defined from a single resource, it's not possible to guarantee conf drift prevention

**Comment by vadivelselvaraj** [comment]
@nfx Is there is a limit on the number of `privilege_assignments` that can exist within a databricks_sql_permissions TF resource?

**Comment by nfx** [comment]
Not on terraform side. You can add couple of dozens of privilege assignments

**Comment by vadivelselvaraj** [comment]
@nfx The only comment that I've is to make this explicit on the docs. Thanks!
