### ISSUE TITLE
[ISSUE] databricks_global_init_script fails when source content change

### ISSUE THREAD

**Issue by EnriqueJoseSanjuaneloRobles-TomTom** [databrickslabs/terraform-provider-databricks#1237]
Hi there,

databricks_global_init_script resource fails when the content of the source change. The content of the init script is because we need to insert some secret keys (that we don't store in our git repositories). So, we have use a template (scalyr_init.tpl), and with that template we generate an output file (scalyr_init.sh).

The first time works properly, but... if we run terraform again. the provider fails

### Configuration
```hcl

locals {
  scalyr_init_script = templatefile("${path.module}/templates/scalyr_init.tpl",
    merge({
      a_key      = "my secret key"
    })
  )
}


resource "local_sensitive_file" "scalyr_init" {
  content  = local.scalyr_init_script
  filename = "${path.module}/out/scalyr_init.sh"
}

resource "databricks_global_init_script" "scalyr_init" {
  enabled    = true 
  name       = "Scalyr initialization"
  source     = "${path.module}/out/scalyr_init.sh"
  depends_on = [null_resource.scalyr_init]
}
```

### Expected Behavior

Init script updated properly

### Actual Behavior

An error:

 When expanding the plan for databricks_global_init_script.scalyr_init to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/databrickslabs/databricks" produced an invalid new
│ value for .md5: was cty.StringVal("different"), but now
│ cty.StringVal("772dc61d1432bea4d566ef335a741774").

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2.`terraform apply`
3. change something on the template
4. `terraform apply`

### Terraform and provider versions

- Installing hashicorp/local v2.2.2...
- Installed hashicorp/local v2.2.2 (signed by HashiCorp)
- Installing hashicorp/null v3.1.1...
- Installed hashicorp/null v3.1.1 (signed by HashiCorp)
- Installing hashicorp/azurerm v2.99.0...
- Installed hashicorp/azurerm v2.99.0 (signed by HashiCorp)
- Installing databrickslabs/databricks v0.5.4...
- Installed databrickslabs/databricks v0.5.4 (signed by a HashiCorp partner, key ID 905AA25F2E92C2D5)

**Comment by nfx** [comment]
Why do you create a file, if you can specify script content directly in content_base64 field?

**Comment by EnriqueJoseSanjuaneloRobles-TomTom** [comment]
Thanks @nfx. I was not aware of using content_base64 in the same way.

**Comment by nfx** [comment]
@EnriqueJoseSanjuaneloRobles-TomTom oh, so it's not documented?...
