### ISSUE TITLE
[ISSUE] Cannot create notebook using repository

### ISSUE THREAD

**Issue by Vertig00** [databrickslabs/terraform-provider-databricks#126]
Hi there,

### Terraform Version
Terraform v0.12.26

### Affected Resource(s)
- databricks_notebook

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "databricks_notebook" "dbc_notebook" {
  content = filebase64("${path.module}/notebooks/notebook1.dbc")
  path = "/workspace/terraform-test-folder/"
  overwrite = false
  mkdirs = true
  format = "DBC"
}
```

### Debug Output
https://gist.github.com/Vertig00/8a682161b372f53c726339e56284b0de.js

### Expected Behavior
Expect to create notebook resource on databricks

### Actual Behavior
return an error named: 
Error: status 400: err Response from server {"error_code":"INVALID_PARAMETER_VALUE","message":"Path (\\workspace\\terraform-test-folder) doesn't start with '/'"}

### Steps to Reproduce
`terraform apply`

**Comment by stikkireddy** [comment]
This is due to mkdirs not working appropriately on windows due to Path function

**Comment by nfx** [comment]
#111
