### ISSUE TITLE
[ISSUE] Unable to create users with non-admin permissions

### ISSUE THREAD

**Issue by aellwein** [databrickslabs/terraform-provider-databricks#1266]
Hello,

i'm unable to create ordinary, non-admin users (i.e. no cluster_create, no instance_pool_create permissions) with template as described below on Azure. The users get created with all permissions (and also land in the "admins" group).

### Configuration
```hcl
resource "databricks_user" "ordinary_user" {
  for_each                   = toset(var.dbx_users)     # this is a list with my user names, you can use your own
  user_name               = each.value
  active                        = true
  allow_cluster_create       = false
  allow_instance_pool_create = false
  workspace_access           = true
  databricks_sql_access      = false
  force                      = true
  lifecycle {
    ignore_changes = [external_id]
  }
}
```

### Expected Behavior

Users without cluster creation/instance pool creation permissions are created.

### Actual Behavior

Admin users are created.

### Steps to Reproduce

just `terraform apply`

### Terraform and provider versions

Terraform v1.0.11
Databricks provider  v0.5.5

### Debug Output

No crashes or errors here, apply works.

### Important Factoids

> Are there anything atypical about your accounts that we should know?

Nothing untypical.

**Comment by nfx** [comment]
Are you using premium sku?

**Comment by nfx** [comment]
this functionality is not available in Standard SKU.
