### ISSUE TITLE
[ISSUE] Import user

### ISSUE THREAD

**Issue by nsampietrowam** [databrickslabs/terraform-provider-databricks#1269]
Hi there,

### Configuration
```hcl
resource "databricks_user" "JYay" {
  user_name    = "JYay@domain.com"
  display_name = "John, Jay"
}
```

### Expected Behavior
The user already exist, so I'm trying to import it with the command:  terraform import databricks_user.JYay JYay@domain.com

### Actual Behavior
 Error: cannot read user: Endpoint not supported.

### Steps to Reproduce

1. `TF_LOG=DEBUG terraform import databricks_user.JYay JYay@domain.com

### Terraform and provider versions

Terraform v1.1.2
on linux_amd64
provider registry.terraform.io/databrickslabs/databricks v0.5.2

**Comment by nfx** [comment]
Use ID of user, not username
