### ISSUE TITLE
[ISSUE] databricks_tables resource provides both Unity Catalog tables and views

### ISSUE THREAD

**Issue by vadivelselvaraj** [databrickslabs/terraform-provider-databricks#1274]
`data.databricks_tables` provides with both the Unity Catalog tables and views. This is problematic especially when trying to assign write permissions to Unity Catalog tables for a principal.

For example, if the `foo` database(aka UC schema) has both tables & views and then we assign `[SELECT, MODIFY]` privileges to a principal terraform errors out with the message `Error: cannot create grants: Privilege MODIFY is not applicable to Views.`.

```hcl
data databricks_tables "things" {
  catalog = "main"
  schema = "foo"
}

locals {
  table_grants = [
    for table_name in sort(data.databricks_tables.low_fidelity_data_db_tables.ids) : {
      table_name : table_name,
      principal : databricks_group.foo_db_read_write.display_name,
      privileges : ["SELECT", "MODIFY"]
    }
  ]
}

resource "databricks_grants" "table_grants" {
  count = length(local.table_grants)
  table = local.table_grants[count.index]["table_name"]

  grant {
    principal  = local.table_grants[count.index]["principal"]
    privileges = local.table_grants[count.index]["privileges"]
  }
}
```
To resolve this, one of the below workarounds would help.
- Provide a way to identify views within `data.databricks_tables`.
- Exclude views within `data.databricks_tables` and create a new `data.databricks_views` terraform resource.

**Comment by nfx** [comment]
@adamcain-db is it possible on API level to distinguish between tables and views, when we list tables?

**Comment by adamcain-db** [comment]
> @adamcain-db is it possible on API level to distinguish between tables and views, when we list tables?

Yes. The `table_type` field (in the `TableInfo` object) will equal "VIEW" for views and either "MANAGED" or "EXTERNAL" for tables ([ref](https://docs.google.com/document/d/1XneoG4YWNBEIUFtk-lgeHzyES2ACLsQ_Kb5E-LPjlhc/edit?pli=1#bookmark=id.24sl48us3zy6)).
