### ISSUE TITLE
[ISSUE] PAT and OBO tokens reset on deploy

### ISSUE THREAD

**Issue by mindejulian** [databrickslabs/terraform-provider-databricks#1290]
Hi there,

We have four workspaces managed in one terraform project. Sometimes when we deploy changes, not related to tokens, users tokens and service principals obo tokens are invalidated. I have looked at https://github.com/databrickslabs/terraform-provider-databricks/issues/1223 but the issue remains.

### Configuration
```hcl
resource "databricks_permissions" "token_usage_other_workspaces" {
  count = contains(["process", "ingest"], var.env) ? 0 : 1

  authorization = "tokens"

  access_control {
    group_name       = "users"
    permission_level = "CAN_USE"
  }
}
```

### Expected Behavior
Since there are no changes, a new deploy should not make any changes to the workspace

### Actual Behavior
No changes are made, except that PAT and OBO tokens are sometimes (1 of 5 times maybe) invalid after a deploy.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions

Terraform v1.1.9
on darwin_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.5.4
+ provider registry.terraform.io/hashicorp/aws v4.10.0
+ provider registry.terraform.io/hashicorp/random v3.1.2

### Important Factoids
Are there anything atypical about your accounts that we should know?

**Comment by nfx** [comment]
i think it's related to `count` meta-argument. not the issue of provider itself.

**Comment by mindejulian** [comment]
Why would that cause tokens to get invalidated, is count not supported?
This resource is only to be deployed to workspaces not named process or ingest (they have token permissions for service principals as well.)
