### ISSUE TITLE
[ISSUE] Provider issue - databricks_azure_adls_gen2_mount/databricks_mount failed!

### ISSUE THREAD

**Issue by Mohammad-AlRousan** [databrickslabs/terraform-provider-databricks#1302]
Hi there,

when mounting container I am getting this issue:

### Configuration
resource "databricks_azure_adls_gen2_mount" "container_mount" {
    count                  = length(var.containers)
    container_name         = var.containers[count.index]
    storage_account_name   = var.storage_name
    mount_name             = var.containers[count.index]
    tenant_id              = var.tenant_id
    client_id              = var.client_id
    client_secret_scope    = var.secretscope_name
    client_secret_key      = "spn_key"
    initialize_file_system = true
}
**or even if I with this:**
 resource "databricks_mount" "container_mount" {
   count                  = length(var.containers)

   name                   = var.containers[count.index]
   uri = "abfss://${var.containers[count.index]}@${var.storage_name}.dfs.core.windows.net"
   extra_configs = {
     "fs.azure.account.auth.type" : "OAuth",
     "fs.azure.account.oauth.provider.type" : "org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider",
     "fs.azure.account.oauth2.client.id" : var.client_id,
     "fs.azure.account.oauth2.client.secret" : "{{secrets/${var.secretscope_name}/${var.secret_key}}}", 
     "fs.azure.account.oauth2.client.endpoint" : "https://login.microsoftonline.com/${var.tenant_id}/oauth2/token",
     "fs.azure.createRemoteFileSystemDuringInitialization" : "false",
   }
 }
### Expected Behavior
the container should be mounted

### Actual Behavior
Secret does not exist with scope: secret_scope01 and key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
│
│   with module.Mount_Containers.databricks_azure_adls_gen2_mount.container_mount[0],
│   on modules/adb_mount/main.tf line 17, in resource "databricks_azure_adls_gen2_mount" "container_mount":
│   17: resource "databricks_azure_adls_gen2_mount" "container_mount" {

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions
Terraform version: Terraform v1.2.0-rc1 on linux_amd64
Databrticks provider version: **0.5.7**

Note: if i replace client.secrets block  " "fs.azure.account.oauth2.client.secret" : xxxxxxxxxxxxxxxxxxxxxxx"  with the SPN key/secret it will run without any issue

**Comment by nfx** [comment]
You have to make sure that mount depends on secret resource 🤷🏻‍♂️

It's not an issue in provider.
