### ISSUE TITLE
[FEATURE] Install multiple libraries from one provider in one statement

### ISSUE THREAD

**Issue by dvasdekis** [databrickslabs/terraform-provider-databricks#1316]
We would like to install multiple packages from each provider in one library statement. Our R-CRAN package list is 20+ packages long and growing, for example, and we can't create library resources for every package.

### This works fine:
```hcl
resource "databricks_library" "cluster-python" {
  cluster_id = databricks_cluster.dbcluster-c.id
  pypi {
    package = "databricks-cli"
  }
}
```
### but I'd like this to be supported:
```hcl
resource "databricks_library" "cluster-python" {
  cluster_id = databricks_cluster.dbcluster-c.id
  pypi {
    package = "databricks-cli, pyodbc"
  }
}
```

### Expected Behavior
I want both "databricks-cli" and "pyodbc" to be installed

### Actual Behavior
Gets confused and tries to install a library called "databricks-cli, pyodbc"
│ Error: cannot create library: pypi:databricks-cli, pyodbc failed: Library installation attempted on the driver node of cluster 0510-015243-ydrmiivq and failed. Please refer to the following error message to fix the library or contact Databricks support. Error Code: DRIVER_LIBRARY_INSTALLATION_FAILURE. Error Message: org.apache.spark.SparkException: Process List(/databricks/python/bin/pip, install, databricks-cli, pyodbc, --disable-pip-version-check) exited with code 1. ERROR: Invalid requirement: 'databricks-cli, pyodbc'

### Steps to Reproduce
1. `terraform apply`

### Terraform and provider versions
```
Terraform v1.1.9
on linux_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.5.7
+ provider registry.terraform.io/hashicorp/azuread v2.22.0
+ provider registry.terraform.io/hashicorp/azurerm v2.99.0
+ provider registry.terraform.io/hashicorp/random v3.1.3
```

Thank you!

**Comment by alexott** [comment]
when you use `for_each` with dynamic block you, instead of the `each.value` you need to use the name of dynamic block, like, `library.value`. Here is the working example (I only use list of maps, instead of lists of strings):

```hcl
  dynamic "library" {
    for_each = var.library_pypi
    content {
      pypi {
        package = library.value["package"]
        repo = lookup(library.value, "repo", null)
      }
    }
  }
```
and variables:
```hcl
library_pypi = [
  {"package":"mlflow==1.11.0"},
  {"package":"fbprophet==0.7.1"}
]
```

**Comment by dvasdekis** [comment]
Thanks @alexott . The setup that worked for me to define a serverless cluster with libraries was below:
```terraform
variable "databricks_pypi_libraries" { 
  type = list
  default = ["databricks-cli", "pyodbc", "geopandas"]
}

variable "databricks_cran_libraries" { 
  type = list
  default =  ["sparklyr", "dplyr", "ggplot2", "forecast", "gridExtra", "tidymodels", "corrplot"]
}

resource "databricks_cluster" "dbcluster-c" {
  depends_on = [azurerm_databricks_workspace.databricks-c]
  cluster_name           = "cluster"
  spark_version           = data.databricks_spark_version.latest.id
  autotermination_minutes = 10
  dynamic "library" {
    for_each = var.databricks_pypi_libraries
      content {
        pypi {
          package = library.value
        }
      }
  }
  dynamic "library" {
    for_each = var.databricks_cran_libraries
      content {
        cran {
          package = library.value
        }
      }
  }
  autoscale {
    min_workers = 2
    max_workers = 8
  }
  spark_conf = {
    "spark.databricks.cluster.profile": "serverless",
    "spark.databricks.repl.allowedLanguages": "python,sql,r",
    "spark.databricks.passthrough.enabled": true,
    "spark.databricks.pyspark.enableProcessIsolation": true,
    "spark.databricks.delta.optimizeWrite.enabled": true,
    "spark.databricks.delta.autoCompact.enabled": true
    }
  custom_tags = {
    "ResourceClass" : "Serverless"
  }
}
```
