### ISSUE TITLE
[ISSUE] Removing service principal entitlement leads to Error: cannot update service

### ISSUE THREAD

**Issue by fvdnabee** [databrickslabs/terraform-provider-databricks#1319]
The entitlement `allow-instance-pool-create` was added to the service principal outside of terraform. When applying my terraform configuration (without this entitlement), the provider detects the drift: 
```bash
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # databricks_service_principal.sp has changed
  ~ resource "databricks_service_principal" "sp" {
      ~ allow_instance_pool_create = false -> true
        id                         = "2323502488275632"
        # (6 unchanged attributes hidden)
    }

```
and proposes to remove the entitlement:
```bash
  # databricks_service_principal.sp will be updated in-place
  ~ resource "databricks_service_principal" "sp" {
      ~ allow_instance_pool_create = true -> false
        id                         = "2323502488275632"
        # (6 unchanged attributes hidden)
    }
```
When trying to update the service principal, the provider throws the following error:
```bash
databricks_service_principal.sp: Modifying... [id=2323502488275632]

╷
│ Error: cannot update service principal: Required attribute applicationID is missing in the SCIM Object. Request is unparsable, syntactically incorrect, or violates schema.
│ 
│   with databricks_service_principal.sp,
│   on main.tf line 74, in resource "databricks_service_principal" "sp":
│   74: resource "databricks_service_principal" "sp" {
│ 
```

This is the state of the service principal before the apply:
```bash
❯ curl --netrc -X GET https://REDACTED.azuredatabricks.net/api/2.0/preview/scim/v2/ServicePrincipals/2323502488275632
{"displayName":"Azure SPN","groups":[],"id":"2323502488275632","entitlements":[{"value":"allow-cluster-create"},{"value":"allow-instance-pool-create"}],"applicationId":"5d13fa1a-REDACTED","schemas":["urn:ietf:params:scim:schemas:core:2.0:ServicePrincipal"],"active":true}
```

### Configuration
```hcl
resource "azuread_application" "databricks" {
  display_name     = "test"
  owners           = [data.azuread_client_config.current.object_id]
}

resource "databricks_service_principal" "sp" {
  application_id = azuread_application.databricks.application_id
  display_name   = "Azure SPN"  # not required for Azure, but provide anyway
  # the allow-cluster-create entitlement is necessary when access control is
  # enabled for clusters, otherwise the service principal cannot create a job
  # cluster when it runs a job. See
  # https://docs.microsoft.com/en-us/azure/databricks/tutorials/run-jobs-with-service-principals#--add-the-service-principal-to-the-azure-databricks-workspace
  allow_cluster_create       = true
}

```

### Expected Behavior
The provider should be able to remove the entitlement from the SPN.

### Actual Behavior
The provider throws an error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. update the service principal outside of terraform to add the allow-instance-pool-create entitlement, e.g. via curl [1]
4. `terraform apply` again and observe the error

[1]
```bash
curl --netrc -X PUT \
https://<databricks-instance>/api/2.0/preview/scim/v2/ServicePrincipals/<service-principal-id> \
--header 'Content-type: application/scim+json' \
--data @update-service-principal.json \
| jq .
```
update-service-principal.json:
```json
{
  "schemas": [ "urn:ietf:params:scim:schemas:core:2.0:ServicePrincipal" ],
  "applicationId": "<appliation-id>",
  "displayName": "<display-name>",
  "groups": [
    {
      "value": "<group-id>"
    }
  ],
  "entitlements": [
    {
      "value":"allow-instance-pool-create"
    }
  ]
}

```
### Terraform and provider versions

```
❯ terraform version
Terraform v1.1.8
on linux_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.5.7
+ provider registry.terraform.io/hashicorp/azuread v2.22.0
+ provider registry.terraform.io/hashicorp/azurerm v3.6.0
```

### Debug Output
n/a

### Important Factoids
Premium SKU on azure.

**Comment by nfx** [comment]
@fvdnabee did you use `force` parameter? https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/service_principal#force

**Comment by nfx** [comment]
i see - https://github.com/databrickslabs/terraform-provider-databricks/blob/master/scim/resource_service_principal.go#L128-L133

we don't set app id for auzre in updates. the complicated bit is that AWS prevents us from setting app id for spns, which requires to test this a bit more carefully

**Comment by fvdnabee** [comment]
FYI: as a work-around I removed the entitlement myself by updating the SPN via a PUT request to the `api/2.0/preview/scim/v2/ServicePrincipals/<service-principal-id>` API endpoint. Though destroying and re-adding the service principal from terraform would indeed have been easier.

**Comment by nfx** [comment]
now i see when our Databricks CLI could have been helpful if it supported all CRUD apis :)

**Comment by fvdnabee** [comment]
Certainly, another helpful feature of the databricks cli would be support for authenticating as a service principal. From my understanding service principals can't create databricks tokens, which is the only auth method supported by the databricks cli (please correct me if I am wrong)? The use-case is adding a a git credential for a service principal (so it can run jobs from a private git repo), which requires calling the databricks git credentials API as the service principal (again, according to my understanding). For now I wrote a script that retrieves an AD token (for an Azure backed SP) and calls the git credentials API with that token.

**Comment by nfx** [comment]
> another helpful feature of the databricks cli would be support for authenticating as a service principal

_somewhere later_ cli should support all authentication methods that are supported by this terraform plugin.

> The use-case is adding a a git credential for a service principal
why not https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/git_credential ?...

> requires calling the databricks git credentials API as the service principal
yes...

**Comment by fvdnabee** [comment]
> > The use-case is adding a a git credential for a service principal
> 
> why not https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/git_credential ?...

The service principal managed in my TF config (`databricks_service_principal`) differs from the principal by which the tf provider authenticates to azure (it is a principal with infra CRUD permissions). So the `databricks_git_credential` resource cannot be used, as the resource only allows managing git credentials for the principal of the tf provider. Right? Or am I missing something here?
