### ISSUE TITLE
[ISSUE] Can't destroy DBFS file over 4MB

### ISSUE THREAD

**Issue by algattik** [databrickslabs/terraform-provider-databricks#136]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
0.12.24

### Affected Resource(s)
- databricks_dbfs_file

### Terraform Configuration Files
```hcl
resource "databricks_dbfs_file" "dbfs-ingestion" {
  content = filebase64("${var.spark_job_jars}/spark-ingestion-job.jar")
  path = "${local.databricks_dbfs_jar_folder}/sparkjars/spark-ingestion-job.jar"
}
```

### Debug Output
terraform destroy -input=false -auto-approve

rpc error: code = ResourceExhausted desc = grpc: received message larger than max (19383873 vs. 4194304)

**Comment by stikkireddy** [comment]
Sorry this should be documented, its a limitation of terraform that you are not able to send more than 4mb on a field (or resource not sure here) via grpc protocol. Unfortunately, this resource may need to be redesigned to include path, local_path and md5_checksum

**Comment by nfx** [comment]
@stikkireddy we should fail the resource at plan stage and make descriptive message :)

**Comment by stikkireddy** [comment]
ya the quickest patch at the moment would be to add a validate func to verify that it is 4mb or less on the content field

**Comment by nfx** [comment]
This issue per se won't be fixed due to limitations of Terraform. JARs, per se, should be put on dbfs by databricks CLI as part of CICD process. There'll be a separate PR on fixing validation for most of resources.

**Comment by algattik** [comment]
> This issue per se won't be fixed due to limitations of Terraform. JARs, per se, should be put on dbfs by databricks CLI as part of CICD process. There'll be a separate PR on fixing validation for most of resources.

This is hard to understand. The terraform provider for blob storage can upload blobs of arbitrary size.  The whole point of using terraform is to automate the CICD process and resource provisioning in a more reliable manner than having to use a CLI. 

At the very least this should become a documentation issue, that a prominent warning about this limitation should be posted on the resource documentation page.

**Comment by sdebruyn** [comment]
+1 on that. Other terraform providers can upload resources > 4 MB. Maybe because they use a path as reference instead of base64 encoding the JAR?

@algattik A simple workaround for this:
Upload the resources to ADLS or blob storage and then mount your container/filesystem with this provider.

**Comment by al-lac** [comment]
@sdebruyn My thoughts exactly. 

I wanted to setup spark-monitoring by transferring the needed JAR files, a few of them work until the .tfstate file gets to big and it fails.

Please reopen this ticket and change the transfer method to not use base64 encoding.
