### ISSUE TITLE
[DOC] No example for a cluster-scoped init script stored in Azure

### ISSUE THREAD

**Issue by dvasdekis** [databrickslabs/terraform-provider-databricks#1372]
Hi team, thanks in advance for the help.

There's currently no way to define a cluster-scoped init script in Databricks when using Azure storage. Could you please provide an example? AWS and GCP already have examples. 

### Affected Resource(s)
[datbricks_cluster - init_scripts](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster#init_scripts)

### Expected Details
Looking for a way to define a cluster-scoped init_script that exists in Azure Data Lake (e.g. ABFSS) or blob storage. There's currently no example on how to do so.

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] Add example of storing a cluster-scoped init script in Azure Blob Storage
- [ ] Add example of storing a cluster-scoped init script in Azure Data Lake Gen2

**Comment by nfx** [comment]
This feature is not directly supported on the platform side. Azure Databricks can send logs or read init scripts only from DBFS. You can attach adls/blob with SPN client/secret via databricks_mount. Though you should be using databricks_global_init_script instead to avoid mounting
