### ISSUE TITLE
[ISSUE] databricks_instance_pool with preloaded_spark_versions crashes

### ISSUE THREAD

**Issue by jdillon** [databrickslabs/terraform-provider-databricks#144]
Looks like there is a bug in converting the `preloaded_spark_versions` configuration which when present will cause terraform to crash.

Workaround is degraded configuration to not set `preloaded_spark_versions` when creating a `databricks_instance_pool`.

### Terraform Version

Terraform v0.12.28
+ provider.databricks v0.2.2

### Affected Resource(s)

- databricks_instance_pool

### Terraform Configuration Files
```hcl
resource "databricks_instance_pool" "elysium_curator" {
  instance_pool_name = "elysium-curator"
  node_type_id = "i3.xlarge"
  max_capacity = 20
  min_idle_instances = 1
  aws_attributes {
    availability = "SPOT"
    spot_bid_price_percent = 100
  }
  idle_instance_autotermination_minutes = 30
  enable_elastic_disk = false
  preloaded_spark_versions = [
    "6.6.x-scala2.11"
  ]
  custom_tags = {
    "use-case" = "elysium"
    "expiration" = "never"
  }
}
```

### Panic Output

https://gist.github.com/jdillon/e0e1df4280d943f0cf7b54fc7398927b

### Expected Behavior

Instance-pool should have been created with the preloaded_spark_versions specified.

### Actual Behavior

Crash

### Steps to Reproduce

1. `terraform apply`

**Comment by sdebruyn** [comment]
I submitted PR #153 to fix this issue.
If you want, you can find patched versions here for now:

- v0.2.0 with the fix: https://github.com/datarootsio/databrickslabs-terraform-provider-databricks/tree/v0.2.0-instance_pool-fix
- v.0.2.2 with the fix: https://github.com/datarootsio/databrickslabs-terraform-provider-databricks/tree/instance_pool-sparkVersions

I am still on v0.2.0 as any form of authentication other than databricks CLI is broken in v.0.2.2.
