### ISSUE TITLE
Typo on JobSettings struct tag json attribute

### ISSUE THREAD

**Issue by psg2** [databrickslabs/terraform-provider-databricks#150]
https://github.com/databrickslabs/terraform-provider-databricks/blob/9e3acafb6cbc42489ec6d0a3fa7751b4b6ef52d5/client/model/job.go#L54

The attribute `MinRetryIntervalMillis` is incorrectly mapped to `max_retry_interval_millis` on json.

**Comment by nfx** [comment]
Will be resolved in scope of bigger refactoring in #147. Otherwise pull requests are welcome :)
