### ISSUE TITLE
[ISSUE] Add global rate limit to API calls

### ISSUE THREAD

**Issue by nfx** [databrickslabs/terraform-provider-databricks#156]
There needs to be a rate limit configuration present to limit number of requests to reasonable number per minute to ensure smooth operations. The most complicated part is testing.

**Comment by ketan** [comment]
According to the [databricks API documentation](https://docs.databricks.com/dev-tools/api/latest/index.html), the rate limit can be increased by asking a rep.

If there's a possibility of implementing this (for the most common cases), can I request that this be made configurable somehow?

Thanks.

**Comment by nfx** [comment]
@ketan if you want to have it done quicker, pull requests are always welcome. currently, absence of rate limiting may result in blocking your IP for 5-10 minutes on workspaces with thousands of managed Databricks resources. Though, improved HTTP retries would kick in and terraform execution won't see any disturbance. Though, it's generally better to be more gentle to APIs and not lock yourself out by running less concurrent requests :)
