### ISSUE TITLE
[ISSUE] Using incorrect env variable in provider to get ARM_SUSBCRIPTION_ID

### ISSUE THREAD

**Issue by jjcollinge** [databrickslabs/terraform-provider-databricks#164]
The provider is checking for the existence of `ARM_SUBSCRIPTION_ID` but then reading `DATABRICKS_AZURE_SUBSCRIPTION_ID` which leads to an empty subscription ID in the token payload.

https://github.com/databrickslabs/terraform-provider-databricks/blob/d16d18baf933336e1fea4e669267b0d97780414b/databricks/provider.go#L231

cc: @masoncusack

**Comment by nfx** [comment]
will double check in #158 , thanks for reporting

**Comment by sdebruyn** [comment]
can confirm this was fixed with #158
