### ISSUE TITLE
How To Assign Cluster Permissions

### ISSUE THREAD

**Issue by mclite** [databrickslabs/terraform-provider-databricks#168]
How do I assign cluster permissions like the ones in the attached image?

![image](https://user-images.githubusercontent.com/16764021/87086163-28969580-c1ff-11ea-9376-eb4c40b455e4.png)

**Comment by mclite** [comment]
Any updates?

**Comment by stikkireddy** [comment]
please track issue #176

**Comment by stikkireddy** [comment]
closing due to duplicate for #176

**Comment by mclite** [comment]
It worked thanks. This provider is awesome. I've setup 6 clusters using this
