### ISSUE TITLE
[ISSUE] databricks_notebook format "DBC" does not work as documented

### ISSUE THREAD

**Issue by jdillon** [databrickslabs/terraform-provider-databricks#179]
Documentation suggests that format can be "SOURCE" or "DBC:

```
(Required) This specifies the format of the file to be imported. By default, this is SOURCE. However it may be one of: SOURCE, or DBC. The value is case sensitive. SOURCE is suitable for .scala, .py, .r, .sql extension based files, HTML for .html files, JUPYTER for .ipynb files, and DBC for .dbc files. Though the API supports HTML and JUPYTER currently we do not support them as identifying DIFF is quite challenging.
```

Looks like impl however only allows "SOURCE": https://github.com/databrickslabs/terraform-provider-databricks/blob/master/databricks/resource_databricks_notebook.go#L77 ?

### Terraform Version

Terraform v0.12.28
+ provider.databricks v0.2.3

### Affected Resource(s)

- databricks_notebook

### Terraform Configuration Files
```hcl
resource "databricks_notebook" "qux" {
  path = "/foo/bar/baz/qux"
  mkdirs = true
  format = "DBC"
  content = filebase64("${path.module}/qux.dbc")
}
```

### Debug Output
```
Error: expected format to be one of [SOURCE], got DBC

  on main.tf line 119, in resource "databricks_notebook" "qux":
 119: resource "databricks_notebook" "qux" {
```

### Expected Behavior
Able to provision notebooks from DBC archives.

**Comment by stikkireddy** [comment]
Hey @jdillon at this point in time, we will not be supporting DBC files and only source format. Identifying difference between DBC files is not feasible. DBC files will pull down timestamp information and other outputs from the notebooks so when identifying to see if content has changed it will always say that the notebook has been updated. Please use SOURCE files. At this point in time I will fix the docs but we will not be adding in capability to support DBC at this point in time.

**Comment by jdillon** [comment]
understood
