### ISSUE TITLE
[FEATURE] Notebooks Support for detecting changes (Currently only supports SOURCE)

### ISSUE THREAD

**Issue by stikkireddy** [databrickslabs/terraform-provider-databricks#183]
**Is your feature request related to a problem? Please describe.**
Notebooks should get a similar enhancement to the way, that dbfs_file works. This will prevent statefile from being flooded with content. We should also switch from CRC checksum to MD5 as that is the function available in terraform.

**Describe the solution you'd like**
The tricky part here is identifying differences and how does the user provide a checksum that will determine if the notebook has changed. This will involve the creation of a datasource called:

```hcl
resource databricks_notebook "notebook" {
  source = "my_local_file_path" // optionally this should also support content field for small content items or things using templates in terraform.
  format = "SOURCE"
}
```

Proposed changes:

The goal of these changes is to avoid detecting "changes" everytime we apply so we need to know when the file has changed locally and remotely.

1. make sure that both `source` and `content` options exist. source is the filepath ondisk and the content is the raw content, and maybe `content_b64`. This is very similar to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object. 

2. Ability to detect changes should be simple and hidden from the user. Unfortunately for notebooks based on the notebook is uploaded the easiest way to detect changes is with the source format as we can normalize the file by removing the magic components of a source export, etc. Unfortunately we need a field to be able to track this. 

Other cloud providers such as aws does this with the [etag](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object#etag) but it is clunky, user needs to know they need to use this and only works part of the time. 

I believe gcp solves detecting changes much more elegantly and hidden from the user. Their doc for cloud_storage_object is https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/storage_bucket_object very simple they also support `source`, `content` but they dont have an ability from looking at their docs that they can detect diff. But if you look int the code: 
https://github.com/hashicorp/terraform-provider-google/blob/02b54787626964cd329d7e7baf7570f9d14b7b54/google/resource_storage_bucket_object.go#L107-L144

They have an undocumented field called `detect_md5hash` which is used to detect changes and the diff is suppressed. It also doesn't need to be documented because the goal is the user should not be populating this field. This IMO is a really simple solution for SOURCE that will not introduce any complexity and it removes this bizarre state func that we have: https://github.com/databrickslabs/terraform-provider-databricks/blob/c2dc11fad67184c751361ae854a9cc48aaf0183c/workspace/resource_notebook.go#L207-L212

**Comment by nfx** [comment]
why not just re-uploading notebooks every time?..

**Comment by nfx** [comment]
@stikkireddy is this still relevant? we should also re-visit with larger group on how to supply content to notebooks. asking users to supply MD5 calculation looks like an overkill for entry-level audience.

**Comment by nfx** [comment]
@stikkireddy i'd suggest to keep only `source` and deprecate `content`

**Comment by nfx** [comment]
will cover in scope of harmonising behavior between DBFS & Notebook resources - #417

**Comment by nfx** [comment]
Fix is in https://github.com/databrickslabs/terraform-provider-databricks/pull/417/commits/9066bee70a2f2810f272ee36775409a74c2c446e

**Comment by nfx** [comment]
this change also ignores any changes on the workspace side and only relies on synthetic `md5` field. This means that notebook/file will be updated only when terraform state changes and any changes on workspace won't get reflected on the state. Same behaviour holds true for secrets & tokens. 

So 0.3.0 will have some significant changes, together with simplified maintainability.
