### ISSUE TITLE
[ISSUE] Customize the transport properties of the HTTP request. 

### ISSUE THREAD

**Issue by stikkireddy** [databrickslabs/terraform-provider-databricks#200]
These are the defaults setup by the http.DefaultTransport.(*http.Transport).

If we determine that these values should be higher we should add them to our http.Transport block using the time.* notation. 

```go
	IdleConnTimeout:       90 * time.Second,
	TLSHandshakeTimeout:   10 * time.Second
```

Might also be a good idea to propagate these up as options/env variables set by the provider.

**Comment by nfx** [comment]
I think they might be configuration properties on provider level. though it's reproduced for extremely large terraform states only... 

/cc @johnkeates was able to catch it today.

**Comment by nfx** [comment]
doesn't seem to be any interest from users, closing it to focus on more important issues
