### ISSUE TITLE
[FEATURE] Associate cluster policies to clusters

### ISSUE THREAD

**Issue by stikkireddy** [databrickslabs/terraform-provider-databricks#205]
When using the cluster resource, I would like to define the policy id associated with that cluster resource and let the policy define the cluster object. 

A very trivial approach can be to place the policy id in the databricks_cluster resource and let the user figure out which parameters are required and not required.

**Comment by nfx** [comment]
I'll see if i can add it in final stages of #158 cleanup

**Comment by stikkireddy** [comment]
done as part of #158
