### ISSUE TITLE
[ISSUE] No longer possible to create ADLS2 mount

### ISSUE THREAD

**Issue by sdebruyn** [databrickslabs/terraform-provider-databricks#213]
### Terraform Version
Latest version from master
Terraform 0.12.29

Used to work in previous version

### Affected Resource(s)
- databricks_azure_adls_gen2_mount

### Terraform Configuration Files
```hcl
resource "databricks_azure_adls_gen2_mount" "fs" {
  for_each               = toset(data.terraform_remote_state.platform.outputs.filesystems)
  cluster_id             = databricks_cluster.cluster.id
  container_name         = each.key
  storage_account_name   = data.terraform_remote_state.platform.outputs.fs_storage_account_name
  mount_name             = each.key
  tenant_id              = data.azurerm_client_config.current.tenant_id
  client_id              = var.application_id
  client_secret_scope    = databricks_secret.client_secret.scope
  client_secret_key      = databricks_secret.client_secret.key
  initialize_file_system = true
}
```

### Debug Output
Available upon request by email, contains a lot of keys and IDs...

### Expected Behavior
Mounts should be created like before.

### Actual Behavior
1 error per mount, always the same:
```
Error: https://login.microsoftonline.com//oauth2/token

  on mounts.tf line 1, in resource "databricks_azure_adls_gen2_mount" "fs":
   1: resource "databricks_azure_adls_gen2_mount" "fs" {
```

### Steps to Reproduce
1. `terraform apply`

**Comment by sdebruyn** [comment]
Apparently it's because the values at https://github.com/databrickslabs/terraform-provider-databricks/blob/master/databricks/resource_databricks_azure_adls_gen2_mount.go#L29 are not filled in

<img width="259" alt="Screenshot 2020-08-06 at 10 14 05" src="https://user-images.githubusercontent.com/963413/89508103-bac59580-d7cd-11ea-8001-f9246d259f8f.png">

**Comment by sdebruyn** [comment]
The variable called `tpl` which is passed along is always empty. The issue seems to be occurring for all types of mounts.

**Comment by stikkireddy** [comment]
that empty value is passed along for using reflection; let me take a look into this: https://github.com/databrickslabs/terraform-provider-databricks/blob/7d23e61d78f45d2492035e95ce4af11e47a323bc/databricks/mounts.go#L122-L150

**Comment by sdebruyn** [comment]
The parsing of the fields here doesn't seem to go well for mounts: https://github.com/databrickslabs/terraform-provider-databricks/blob/master/databricks/util/reflect_resource.go#L195
All the field names are empty strings.

**Comment by sdebruyn** [comment]
Digging deeper and deeper and I start to understand how it's structured now. Quite elegant actually, less code duplication.
So it seems like the json tags are missing here: https://github.com/databrickslabs/terraform-provider-databricks/blob/master/databricks/resource_databricks_azure_adls_gen2_mount.go#L10

**Comment by sdebruyn** [comment]
So it's only ADLS2 after all

**Comment by sdebruyn** [comment]
alright, was an easy fix after all :)

**Comment by nfx** [comment]
thanks @sdebruyn !

**Comment by nfx** [comment]
> The variable called `tpl` which is passed along is always empty

@sdebruyn  if you're aware of better way of Go's Class<T> equivalent - make a PR :)

**Comment by sdebruyn** [comment]
> > The variable called `tpl` which is passed along is always empty
> 
> @sdebruyn if you're aware of better way of Go's `Class<T>` equivalent - make a PR :)

No not at all, I learned Go specifically to work with Terraform providers and mostly for this one. So I'm pretty new to it and I think your solution is quite elegant. A lot of providers have boilerplate code and this seems a good way to get rid of that.
