### ISSUE TITLE
[ISSUE] Instance_Pool disk_spec not expected

### ISSUE THREAD

**Issue by markhoiland** [databrickslabs/terraform-provider-databricks#238]
### Terraform Version
Terraform v0.13.0
+ provider registry.terraform.io/databrickslabs/databricks v0.2.3
+ provider registry.terraform.io/hashicorp/azurerm v2.22.0

### Affected Resource(s)
- databricks_instance_pool

### Terraform Configuration Files
```hcl
resource "databricks_instance_pool" "my_pool" {
  instance_pool_name                    = "test-pool"
  min_idle_instances                    = 2
  max_capacity                          = 8
  node_type_id                          = "Standard_DS3_v2"
  idle_instance_autotermination_minutes = 60
  enable_elastic_disk                   = true
  preloaded_spark_versions              = ["6.5.x-scala2.11"]
  disk_spec = {
    azure_disk_volume_type = "PREMIUM_LRS"
    disk_size              = 80
    disk_count             = 1
  }
}
```

### Debug Output
```
Error: Unsupported argument

  on main.tf line 85, in resource "databricks_instance_pool" "my_pool":
  85:   disk_spec = {

An argument named "disk_spec" is not expected here. Did you mean to define a
block of type "disk_spec"?
```

### Expected Behavior
Instance pool to be created with disk spec options, as in the examples here, providing the option to specify premium or standard disks.

### Actual Behavior
The provider is no longer expecting the "disk_spec" argument, but succeeds without issue without it.

### Steps to Reproduce
`terraform validate`
`terraform plan`
`terraform apply`

**Comment by nfx** [comment]
@markhoiland can you verify it working with tf0.12?

**Comment by stikkireddy** [comment]
@markhoiland please refer to https://databrickslabs.github.io/terraform-provider-databricks/resources/instance_pool/

disk_spec is a configuration block and not a map. 

# Invalid Config
```hcl
disk_spec = {
    azure_disk_volume_type = "PREMIUM_LRS"
    disk_size              = 80
    disk_count             = 1
  }
```

# Valid Config
```hcl
disk_spec {
    azure_disk_volume_type = "PREMIUM_LRS"
    disk_size              = 80
    disk_count             = 1
  }
```

**Comment by stikkireddy** [comment]
closing as its just an issue with the configuration
