### ISSUE TITLE
[ISSUE] More than one authorization method configured

### ISSUE THREAD

**Issue by sdebruyn** [databrickslabs/terraform-provider-databricks#266]
### Terraform Version
Terraform 0.12.29
Latest master (commit b95bcacb4fee531fc3f212b828da91d9f2308bc8)

### Affected Resource(s)
all resources

### Terraform Configuration Files
```hcl
provider "databricks" {
  host  =  "https://somethingonazure"
  token = "secret"
}
```

But read Important Factoids below...

### Debug Output
```
Error: More than one authorization method configured: azure and token
```

### Expected Behavior
Use the host and token for authorization.

But read Important Factoids below...

### Actual Behavior
See debug output

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
It noticed that I also have some Azure environment variables and treated it as an authorization method. However, I've only set the following variables:
* `ARM_TENANT_ID`
* `ARM_CLIENT_ID`
* `ARM_CLIENT_SECRET`
* `ARM_SUBSCRIPTION_ID`

This is not a complete authorization method as you don't know which workspace it should use. I'm using these for other resources in Terraform and Databricks should ignore them unless I add the workspace arguments.

**Comment by nfx** [comment]
@sdebruyn , but why are you not using just Azure authentication then? Internally it exchanges AAD token for PAT in AZ SP cases, which makes no point about this very specific env variable and argument combination. Situations of only one single attribute of Azure cloud configured without others can proliferate into unexpected and hard to debug scenarios.

Auth test cases are described here - https://github.com/databrickslabs/terraform-provider-databricks/blob/master/provider/provider_test.go#L82 - feel free to suggest a PR, which will work for all existing cases.

Closing this issue.

**Comment by andrew-oneill** [comment]
My team has run into a potential issue that this may address. It relates to [`databricks_secret_scope`](https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/resources/secret_scope.md)'s inability to be created using service principal authorization - [https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/resources/secret_scope.md#keyvault_metadata](https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/resources/secret_scope.md#keyvault_metadata)

Using Terraform Cloud in `Remote` execution mode, we are create our workspace using the azurem provider (authenticated with a service principal via the `ARM_*` environment variables) and authenticate the databricks provider with the resultant `azure_workspace_resource_id`. However, once we reach the point where the secret scope is to be created, we must switch the Terraform Cloud workspace to `Local` execution mode and run the plan on a team member's machine that is logged into the Azure CLI with their personal user to create the scope.

If we were able to utilize two provider blocks, we could use the databricks provider authenticated with the `azure_workspace_resource_id` to generate a token using [`databricks_token`](https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/resources/token.md#databricks_token-resource) and feed that token into the second databricks provider to authenticate with the workspace. We would then use the token authenticated provider to create the secret scope. This would allow us to execute the entire pipeline within Terraform Cloud without having to break in the middle and change which user is authenticated.

If this is already possible via another approach and I've simply missed it, I'm all ears.

**Comment by dsfrederic** [comment]
@nfx I'm having same error output. 

The reason why I'm not using the Azure Authentication via Service principal method is because ATM you cannot configure a secret scope using this method.  So what I'm trying to do is retrieve token with Azure Service Principal Authentication and then using the token in a dedicated databricks provider. 

```
module "databricks_token" {
  source = "../../_modules/databricks_token"
  
  adb_resource_id = module.azurerm_databricks_workspace.adb_resource_id
}


provider "databricks" {
  alias = "databricks_provider"

  host  = module.azurerm_databricks_workspace.adb_host
  token = module.databricks_token.databricks_token
}

resource "databricks_secret_scope" "kv" {
  name = "KRCG-KV-001"

  provider = databricks.databricks_provider
  keyvault_metadata {
    resource_id = module.azurerm_key_vault.kv_id
    dns_name    = module.azurerm_key_vault.kv_uri
  }
}
```


content of main.tf in `databricks_token` module 

```
variable "adb_resource_id" {
  type = string
}


terraform {
  required_providers {
    databricks = {
      source = "databrickslabs/databricks"
      version = "0.3.1"
    }
  }
}

provider "databricks" {
  alias                       = "created_workspace"
  azure_workspace_resource_id = var.adb_resource_id
}

// create PAT token to provision entities within workspace
resource "databricks_token" "pat" {
  provider = databricks.created_workspace
  comment  = "Terraform Provisioning"
  // 100 day token
  lifetime_seconds = 8640000
}

// output token for other modules
output "databricks_token" {
  value     = databricks_token.pat.token_value
  sensitive = true
}
```

**Comment by sdebruyn** [comment]
>you cannot configure a secret scope using this method

I also read this in the docs. I don't know why, but it just works for me. We use SP auth and have several secret scopes in our TF files without any issues. Did you try using it regardless?

**Comment by dsfrederic** [comment]
@sdebruyn I've tried using it without any luck... 

Can you show me a snippet of your databricks provider configuration block? Are you sure there are no environment variables configured?

**Comment by nfx** [comment]
@dsfrederic https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/secret_scope#keyvault_metadata should hold the details
