### ISSUE TITLE
[ISSUE] Provider Lazy Authentication

### ISSUE THREAD

**Issue by sdebruyn** [databrickslabs/terraform-provider-databricks#267]
### Terraform Version
Terraform 0.12.29
latest master version

### Affected Resource(s)
all

### Terraform Configuration Files
The following environment variables are set (copy from my azure-pipelines.yml):
```yml
echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(subscription-id)"
echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$(client-id)"
echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET]$(client-secret)"
echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(tenant-id)"
echo "##vso[task.setvariable variable=AD_CLIENT_ID]$(azuread-client)"
echo "##vso[task.setvariable variable=AD_CLIENT_SECRET]$(azuread-secret)"
```

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_databricks_workspace" "dbks" {
  name                        = "dbks${local.name}"
  resource_group_name         = azurerm_resource_group.rg.name
  managed_resource_group_name = "rgdbks${local.name}"
  location                    = local.region
  sku                         = "standard"
  tags                        = local.tags
}

provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.dbks.id
}

resource "databricks_instance_pool" "pool" {
  instance_pool_name                    = "dl-pool"
  min_idle_instances                    = 0
  node_type_id                          = "Standard_DS3_v2"
  idle_instance_autotermination_minutes = 10
  enable_elastic_disk                   = true
  preloaded_spark_versions              = [var.databricks_version]
}
```

### Debug Output
```
Error: Authentication is not configured for provider. Please configure it
through one of the following options:
1. DATABRICKS_HOST + DATABRICKS_TOKEN environment variables.
2. host + token provider arguments.
3. azure_databricks_workspace_id + AZ CLI authentication.
4. azure_databricks_workspace_id + azure_client_id + azure_client_secret + azure_tenant_id for Azure Service Principal authentication.
5. Run `databricks configure --token` that will create ~/.databrickscfg file.

Please check https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/index.md#authentication for details

  in databricks.tf, in provider "databricks":
  provider "databricks" {

```

### Expected Behavior
Succesful authentication

### Actual Behavior
Error above

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
I am using a child module that has a different provider configuration set, maybe they are conflicting?

**Comment by sdebruyn** [comment]
I tried this locally (instead of on Azure DevOps) and I don't get the error there. I'm not sure why this is happening.

**Comment by sdebruyn** [comment]
Aha, found the only difference between my machine and "the cloud". My machine had a file `~/.databrickscfg` After deleting it, I got the same error.

**Comment by sdebruyn** [comment]
I debugged this a little bit and apparently Terraform passes an empty string for that ID during the plan phase.

**Comment by sdebruyn** [comment]
This seems very similar to what we saw when working on PR #48 cc @stikkireddy

**Comment by sdebruyn** [comment]
Maybe the actual authentication validation should be delayed until it is actually used (e.g. when refreshing an existing resource or when creating/updating/deleting). By that time, Terraform will provide the real value instead of `""`

**Comment by nfx** [comment]
merged, verified to work properly with this config https://github.com/databrickslabs/terraform-provider-databricks/blob/c333abef9f15df242e5a63c89372914e36466ff3/scripts/awsmt-integration/main.tf

**Comment by MarekLani** [comment]
@nfx  please can you share bit more on how the over mentioned bits help when trying to use Azure Service Principal authentication, because I am still seeing error mentioned by @sdebruyn 

```
provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.databricks.id
  azure_client_id             = var.client_id
  azure_client_secret         = var.client_secret
  azure_tenant_id             = var.tenant_id
}
```

**Comment by lukerosser** [comment]
@nfx I'm also seeing this error when using service principal authentication as above.

I am trying to create the databricks workspace and use the provider for managing clusters within the same module so on the first run there is no workspace to authenticate against when running a plan.
