### ISSUE TITLE
[FEATURE] SCIM service principal resource

### ISSUE THREAD

**Issue by stikkireddy** [databrickslabs/terraform-provider-databricks#28]
**Is your feature request related to a problem? Please describe.**
I would like the scim service principal resource to be implemented, with acceptance tests and documented in the website docs. https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/scim/scim-sp

**Describe the solution you'd like**
This requires:
1. Client implementation to communicate with SCIM api
2. Resource object to create or destroy SCIM object
3. Documentation update describing the attributes of the service principal object & usage.

**Describe alternatives you've considered**
Design is straight forward follows the pattern of scim user.

**Additional context**
For more information read here:  https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/scim/scim-sp. It enables you to use Terraform to add SCIM service principals to the workspace via SCIM.

**Comment by nfx** [comment]
issue is old and it doesn't seem it needs any attention. closing it for now

**Comment by tcz001** [comment]
Hi @nfx  I hope we can reopen this issue, scim_service_principal is not implemented on this provider

**Comment by stikkireddy** [comment]
@tcz001 want to pick this up?

**Comment by nfx** [comment]
why do we need to create SP through scim api? won't it simply work if SP is granted contributor role on workspace resource in Azure through either Portal UI or terraform role assignment resource?

**Comment by dfanesiDB** [comment]
FYI: I have a project starting in few weeks which will need Active Directory and SCIM integration features in Terraform. I wonder whether it is possible to completely automate in Terraform the workspace creation and the AD configuration with SCIM enabled.

**Comment by tcz001** [comment]
@nfx we need Service principal in scim because it's without the Admin permission by default, while Azure RBAC contributor role will be added as by default and it has 2000 role assignments limitation, that's why we need this resource to be implemented

**Comment by tcz001** [comment]
> @tcz001 want to pick this up?

yes, we will try to send a PR on this

**Comment by tcz001** [comment]
@nfx  one quick question, should we name the resource as databricks_service_principal to follow your recent change on databricks_user and databricks_scim_user?

**Comment by nfx** [comment]
@tcz001 , `databricks_service_principal` is naming convention to go ahead with, correct. SCIM is just the name of the industry standard interface to manage identities, it shouldn't leak into resource names. Most of people would even ask first - "what is SCIM?..". 

To be clear, this is what we'd expect in PR:

* resource code itself, which has 90% coverage by unit tests - see examples for `databricks_user`. you can check coverage by running `make coverage`.
* acceptance test
* documentation (+change to `databricks_permissions` resource doc in this particular case)

**Comment by tcz001** [comment]
@nfx @sdebruyn  PR is created

**Comment by nfx** [comment]
Changes from #386 merged in #432 and will be part of 0.3.0 release.

**Comment by snowch** [comment]
As this ticket is closed, is the original requirement (below) now possible with terraform?

> I would like the scim service principal resource to be implemented, with acceptance tests and documented in the website docs. https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/scim/scim-sp

Are there any docs on this?  I couldn't see anything here:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/147713/190638423-8ceed75b-67bb-44ea-b175-c52780f453aa.png">

There's also a question on this topic [stackoverflow](https://stackoverflow.com/questions/70926276/configuring-the-azure-ad-databricks-scim-application-with-terraform).

**Comment by nfx** [comment]
@snowch https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/service_principal
