### ISSUE TITLE
[ISSUE] Provider bug

### ISSUE THREAD

**Issue by RamlaSuhra123** [databrickslabs/terraform-provider-databricks#292]
Hi Team,
I am facing below issue while trying to run terragrunt/terraform apply on module, "databricks_mws_workspaces" while trying to create multiworkspace. As per debug logs, workspace is going to provisioning stage and then later getting aborted.

Error: Error: Workspace is in a non runnable state will not be able to transition to running, needs to be created again. Current state: FAILED

**Below are the details:**

### Terraform Version

<User>: I am using the latest version. Terraform v0.13.1

### Affected Resource(s)

<User>: databricks_mws_workspaces

### Debug Output

<User>: Error Log: 
--------------------
2020/09/02 17:01:13 [DEBUG] [aws-sdk-go] DEBUG: Response dynamodb/DeleteItem Details:
---[ RESPONSE ]--------------------------------------
HTTP/1.1 200 OK
Connection: close
Content-Length: 2
Content-Type: application/x-amz-json-1.0
Date: Wed, 02 Sep 2020 22:01:13 GMT
Server: Server
X-Amz-Crc32: 2745614147
X-Amzn-Requestid: M71QEG5BMMIMPOQ1N9EVV184B3VV4KQNSO5AEMVJF66Q9ASUAAJG

-----------------------------------------------------
2020/09/02 17:01:13 [DEBUG] [aws-sdk-go] {}
2020-09-02T17:01:13.783-0500 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"
2020-09-02T17:01:13.784-0500 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.4/darwin_amd64/terraform-provider-databricks_v0.2.4 pid=7197
2020-09-02T17:01:13.784-0500 [DEBUG] plugin: plugin exited

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.
<User>: Not applicable

### Expected Behavior
What should have happened?
<User>: Created Workspace using this resource

### Actual Behavior
What actually happened?
<User> Got Error Message: Error: Workspace is in a non runnable state will not be able to transition to running, needs to be created again. Current state: FAILED

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

<User>: Terragrunt apply (which is in effect "terraform apply" in the background)
### Important Factoids
Are there anything atypical about your accounts that we should know?

**Comment by nfx** [comment]
Hi @RamlaSuhra123 , can you provide more information, like what are the other configs, that feed into workspace resource? also the logs do not contain any calls to databricks API

**Comment by stikkireddy** [comment]
Not related to the provider.
