### ISSUE TITLE
[FEATURE] Support for new Global Init Scripts

### ISSUE THREAD

**Issue by markhoiland** [databrickslabs/terraform-provider-databricks#295]
New Global Init Scripts are now in public preview.  [Global Init Scripts API](https://docs.databricks.com/dev-tools/api/latest/global-init-scripts.html)

##### This implementation may look like:
```hcl
resource "databricks_global_init_script" "script" {
  script_content = base64encode("./script/path")
  name = "init_script"
  position = 1
  enabled = true
}
```

**Comment by nfx** [comment]
for those, who'll be picking this up: this one should be in `compute` module and should preferably use reflect resource.

**Comment by nfx** [comment]
> when creating new object we need to check if the script with the same name already exists or not
> is it possible to have 2 scripts with the same position value?
integration test will tell you if API is handling those things already 

> should we detect changes in the content of the script itself, and send changes to DB?
yes, whenever content is updated, init script should be updated as well.

**Comment by markhoiland** [comment]
@alexott @nfx is there a estimated release date of v0.3.0 if that's the release this feature will be added to? 

Thanks for your help.

**Comment by nfx** [comment]
Update, global init scripts should use the same content_base64/source critical code path, as dbfs files and notebooks.

**Comment by davidferdinand** [comment]
@alexott @nfx do you have any updates on when v0.3.0 will be ready with this feature? it will be great as its currently one of the only manual steps we have in set up
