### ISSUE TITLE
[ISSUE] Unclear error message when the location to be mounted does not exist

### ISSUE THREAD

**Issue by sdebruyn** [databrickslabs/terraform-provider-databricks#321]
### Terraform Version
Terraform 0.13.2
Databricks 0.2.4

### Affected Resource(s)
- databricks_azure_adls_gen2_mount

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "databricks_azure_adls_gen2_mount" "mongo_staging" {
  depends_on             = [azurerm_role_assignment.sp_integration]
  provider               = databricks.cws
  container_name         = "integration"
  storage_account_name   = module.datalake.storage_account_name
  mount_name             = "mongo_staging_dl_${var.customerID}"
  tenant_id              = data.azurerm_key_vault_secret.integration["service-principal-staging-tenant-id"].value
  client_id              = data.azurerm_key_vault_secret.integration["service-principal-staging-client-id"].value
  client_secret_scope    = databricks_secret_scope.cws.name
  client_secret_key      = databricks_secret.cws_client_secret.key
  initialize_file_system = true
  directory              = "/mongo_staging"
}
```

### Debug Output
https://gist.github.com/sdebruyn/f20d899d63191f902d1cd3225f15edc6

### Expected Behavior
An error saying that the mount location does not exist. Or, create the directory for me, since I expected that this is what the initialize filesystem does.

### Actual Behavior
An error with the following message:
```
Error: GET https://secret.dfs.core.windows.net/secret?resource=filesystem&maxResults=5000&directory=secret&timeout=90&recursive=false
```

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Possibly related to #94

**Comment by nfx** [comment]
@sdebruyn

1. latest version is 0.2.5
2. error message could probably be fixed by moving [errorMessageRE upwards](https://github.com/databrickslabs/terraform-provider-databricks/blob/732b3f01224658d9ee01a594f3be1e5d27a613f8/compute/commands.go#L88)
3. #94 there's no way of generic validating if the path is there or not without mounting it first

**Comment by nfx** [comment]
@sdebruyn it will eventually be fixed on the backend, so closing this issue.
