### ISSUE TITLE
[ISSUE] mws_workspace resources AWS region check out of date

### ISSUE THREAD

**Issue by RobertHorrox** [databrickslabs/terraform-provider-databricks#327]
In `mws/resource_workspace.go` on [line 147](https://github.com/databrickslabs/terraform-provider-databricks/blob/785cb2d0e1c3ae495f5145465552911536685bc5/mws/resource_workspace.go#L147) a region check is performed which doesn't include `us-east-2`.  According to [https://docs.databricks.com/administration-guide/account-api/new-workspace.html] `us-east-2` is a supported region.

**Comment by nfx** [comment]
@RobertHorrox fixed, should be available in next release. You can also [install it from sources](https://github.com/databrickslabs/terraform-provider-databricks/blob/master/CONTRIBUTING.md#installing-from-source).
