### ISSUE TITLE
[ISSUE] add support for sql-analytics-access in databricks_group

### ISSUE THREAD

**Issue by itaiw** [databrickslabs/terraform-provider-databricks#341]
Hi there,

Databricks groups REST API added support for "sql-analytics-access" in databricks_group. Please add it tot he TF resource

example:
"entitlements": [
                {
                    "value": "allow-cluster-create"
                },
                {
                    "value": "allow-instance-pool-create"
                },
                {
                    "value": "sql-analytics-access"
                }

### Affected Resource(s)
databricks_group
databricks_user

Thank you,
Itai

**Comment by nfx** [comment]
Should be added to 

* `databricks_user`
* `databricks_group`

must not be added to deprecated resources.

**Comment by nfx** [comment]
`sql-analytics-access` is not documented in any of the public docs, so won't be adding it for now with the risk of name changes and things related to it.
