### ISSUE TITLE
Data source for cloud-dependent node types

### ISSUE THREAD

**Issue by nfx** [databrickslabs/terraform-provider-databricks#346]
Make terraform configuration less cloud-dependent by allowing to specify node characteristics instead of node type names

```hcl
data "databricks_node_type" "ds" {
    min_memory = 32
    min_memory_per_core = 2
    min_cores = 8
    local_disk = true
    min_gpus = 1
}
```

* by default should return smallest possible instance with local disk
* min_memory_per_core conflicts with min_memory
* id is set to the first matching node type
* error is returned if no match

**Comment by nfx** [comment]
already implemented it, PR pending

**Comment by gilShin** [comment]
I'm working on Azure and for some reason I sometimes get i3.xlarge
Looks like a bug to me
