### ISSUE TITLE
[ISSUE] azure_workspace_name ignored when ~/.databrickscfg profile points to another workspace

### ISSUE THREAD

**Issue by fedragon** [databrickslabs/terraform-provider-databricks#349]
Hi Databricks team,

I just run into the following unexpected (to me) behavior of the provider, related to the presence of a `~/.databrickcfg` file in combination with the usage of [azure_workspace_name](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs#azure_workspace_name) provider argument. 

The configuration file contains a `DEFAULT` profile pointing to a workspace (say `workspace001`) whereas the Terraform configuration points to `workspace002`: after applying the configuration, the cluster was created in `workspace001`.

I understand that it is related to the usage of PAT tokens, the only reason I opened this issue is that _I think_ it would be nice if the provider warned its user about such configuration errors (or failed, maybe). If you don't think so, please feel free to close it right away.

### Terraform Version

0.12.26

### Affected Resource(s)

- databricks_cluster (in my case, but I suspect that any resources created with such a provider configuration would be affected)

### Environment variable names

```
ARM_CLIENT_ID
ARM_CLIENT_SECRET
ARM_SUBSCRIPTION_ID
ARM_TENANT_ID
```

### Terraform Configuration Files

```hcl
provider "databricks" {
  azure_resource_group = var.resource_group_name
  azure_tenant_id      = data.azurerm_client_config.current.tenant_id
  azure_workspace_name = "workspace002"
}

resource "databricks_cluster" "fs_mounter" {
  cluster_name            = "my-cluster"
  idempotency_token       = "my-cluster"
  spark_version           = "7.0.x-scala2.12"
  driver_node_type_id     = "Standard_DS3_v2"
  node_type_id            = "Standard_DS3_v2"
  num_workers             = 1
  autotermination_minutes = 10
}
```

### Debug Output

I didn't find any relevant information in the debug output (credentials and workspace names are not logged). If you still think it's useful, I can provide it.

### Panic Output

N/A

### Expected Behavior

`my-cluster` should have been created in workspace `workspace002`.

### Actual Behavior

`my-cluster` was created in workspace `workspace001`.

### Steps to Reproduce

1. `databricks configure --token` (providing the credentials for `workspace001` in a `DEFAULT` profile)
2. `terraform apply`

**Comment by nfx** [comment]
@fedragon please check the order of authorisation method resolution in documentation:
https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs#empty-provider-block and tell at which step was it not expected?

`azure_tenant_id` is not needed when you set `ARM_TENANT_ID` environment variable.

i see you have `fs_mounter` cluster - if you omit cluster_id for `*_mount` resources - https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/azure_blob_mount - it would create a temporary cluster for you.

**Comment by fedragon** [comment]
Hi @nfx, thanks for your quick reaction! 

The authorisation resolution works as expected, no issues there (I went through it before opening this issue): the misconfiguration was on my side. Yet, as a user of this provider, I would find it very nice to be at least warned when my credentials and `azure_workspace_name` are not aligned, because it can easily lead to the creation (or worse, replacement) of resources in the wrong workspace.

> azure_tenant_id is not needed when you set ARM_TENANT_ID environment variable.

Good point, thanks. I will remove it!

> i see you have fs_mounter cluster - if you omit cluster_id for *_mount resources - https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/azure_blob_mount - plugin would create a temporary cluster for you.

Thanks, I know but I prefer to reuse a single cluster for all mount operations

**Comment by nfx** [comment]
@fedragon what provider version is used, btw? in 0.2.5 this issue should have been fixed.

```
terraform {
  required_providers {
    databricks = {
      source = "databrickslabs/databricks"
      version = "0.2.5"
    }
  }
}
```

**Comment by nfx** [comment]
> Thanks, I know but I prefer to reuse a single cluster for all mount operations

it's actually re-used for all of the mount points, which don't specify the cluster_id 🤷‍♂️

**Comment by fedragon** [comment]
I'm using version `0.2.5`

> it's actually re-used for all of the mount points, which don't specify the cluster_id 🤷‍♂️

To my understanding (and please correct me if I'm wrong), two different executions of Terraform would create a temporary cluster each... and since these clusters can *never* be deleted (otherwise any subsequent execution of Terraform will fail because the provider stores the cluster ID in Terraform's remote state and fails if it cannot find it in the workspace), I prefer to have meaningful names

**Comment by fedragon** [comment]
> since these clusters can never be deleted (otherwise any subsequent execution of Terraform will fail because the provider stores the cluster ID in Terraform's remote state and fails if it cannot find it in the workspace)

@nfx Thinking about it, is this actually intended behavior? If not, I'm happy to open an issue with more details

**Comment by nfx** [comment]
> two different executions of Terraform would create a temporary cluster each...

no, it's not the case. on azure first execution will create a cluster named "terraform-mount" and all subsequent calls would check if it exists and use that one - https://github.com/databrickslabs/terraform-provider-databricks/blob/master/storage/mounts.go#L107 and https://github.com/databrickslabs/terraform-provider-databricks/blob/master/compute/clusters.go#L258 - cluster is never deleted, but it's stopped after 10 minutes of inactivity

**Comment by fedragon** [comment]
> no, it's not the case. on azure first execution will create a cluster named "terraform-mount" and all subsequent calls would check if it exists and use that one

okay, looks like I was wrong... thanks for the clarification! 🙂
