### ISSUE TITLE
[FEATURE] Add support for Cluster Events API

### ISSUE THREAD

**Issue by alexott** [databrickslabs/terraform-provider-databricks#350]
For correct support of pinned clusters (#113) we need to add support for [Cluster Events API](https://docs.databricks.com/dev-tools/api/latest/clusters.html#events) as we don't get information if cluster pinned or unpinned from the `Get` API.

it would be easier to track this work in a separate issue to keep the size of PR for #113 under the control

**Comment by nfx** [comment]
i'm not sure if cluster events are of any use within terraform than cluster pinning status. All the work for it should be done in scope of #113

**Comment by alexott** [comment]
Implemented as part of the #348
