### ISSUE TITLE
Data source to iterate tables and databases in metastore

### ISSUE THREAD

**Issue by nfx** [databrickslabs/terraform-provider-databricks#359]
Need to create a data source to be able to iterate through tables in metastore. Approximate resource may look like:

```hcl
data "databricks_tables" "default" {
    database = "default" # default, optional
    cluster_id = ... # empty by default, re-uses approach for mounting cluster
    filter = ... # some sort of optional filter not to blow state file
}

data "databricks_table" "default" {
    # to dump SHOW TABLE CREATE ...
    database = "default"
    table_name = "things"
    cluster_id = ... # empty by default, re-uses approach for mounting cluster
}

data "databricks_databases" "default" {
    cluster_id = ... # empty by default, re-uses approach for mounting cluster
    filter = ... # some sort of optional filter not to blow state file
}
```

theoretically with this, we could do something like, though not quite sure if it would be used extensively.

```hcl
resource "databricks_query" "create_table" {
     sql_query = "SELECT foo, bar, baz FROM a"
     cluster_id = ... # empty by default, re-uses approach for mounting cluster
} 
```

This should simplify certain replication scenarios.

Adding more features based on Command/Context API would require #358 to be implemented first, as we don't know how well this might be received by community.

**Comment by stikkireddy** [comment]
hmm.... the second part of that feels like it is very easy for a user to shoot themselves in the foot maybe only for non-managed tables?

**Comment by nfx** [comment]
yeah... `databricks_query` might be good for initial WS setup with random queries, but it opens up unnecessary possibilities for terraform. first 2-3 resources are of great value, though

**Comment by nfx** [comment]
Parking this one for now. There's no significant need for it. Would be addressed if somebody opens up the issue again.
