### ISSUE TITLE
[DOC] Request more Information on non-BYOVPC deployment 

### ISSUE THREAD

**Issue by HamiltonHord** [databrickslabs/terraform-provider-databricks#368]
### Affected Resource(s)
[databricks_mws_workspaces Resource ](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/mws_workspaces)

### Expected Details
While I understand that the suggested behavior of creating a Databricks Workspace is to use the BYOVPC option, but I was curious about some of the behavior/exported information when creating a workspace resource in a non-BYOVPC deployment.

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [x] databricks_mws_workspaces Resource - Need more information about non-BYOVPC deployment behavior. 

### Important Factoids
[Databricks API docs for this ](https://docs.databricks.com/dev-tools/api/latest/account.html)

**Comment by HamiltonHord** [comment]
The only thing I'd like to see is somehow having the Databricks created VPC Id as an attribute that can be used elsewhere. For example, I'd like databricks to make me the VPC, but I then want to hook that VPC up to a Transit gateway + get the VPC info for routing.

**Comment by nfx** [comment]
Will be fixed in #400
