### ISSUE TITLE
[FEATURE] Support for back_end_azure_key_vault and backend_type

### ISSUE THREAD

**Issue by stikkireddy** [databrickslabs/terraform-provider-databricks#369]
Hi there,

Please support following fields in databricks_secret_scope:

1. back_end_azure_key_vault block for secret scopes 
2. scope_backend_type field to support AKV backed secrets (optional)

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_secret_scope

HCL example:

*Databricks backed scope*
```hcl
resource databricks_secret_scope my_scope {
    name = "my scope"
    initial_manage_principal = "users"
}
```

*AKV backed scope*
```hcl
resource databricks_secret_scope my_scope {
    name = "my scope"
    initial_manage_principal = "users"
    scope_backend_type = "AZURE_KEYVAULT" 
    backend_azure_keyvault { 
         resource_id = "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/azure-rg/providers/Microsoft.KeyVault/vaults/my-azure-kv"
         dns_name = "https://my-azure-kv.vault.azure.net/"
    }
}
```

scope_backend_type should be optional string with validation on certain string entries.
backend_azure_keyvault should be an optional block that is only required for akv.

The docs contain more information about secret scopes with akv via REST api.

https://docs.microsoft.com/en-us/azure/databricks/dev-tools/api/latest/secrets#secretsecretservicecreatescope

**Comment by nfx** [comment]
@markhoiland, @alaczynski, it will only work for Azure CLI authentication, but not for Service Principals. That means, `az login --service-principal --username $ARM_CLIENT_ID --password $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID` won't work. This is the limitation from underlying cloud resources.

**Comment by favoretti** [comment]
@nfx How come SP auth won't work on this?

**Comment by nfx** [comment]
it's related to support of "on-behalf-of" flow
