### ISSUE TITLE
[ISSUE] Provider lazy authentication

### ISSUE THREAD

**Issue by lukerosser** [databrickslabs/terraform-provider-databricks#372]
### Terraform Version

Terraform 0.13.4
Databricks Provider 0.2.7

### Affected Resource(s)

provider initialisation

### Terraform Configuration Files
```hcl
provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.databricks_workspace.id
  azure_client_id             = var.client_id
  azure_client_secret         = var.client_secret
  azure_tenant_id             = var.tenant_id
}
```

### Debug Output
```
Error: Authentication is not configured for provider. Please configure it
through one of the following options:
1. DATABRICKS_HOST + DATABRICKS_TOKEN environment variables.
2. host + token provider arguments.
3. azure_databricks_workspace_id + AZ CLI authentication.
4. azure_databricks_workspace_id + azure_client_id + azure_client_secret + azure_tenant_id for Azure Service Principal authentication.
5. Run `databricks configure --token` that will create ~/.databrickscfg file.

Please check https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/index.md#authentication for details
```

### Expected Behavior
Authentication isn't attempted until required

### Actual Behavior
Authentication is attempted on a plan

### Steps to Reproduce

1. `terraform plan`

### Further information

I am trying to manage a databricks workspace and other databricks provider resources such as clusters in the same Terraform configuration. On first run, as the workspace doesn't exist yet, I get authentication errors when running a plan.

Related issue that was supposed to resolve this: https://github.com/databrickslabs/terraform-provider-databricks/issues/267

**Comment by stikkireddy** [comment]
Please look at a similar issue that happens in the https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs#stacking-with-managed-kubernetes-cluster-resources.

```The root issue lies with the order in which Terraform itself evaluates the provider blocks vs. actual resources. Please refer to this section of Terraform docs for further explanation.```

The suggestion is to manage with separate apply operations.

**Comment by lukerosser** [comment]
Thanks for the quick reply! That makes sense. I've managed to work around it by using locals to pre-configure related resource names and then reference those when building the workspace resource id in the provider config:

```
locals {
  local.databricks_workspace_name = "workspace-name"
  local.databricks_workspace_rg   = "workspace-resource-group"
}

resource "azurerm_databricks_workspace" "databricks_workspace" {
  name  = local.databricks_workspace_name
  ...
  ...
}

provider "databricks" {
  azure_workspace_resource_id = "/subscriptions/${data.azurerm_client_config.current.subscription_id}/resourceGroups/${local.databricks_workspace_rg}/providers/Microsoft.Databricks/workspaces/${local.databricks_workspace_name}"
  azure_client_id             = var.client_id
  azure_client_secret         = var.client_secret
  azure_tenant_id             = var.tenant_id
}
```

and databricks provider resources all have a `depends_on` block with the databricks workspace


It might be helpful to add something similar to the kubernetes provider here, or a reference, so it's clear what the options are.

**Comment by nfx** [comment]
@lukerosser overall recommendation is to also separate workspace creation (azurerm provider) and for workspace provisioning (databricks provider). 

the other workaround is to have an empty `~/.databrickscfg` file, so `locals` block might be avoided. not ideal, but will work.

i was able to reproduce this issue by renaming my `~/.databrickscfg`, but haven't gotten time to find the right stack trace why it happens on plan.

**Comment by nfx** [comment]
@lukerosser 

In Terraform 0.13 and later, data resources have the same dependency resolution behavior as defined for managed resources. Most data resources make an API call to a workspace. If a workspace doesn't exist yet, Authentication is not configured for provider error is raised. To work around this issue and guarantee a proper lazy authentication with data resources, you should add depends_on = [azurerm_databricks_workspace.this] or depends_on = [databricks_mws_workspaces.this] to the body. This issue doesn't occur if workspace is created in one module and resources within the workspace are created in another. We do not recommend using Terraform 0.12 and earlier, if your usage involves data resources.

here's the configuration tested:

```
terraform {
  required_providers {
    databricks = {
      source = "databrickslabs/databricks"
    }
  }
}

provider "azurerm" {
  features {}
}

variable "region" {
  type = string
  default = "westeurope"
}

resource "random_string" "naming" {
  special = false
  upper   = false
  length  = 6
}

data "azurerm_client_config" "current" {
}

data "external" "me" {
  program = ["az", "account", "show", "--query", "user"]
}

locals {
  prefix = "databricksdemo${random_string.naming.result}"
  tags = {
    Environment = "Demo"
    Owner       = lookup(data.external.me.result, "name")
  }
}

resource "azurerm_resource_group" "this" {
  name     = "${local.prefix}-rg"
  location = var.region
  tags     = local.tags
}

resource "azurerm_databricks_workspace" "this" {
  name                        = "${local.prefix}-workspace"
  resource_group_name         = azurerm_resource_group.this.name
  location                    = azurerm_resource_group.this.location
  sku                         = "premium"
  managed_resource_group_name = "${local.prefix}-workspace-rg"
  tags                        = local.tags
}

provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.this.id
}

data "databricks_current_user" "me" {
  depends_on = [azurerm_databricks_workspace.this]
}

data "databricks_group" "admins" {
  display_name = "admins"
  depends_on = [azurerm_databricks_workspace.this]
}

resource "databricks_notebook" "this" {
  path     = "${data.databricks_current_user.me.home}/Terraform"
  language = "PYTHON"
  content_base64 = base64encode(<<-EOT
    # created from ${abspath(path.module)}
    # admins group id: ${data.databricks_group.admins.id}
    display(spark.range(10))
    EOT
  )
}

resource "databricks_user" "me" {
  user_name    = "mee@example.com"
}

resource "databricks_group_member" "my_member_a" {
  group_id = data.databricks_group.admins.id
  member_id = databricks_user.me.id
}
```

**Comment by jonathansp** [comment]
@stikkireddy  @lukerosser @nfx thanks for the detailed explanation.

in my use case, I have a shared `azurerm_databricks_workspace`. How this shared resource should be referenced to avoid the _Authentication is not configured for provider_ error? 

```hcl
# ../../../modules/databricks/workspace/main/.tf
# shared and used by others.

resource "azurerm_databricks_workspace" "instance" {
  name                        = local.full_name
  sku                         = var.sku
  ...
}

```

```hcl
# main.tf local
module "rg" {
    ...
}
module "databricks" {
  source                      = "../../../modules/databricks/workspace"   <--- included using source.
  resource_group              = module.rg._all
  ...
}
resource "databricks_instance_pool" "instance_pool" {
   ...
}

data "databricks_current_user" "me" {
  depends_on = [azurerm_databricks_workspace.instance]    <---- will error out as the resource does not exists in this file.
}
```

Output:

```shell
Error: Reference to undeclared resource

  on main.tf line 111, in data "databricks_current_user" "me":
 111:   depends_on = [azurerm_databricks_workspace.instance]

A managed resource "azurerm_databricks_workspace" "instance" has not been
declared in the root module.
```

if this line is removed or I add _depends_on=[module.databricks]_, I will get the `Authentication is not configured for provider.`

**Comment by nfx** [comment]
@jonathansp please open an issue on https://github.com/hashicorp/terraform/issues/new/choose, it's not an issue of this provider, it's rather the way how terraform works. 

In your case, `depends_on = [module.databricks]` should fix the data source auth error.

**Comment by edboykin-insight** [comment]
This appears broken again? I built a very simple module to build the workspace and cluster and I am getting the authentication error. It appears related to being in a module. If I run the config as regular tf and not in a module it works.

azurerm 2.52.0
databricks 0.3.2
```
#############################################################################
# DATA BRICKS WORKSPACE
#############################################################################
resource "azurerm_databricks_workspace" "databricks" {
  name                   = var.DATABRICKS.name
  location               = var.LOCATION
  resource_group_name    = var.RESOURCE_GROUP
  sku                    = var.DATABRICKS.sku

  tags                   = local.TAGS
}

#############################################################################
# DATABROCK PROVIDER CONFIG
#############################################################################

provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.databricks.id
}

#############################################################################
# DATA BRICKS CLUSTER
#############################################################################

resource "databricks_cluster" "research" {
    cluster_name            = var.DATABRICKS.cluster_name
    spark_version           = "7.6.x-cpu-ml-scala2.12"#data.databricks_spark_version.ml_spark.id
    node_type_id            = var.DATABRICKS.node_type_id
    driver_node_type_id     = var.DATABRICKS.driver_node_type_id
    autotermination_minutes = var.DATABRICKS.autotermination_minutes
    autoscale {
        min_workers = var.DATABRICKS.min_workers
        max_workers = var.DATABRICKS.max_workers
    }

    azure_attributes {
      availability       = "ON_DEMAND_AZURE"
      first_on_demand    = 1
      spot_bid_max_price = -1
    }    

    depends_on = [azurerm_databricks_workspace.databricks]
}


```

**Comment by odoo-ce-modules** [comment]
@jonathansp were you ever able to get this working?  I've followed all the recommendations and can't get this to work. Currently I'm creating the workspace in a separate module because using the `depends_on` "fix" was the first thing that I tried without success.

**Comment by odoo-ce-modules** [comment]
Never mind. I added ..
```
provider "databricks" {
  host = module.databricks.workspace_url
}```

.. which did the trick.
