### ISSUE TITLE
[ISSUE] Creation of workspace folder ?

### ISSUE THREAD

**Issue by BertrandDechoux** [databrickslabs/terraform-provider-databricks#373]
Hi,

I am wondering if workspace folders can be created with Terraform ?

I did not find much about this topic.

The documentation of databricks_permissions describes how to manage the folder permission. But even there, the folder is not created. The folder is expected to already have been created. However, for all other permission examples (cluster, policy, pool and notebook), the test resource is created within the example.

Is it simply not yet supported ?

Regards

**Comment by nfx** [comment]
@BertrandDechoux what is the use-case?

**Comment by BertrandDechoux** [comment]
The workspace is shared between multiple teams and that's not something I can change.

I would like to create a distinct workspace folder for each teams and provide the correct rights to it using databricks_permissions.

But as for notebooks, the users will be able to create them by themselves.

So I could create a notebook as a workaround but that seems a big workaround.

I am currently investigating databricks_dbfs_file as a workaround because it will create parent folders.

**Comment by nfx** [comment]
@BertrandDechoux , you can do the following - will it work for your case?

```
resource "databricks_notebook" "readme" {
  # also add some more standard content, like links to team's clusters, jobs & such
  content = base64encode("# ${vars.team_name} home")
  path = "/Teams/${vars.team_name}/README"
  overwrite = true
  mkdirs = true
  language = "PYTHON"
  format = "SOURCE"
}

resource "databricks_permissions" "notebook_usage" {
    notebook_id = databricks_notebook.readme.id

    access_control {
        group_name = vars.team_name
        permission_level = "CAN_RUN"
    }
}

resource "databricks_permissions" "team_folder" {
    directory_path = dirname(databricks_notebook.readme.path)

    access_control {
        group_name = vars.team_name
        permission_level = "CAN_MANAGE"
    }
}
```

If you'd need folder creation from terraform on more granular level - PR for **databricks_folder** is welcome :)

**Comment by BertrandDechoux** [comment]
Thanks. It is close to what I am doing now.

I would have created a PR for databricks_folder if I had the time to implement it. But sadly, that won't be for 2020.

**Comment by abij** [comment]
Workaround still works fine, need some adjustments with latest version. _(no overwrite, mkdirs, format)_

```
resource "databricks_notebook" "prod_readme" {
  content_base64 = base64encode("# Production notebooks and jobs")
  path = "/Prod/README"
  language = "PYTHON"
}

data "databricks_notebook_paths" "prod" {
  path = "/Prod"
  recursive = false
  depends_on = [databricks_notebook.prod_readme]
}

data "databricks_group" "users" {
  display_name = "users"
}

resource "databricks_permissions" "prod-read-access" {
  directory_path = data.databricks_notebook_paths.prod.path

  access_control {
    group_name       = data.databricks_group.users.display_name
    permission_level = "CAN_READ"
  }
}
```
