### ISSUE TITLE
[ISSUE] databricks_permissions fails everytime with Error: Cluster {cluster_id} does not exist

### ISSUE THREAD

**Issue by itachiRedhair** [databrickslabs/terraform-provider-databricks#374]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
v0.13.0

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_permissions
- databricks_cluster

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Environment variable names
ARM_CLIENT_ID
ARM_CLIENT_SECRET
ARM_SUBSCRIPTION_ID
ARM_TENANT_ID

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    databricks = {
      source  = "databrickslabs/databricks"
      version = ">= 0.2.7"
    }
  }
}

provider "databricks" {
  alias = "workspace"
}

resource "databricks_cluster" "this" {
  provider = databricks.workspace

  cluster_name  = var.cluster_name
  spark_version = var.spark_version
  node_type_id  = var.node_type_id
  autoscale {
    min_workers = var.autoscale.min_workers
    max_workers = var.autoscale.max_workers
  }
  custom_tags = var.custom_tags
  spark_conf  = var.spark_conf

  dynamic "library" {
    for_each = var.pypi_packages
    content {
      pypi {
        package = library.value["package"]
        repo    = lookup(library.value, "repo", null)
      }
    }
  }

  dynamic "library" {
    for_each = var.maven_packages
    content {
      maven {
        coordinates = library.value["coordinates"]
        exclusions  = lookup(library.value, "exclusions", [])
      }
    }
  }

  dynamic "library" {
    for_each = var.cran_packages
    content {
      cran {
        package = library.value["package"]
      }
    }
  }
}

resource "databricks_permissions" "this" {
  cluster_id = databricks_cluster.this.cluster_id

  dynamic "access_control" {
    for_each = var.permissions
    content {
      group_name       = access_control.value["group_name"]
      permission_level = access_control.value["permission_level"]
    }
  }
}

```

### Debug Output
```
databricks_group.primary_ws["test-group-created-by-tf"]: Modifying... [id=5525292978316171]
module.common_cluster_clone.databricks_cluster.this: Modifying... [id=1019-181008-share810]
databricks_group.primary_ws["test-group-created-by-tf"]: Modifications complete after 5s [id=5525292978316171]
module.common_cluster_clone.databricks_cluster.this: Still modifying... [id=1019-181008-share810, 10s elapsed]
module.common_cluster_clone.databricks_cluster.this: Still modifying... [id=1019-181008-share810, 20s elapsed]
module.common_cluster_clone.databricks_cluster.this: Still modifying... [id=1019-181008-share810, 30s elapsed]
module.common_cluster_clone.databricks_cluster.this: Still modifying... [id=1019-181008-share810, 40s elapsed]
module.common_cluster_clone.databricks_cluster.this: Still modifying... [id=1019-181008-share810, 50s elapsed]
module.common_cluster_clone.databricks_cluster.this: Still modifying... [id=1019-181008-share810, 1m0s elapsed]
module.common_cluster_clone.databricks_cluster.this: Modifications complete after 1m6s [id=1019-181008-share810]
module.common_cluster_clone.databricks_permissions.this: Creating...

Error: Cluster 1019-181008-share810 does not exist
(404 on /api/2.0/preview/permissions/clusters/1019-181008-share810)
```

### Expected Behavior
Databricks permission should have been created after cluster creation/modifications.

### Actual Behavior
Fails with the error that the cluster doesn't exist even though the cluster is created and is in running state. Another strange behavior is cluster libraries are always updated even though there is no change. This results in update in cluster everytime terraform apply is run. After this databricks_permission creation fails.

**Comment by nfx** [comment]
@itachiRedhair does this happen every time? can you try doing it without provider aliasing? 

could you share the API request sequence around permissions endpoint? `TF_LOG=DEBUG` before terraform apply. 

Please create separate issue for library updates with more details. one of the reasons for that might be unpredictable sequence that arguments are passed to a module.

**Comment by itachiRedhair** [comment]
@nfx My bad. `databricks_permissions` resource was missing provider alias. I seriously need to log off for the day.
Thanks for the hint.

I'm still facing another problem which is: libraries are always getting updated even in subsequent successful `terraform apply`. Could it be because of `dynamic` expression?

**Comment by nfx** [comment]
@itachiRedhair don't use aliases when you don't have to :) separate your code into modules.

> I'm still facing another problem which is: libraries are always getting updated even in subsequent successful terraform apply. Could it be because of dynamic expression?

it might be because of dynamic expression, yes. please compare it with normal case, otherwise open a bug
