### ISSUE TITLE
[ISSUE] Provider bug: impossible to create a single node cluster (num_workers = 0 is ignored)

### ISSUE THREAD

**Issue by evaimitico** [databrickslabs/terraform-provider-databricks#378]
### Terraform Version
Terraform v0.13.2

### Affected Resource(s)
- databricks_cluster

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

variable "subscription_id" {
  description = "subscription id to be used by azurerm"
}

variable "tenant_id" {
  description = "tenant id (Azure AD) to be used by azurerm"
}

variable "client_id" {
  description = "The client id of the service principal to be used by AKS"
}

variable "client_secret" {
  description = "The client secret of the service principal to be used by AKS"
}

provider "azurerm" {
  # The "feature" block is required for AzureRM provider 2.x. 
  # If you are using version 1.x, the "features" block is not allowed.
  version         = "~>2.6.0"
  client_id       = var.client_id
  client_secret   = var.client_secret
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
  features {}
}

provider "databricks" {
  alias = "dbs"
}

terraform {
  required_providers {
    databricks = {
      source  = "databrickslabs/databricks"
      version = "0.2.5"
    }
    azurerm = {
      source = "hashicorp/azurerm"
    }
  }

  required_version = ">= 0.13.0"

}

resource "databricks_cluster" "test" {
  cluster_name            = "test"
  spark_version           = "7.2.x-scala2.12"
  node_type_id            = "Standard_DS3_v2"
  driver_node_type_id     = "Standard_DS13_v2"

  autotermination_minutes = 30

  num_workers = 0

  idempotency_token = "clusterindex2" 

  enable_elastic_disk = true

  custom_tags = {"ResourceClass": "SingleNode"}

  spark_env_vars = {
      "PYSPARK_PYTHON": "/databricks/python3/bin/python3"
  }

  spark_conf = {
      "spark.databricks.cluster.profile": "singleNode",
      "spark.master": "local[*]"
  }

}

```

### Expected Behavior
terraform should be able to create a single node cluster on Azure Databricks (with 0 workers), since it's possible to do it from UI.

### Actual Behavior
When doing terraform apply, i got the following error:
Error: Missing required field: size
Please consult API docs at https://docs.databricks.com/dev-tools/api/latest/clusters.html#create for details.

In the documentation, this kind of error is raised when **num_workers** field is missing

In my cluster definition in terraform i specified num_workers = 0 , but the provided removed this field when serializing to json

Looking at the source code, in compute/model.go at line 231 and line 263 i see

> NumWorkers                int32              `json:"num_workers,omitempty"`

i'm not expert in Go, but i think omitempty is wrong for NumWorkers, because even if the value is 0 this attribute should be present in the json

### Steps to Reproduce
1. `terraform init`
1. `terraform apply`

**Comment by nfx** [comment]
There's PR #375 for this issue already

**Comment by evaimitico** [comment]
nfx, thanks for pointing me to that PR. I'll wait for the moment it will be merged.
