### ISSUE TITLE
[ISSUE] Allow to consume only N items from the Events API

### ISSUE THREAD

**Issue by alexott** [databrickslabs/terraform-provider-databricks#380]
Right now, `cluster.Events` call specifies the limit, but still collects all events from the REST API, as the `limit` parameter specifies the number of the items per page, not the total limit.  It would be useful to add a parameter to the call that will specify the maximal number of events to retrieve...

**Comment by nfx** [comment]
@alexott technically we just need the last state, correct? maybe we can simplify the code just to return the first page.

**Comment by alexott** [comment]
Yes, that's what I want to implement - current implementation is generic, planned for future use.
