### ISSUE TITLE
[ISSUE] Submit multiple (jar/python) jobs to cluster. 

### ISSUE THREAD

**Issue by MarekLani** [databrickslabs/terraform-provider-databricks#387]
Based on the documentation one can invoke Spark submit tasks only on new clusters (https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/job#spark_submit_task-configuration-block). 

This would mean it is possible to create only one jar or python based job on the cluster, as one cannot reference existing cluster id. 

Maybe my understanding of documentation is not correct, but if it is, it is quite strong downside of the the provider. It should provide a way how to deploy multiple jobs to the cluster.

### Affected Resource(s)
- databricks_job

### Expected Behavior
It should be possible to deploy multiple python/jar based jobs to the cluster

**Comment by stikkireddy** [comment]
@MarekLani can you describe how you want to configure the resource. This provider is based on the capabilities of the databricks platform and rest api: https://docs.databricks.com/dev-tools/api/latest/jobs.html#jobs-api. If you can show me how you want to configure the resource via an example and indicate whether the api can support that it would be a way forward to include that in the provider. But AFAIK and can see in the jobs api, there is no way to configure multiple "tasks" in one job. This will remain that way till the REST resource can support that.

**Comment by MarekLani** [comment]
@stikkireddy thank you for your response. I might have done more due diligence on the API side. Now I have understanding that actually it is usual practice to have one job per cluster when job is defined thru python files or jars. Closing this issue. Sorry for creating it prematurely.
