### ISSUE TITLE
[FEATURE] Support for Azure Managed Identity Authentication

### ISSUE THREAD

**Issue by yuri-tieto** [databrickslabs/terraform-provider-databricks#388]
Hello,

We are currently using Terraform through Managed Identity authentication, but looks like databricks provider does not support it. Is this possible to implement? Any workarounds that can be used?

**Comment by nfx** [comment]
@yuri-tieto i've seen references to Managed Identity Auth in ADAL, so technically it should be possible to add another "authorizer" here - https://github.com/databrickslabs/terraform-provider-databricks/blob/master/common/client.go#L59, which would be a variation of Service Principal auth. Right now it's called `configureWithClientSecret`, but has to be expanded, if MSI is used. I also foresee difficulties unit testing this. 

workaround 1 - can you assign any of the env variables from here? https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs#environment-variables

workaround 2 - ugly hack - create PAT token through external datasource:

https://registry.terraform.io/providers/hashicorp/external/latest/docs/data-sources/data_source#example-usage

```
data "external" "example" {
  program = ["python", "${path.module}/make-pat-for-workspace.py"]
  query = {
    resource_id = azurerm_databricks_workspace.this.id
  }
}
```

as always, PR's are welcome for functionality like this. we can work together to get this is.

**Comment by nfx** [comment]
In order to drive maintainer community efforts in a more focused way, closing this issue for now as there's not enough demand for it at the moment.
