### ISSUE TITLE
[ISSUE] Unable to create Cluster on GovCloud (Azure)

### ISSUE THREAD

**Issue by ganeshRajagopal** [databrickslabs/terraform-provider-databricks#391]
Hello,

Trying to use the Terraform provider agains the GovCloud  (Azure) and hitting issues while creating the cluster. The workspace is created successfully. The hard coding to point to Commercial cloud needs to be fixed so the provider can be used against govCloud.  

Affected Resource(s)
databricks_Cluster 
 
Steps to Reproduce
N/A

**Comment by nfx** [comment]
Hi @ganeshRajagopal , would you be able to PR in the changes? it's a simple one, in `azure_auth.go`

**Comment by nfx** [comment]
Stable implementation of this issue may require pulling in the same package, that is used by `azurerm` provider, otherwise i foresee more bugs down the line - https://github.com/hashicorp/go-azure-helpers (MPL 2.0)

**Comment by nfx** [comment]
@ganeshRajagopal  feature is released.
