### ISSUE TITLE
[DOC] How to Enable Workspace Access Control through Terraform Databricks Provider

### ISSUE THREAD

**Issue by dgray1k** [databrickslabs/terraform-provider-databricks#408]
I cannot see a way of setting Enable Workspace Access Control (https://docs.databricks.com/administration-guide/access-control/workspace-acl.html#enable-workspace-object-access-control) to be "on" using the terraform provider.

 Is this possible or am i missing something?

**Comment by nfx** [comment]
@dgray1k isn't it available for premium subscription workspaces by default? I'm seeing it enabled by default on all workspaces created.

> Access control is available only in the Premium plan (or, for customers who subscribed to Databricks before March 3, 2020, the Operational Security package).

**Comment by dgray1k** [comment]
@nfx You are absolutely correct. I was looking at a different workspace than created using my TF script doh. 

Long day yesterday...
