### ISSUE TITLE
Unable to import databricks_secret

### ISSUE THREAD

**Issue by saguziel** [databrickslabs/terraform-provider-databricks#409]
### Terraform Version
0.13.5, provider version 0.2.7, 0.2.8

### Affected Resource(s)
databricks_secret

### Expected Behavior
Import succeeds when running terraform import as described in the docs

### Actual Behavior
The following output `Error: resource databricks_secret doesn't support import`

### Steps to Reproduce
Try importing a databricks secret

**Comment by nfx** [comment]
Will be fixed in #415 along with few other resources.

**Comment by nfx** [comment]
Should be fixed on current master
