### ISSUE TITLE
Advanced admin configuration at cluster or workspace creation level

### ISSUE THREAD

**Issue by stanbiryukov** [databrickslabs/terraform-provider-databricks#410]
Is there a way to enable advanced databricks settings at the terraform resource level? For example, I don't see an option to enable container services, web terminal etc in any of the modules. It might make sense to add those types of options under "azurerm_databricks_workspace". Specifically, I can't deploy a databricks environment with a Docker image in one step. I need to first deploy the workspace, then navigate to advanced settings within Databricks to enable container services, and then I can deploy my terraform "databricks_cluster" module with a docker image.

**Comment by nfx** [comment]
@stanbiryukov it's possible through https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/workspace_conf, but the exact names of advanced feature toggles are not public at the moment. Please contact your Databricks representative and describe the use-case.
