### ISSUE TITLE
Auth type option for databricks_azure_adls_gen2_mount

### ISSUE THREAD

**Issue by stanbiryukov** [databrickslabs/terraform-provider-databricks#412]
It looks like the data lake mount module, `databricks_azure_adls_gen2_mount`, requires a service principal token. Is there a way to mount it with the storage account `primary_access_key` directly? Perhaps it can accept an `auth_type` option just like the `azure_blob_mount` module.

**Comment by nfx** [comment]
type option is not possible for adls_gen2 resources.
