### ISSUE TITLE
[DOC] Fix Typo In Doc

### ISSUE THREAD

**Issue by anthonyawuley** [databrickslabs/terraform-provider-databricks#413]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general Terraform questions, please see: https://www.terraform.io/community.html.
This template is for both adding enhancement as well as pointing out issues with the provider documentation.

### Affected Resource(s)
Link to the page with issues and a screenshot/description of what section has an issue.
Every doc page has anchor links for all the headings please post that here.

https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster#ebs_volume_type

### Expected Details
What are you expecting from the section that has an issue. If the section is missing anything that should be 
expected please point that out.

`ebs_volume_type - (Optional) The type of EBS volumes that will be launched with this cluster. Valid values are GENERAL_PURPOSE_SSD or THROUGHPUT_OPTIMIZED_HDD. Use this option only if you're not picking Delta Optinized i3.* node types.`
The above description mentions `Optinized` instead of `Optimized`

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] Change `Optinized` to `Optimized`

### Important Factoids
Any links to external documentation that may prove your case, i.e Databricks public docs or Terraform public docs. 

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #158

**Comment by nfx** [comment]
Fixed in #416
