### ISSUE TITLE
[ISSUE] Missing shell_command_task

### ISSUE THREAD

**Issue by sudeepgupta90** [databrickslabs/terraform-provider-databricks#431]
Hi Team,

This is an issue which spans across multiple repositories.
I have been using the Databricks Rest API for Jobs - [link](https://docs.databricks.com/dev-tools/api/latest/jobs.html#jobsettings)
This used to contain ShellCommandTask in the Job Settings API. It is no longer covered in the documentation.

ShellCommandTask is also a requirement for using MlFlow as shown in this code - [link to mlflow official repo](https://github.com/mlflow/mlflow/blob/master/mlflow/projects/databricks.py#L212)

I am using the terraform provider to provision my resources to migrate from the Rest API. Affected resources:
- databricks_job

`databricks_job` also doesn't have any support/argument for `shell_command_task`

My questions/issues are:

- ShellCommandTask documentation has been removed from the Databricks Jobs API. Is this no longer supported?
- Can we add `shell_command_task` to the terraform provider?
- How do I use Mlflow with terraform provider without `shell_command_task`?

This issue is blocking for us. Any help/clarity on this would be very much appreciated. 

Thanks!

**Comment by nfx** [comment]
Terraform integration works with *all supported* Public APIs, which is not the case for `shell_command_task`. We don't have any plans on adding it to terraform integration.
