### ISSUE TITLE
[FEATURE] AWS STS AssumeRole Mounts

### ISSUE THREAD

**Issue by WightmanVH** [databrickslabs/terraform-provider-databricks#436]
Hello,

I'm trying to use the databricks_aws_s3_mount syntax to reproduce the recommended AWS mount configuration here:

[Documentation > Databricks Workspace guide > Administration guide > Manage AWS Infrastructure > Secure access to S3 buckets across accounts using instance profiles with an AssumeRole policy](https://docs.databricks.com/administration-guide/cloud-configurations/aws/assume-role.html)

The SCALA code looks like this:
> dbutils.fs.mount("s3a://<s3-bucket-name>", "/mnt/<s3-bucket-name>",
>   extraConfigs = Map(
>     "fs.s3a.credentialsType" -> "AssumeRole",
>     "fs.s3a.stsAssumeRole.arn" -> "arn:aws:iam::<bucket-owner-acct-id>:role/MyRoleB",
>     "spark.hadoop.fs.s3a.canned.acl" -> "BucketOwnerFullControl",
>     "spark.hadoop.fs.s3a.acl.default" -> "BucketOwnerFullControl"
>   )
> )

My databricks_aws_s3_mount code looks like this:
> resource "databricks_aws_s3_mount" "mymount" {
>   instance_profile = "DatabricksXProfile"
>   s3_bucket_name = "s3X"
>   mount_name = "mountX"
>   extraConfigs = jsonencode(local.extraConfigsDatabricksS3)
> }
> 

The error that I see is -> An argument named "extraConfigs" is not expected here.

Thank you

**Comment by nfx** [comment]
Hi @WightmanVH ,

Please start your cluster with `"arn:aws:iam:::role/MyRoleB"` and then mount within it to achieve mount being available for all clusters with that instance profile (role). 

```
resource "databricks_instance_profile" "b" {
  instance_profile_arn = "arn:aws:iam:::role/MyRoleB"
  skip_validation      = false
}
resource "databricks_cluster" "this" {
  ...
  aws_attributes {
     instance_profile_arn = databricks_instance_profile.b.id
  }
}
resource "databricks_aws_s3_mount" "mymount" {
    cluster_id = databricks_cluster.this.id
    s3_bucket_name = "s3X"
    mount_name = "mountX"
}
```

What you're asking for is new feature of provider for additional configuration properties. I'm not convinced enough we need `extraConfigs` way, because we're directly specifying properties in provider.

Pull Requests are welcome, as always.

**Comment by WightmanVH** [comment]
My understanding is that these extra configs support the AssumeRole capability (additional to the databricks instance profile) needed because our S3 storage is in an separate AWS account.  I will test the suggested code to see if this works.  Thank you

**Comment by nfx** [comment]
most likely we'd need to refactor mounting data source semantics a bit. to start with, we should create single `databricks_mount` resource and coordinate how would it look like with @adriana-tufa and @bogdanghita-db. probably it should happen in few months. I don't really want to add more mounting options with hacks and aim for a generic solution.

**Comment by nfx** [comment]
Closing in favor of #497
