### ISSUE TITLE
[ISSUE] Minimal setup on master fails with internal error 

### ISSUE THREAD

**Issue by alexott** [databrickslabs/terraform-provider-databricks#438]
When debugging the data source for spark versions I've got an error with internal validation (provider is setup via `make install`) when running against Azure & configured with databricks-cli:

```
1 error occurred:
	* ConflictsWith: token references unknown attribute (basic_auth) at part (basic_auth)

1 error occurred:
	* ConflictsWith: token references unknown attribute (basic_auth) at part (basic_auth)

```

### Environment variable names

```
>env | sort | grep -E 'DATABRICKS|AWS|AZURE|ARM|TEST' | awk -F= '{print $1}'
```

### Terraform Configuration Files

minimal example from our documentation:

```hcl
terraform {
  required_providers {
    databricks = {
      source = "databrickslabs/databricks"
      version = "0.3.0"
    }
  }
}

provider "databricks" {
}

data "databricks_node_type" "smallest" {
  local_disk = true
}

resource "databricks_cluster" "shared_autoscaling" {
  cluster_name            = "Shared Autoscaling"
  spark_version           = "6.4.x-scala2.11"
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 20

  autoscale {
    min_workers = 1
    max_workers = 50
  }
}
```

### Debug Output

debug log is attached: [debug.log](https://github.com/databrickslabs/terraform-provider-databricks/files/5666959/1.log)

**Comment by nfx** [comment]
This should be fixed in #417

**Comment by alexott** [comment]
Ok, do you plan to merge it soon?

**Comment by nfx** [comment]
i can merge it, but acceptance tests are not fully rewritten. would you agree it's a good idea to merge with broken acceptance tests and work on those in separate PRs?

**Comment by alexott** [comment]
If master doesn’t work anyway (or it’s just my version), then I’m ok to work on tests in other PR...

—
