### ISSUE TITLE
[ISSUE] Failed cluster library dependencies are not cleaned up from error state 

### ISSUE THREAD

**Issue by heeroyuy925** [databrickslabs/terraform-provider-databricks#440]
### Terraform Version
terraform -v                                                                                                 
Terraform v0.13.3
+ provider registry.terraform.io/databrickslabs/databricks v0.2.9
+ provider registry.terraform.io/hashicorp/azuread v1.1.1
+ provider registry.terraform.io/hashicorp/azurerm v2.39.0

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_cluster

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Environment variable names
To get relevant environment variable _names_ please copypaste the output of the following command:
`$ env | sort | grep -E 'DATABRICKS|AWS|AZURE|ARM|TEST' | awk -F= '{print $1}'`

### Terraform Configuration Files
```local default config```

### Debug Output
2020-12-11T12:13:13.298+0800 [DEBUG] plugin.terraform-provider-databricks_v0.2.9: } <- GET /preview/scim/v2/Me
2020-12-11T12:13:13.314+0800 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"

Error: library_pypi[colorama=0.3.8] failed: java.lang.RuntimeException: ManagedLibraryInstallFailed: org.apache.spark.SparkException: Process List(/databricks/python/bin/pip, install, colorama=0.3.8, --disable-pip-version-check) exited with code 1. Invalid requirement: 'colorama=0.3.8'
= is not a valid operator. Did you mean == ?
 for library:PythonPyPiPkgId(colorama=0.3.8,None,None,List()),isSharedLibrary=false
library_pypi[lightgbm=2.3.1] failed: java.lang.RuntimeException: ManagedLibraryInstallFailed: org.apache.spark.SparkException: Process List(/databricks/python/bin/pip, install, lightgbm=2.3.1, --disable-pip-version-check) exited with code 1. Invalid requirement: 'lightgbm=2.3.1'
= is not a valid operator. Did you mean == ?
 for library:PythonPyPiPkgId(lightgbm=2.3.1,None,None,List()),isSharedLibrary=false
2020-12-11T12:13:13.319+0800 [DEBUG] plugin: plugin process exited: path=.terraform/plugins/registry.terraform.io/databrickslabs/databricks/0.2.9/darwin_amd64/terraform-provider-databricks_v0.2.9 pid=23183
2020-12-11T12:13:13.319+0800 [DEBUG] plugin: plugin exited
library_pypi[yaml] failed: java.lang.RuntimeException: ManagedLibraryInstallFailed: org.apache.spark.SparkException: Process List(/databricks/python/bin/pip, install, yaml, --disable-pip-version-check) exited with code 1.   Could not find a version that satisfies the requirement yaml (from versions: )
No matching distribution found for yaml
 for library:PythonPyPiPkgId(yaml,None,None,List()),isSharedLibrary=false

### Expected Behavior
The databricks cluster libraries could be updated

### Actual Behavior
At first I put the wrong value in cluster library with "=" the correct should be "==". When I try to update the value, whatever command as plan, apply, destroy, it still be broken by the libraries error. It seems the library block can not trigger the state diff action in databricks provider

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by nfx** [comment]
@heeroyuy925 ,

Interesting. State diff is there, but every time there’s a check for library status from platform. If there’s a failure in installing of one or more libraries - it’ll fail entire resource. Just because managed libraries are parts of the fully functioning specific cluster. 

To follow the logic with failed cluster/workspace cleanup, we should trigger uninstall of a library in case of failure to install it. Because libraries pending uninstalling are not affecting error state checks.

Volunteers and pull requests are always more than welcome.

**Comment by nfx** [comment]
@heeroyuy925 , for now as workaround, you have to manually go and remove failing library from cluster in user interface

**Comment by heeroyuy925** [comment]
Thanks you so much, I will use workaround first.
