### ISSUE TITLE
[FEATURE] Support for AWS IAM Passthrough

### ISSUE THREAD

**Issue by nfx** [databrickslabs/terraform-provider-databricks#444]
In order to enable IAM passthrough, we should enable creation of meta instance profiles. Include relevant documentation as well.

**Comment by nfx** [comment]
@psg2 willing to pick this one up and test it? `make test-awsmt` is the integration testing run.

**Comment by psg2** [comment]
> @psg2 willing to pick this one up and test it? `make test-awsmt` is the integration testing run.

I'm interested, but won't be a priority for some time as we don't use IAM Passthrough at Wildlife.
