### ISSUE TITLE
Instance pool keeps being recreated according to the zone_id

### ISSUE THREAD

**Issue by GwonsooLee** [databrickslabs/terraform-provider-databricks#459]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
Terraform v0.12.24
+ provider.aws v2.30.0
+ provider.databricks v0.2.8

Your version of Terraform is out of date! The latest version
is 0.14.4. You can update by downloading from https://www.terraform.io/downloads.html

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_instance_pool_nodes

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Environment variable names
To get relevant environment variable _names_ please copypaste the output of the following command:
`$ env | sort | grep -E 'DATABRICKS|AWS|AZURE|ARM|TEST' | awk -F= '{print $1}'`

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please add turn on logging, e.g. `TF_LOG=DEBUG terraform apply` and run command again, paste it to gist & provide the link to gist. If you're still willing to paste in log output, make sure you provide only relevant log lines with requests.

It would make it more readable, if you pipe the log through `| grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'`, e.g.:

```
TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
If I didn't change the value of databricks_instance_pool.aws_attributes.zone_id`, then it should not be replaced.

### Actual Behavior
What actually happened?
Even though I didn't change `databricks_instance_pool.aws_attributes.zone_id` value, but it keeps being recreated.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `set value of databricks_instance_pool.aws_attributes.zone_id to ""`
2. Then default zone_id will be applied.
3. After applying once, then plan once again.
4. Then you can see the recreated message

### Important Factoids
Are there anything atypical about your accounts that we should know?

**Comment by nfx** [comment]
This is a known issue. added the following in docs for next release:

-> **Note** *(AWS only)* Please specify empty configuration block (`aws_attributes {}`), even if you're not setting any custom values. This will prevent any resource update issues.
