### ISSUE TITLE
How to specify a managed resource group for databricks

### ISSUE THREAD

**Issue by mivano** [databrickslabs/terraform-provider-databricks#460]
Creating a databricks workspace works fine, however I m unable to find the correct way to specify the managed resource group. At the moment it will automatically create the `databricks-rg-` prefixed resource group, which is not in line with the naming convention used at my customer. 
In ARM I can specify the `managed-resource-group-id` and I m looking for a similar option in Terraform. 
I see some GitHub issues referring to the provider so I tried the below:

```
provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.databricks.id
  azure_workspace_name        = azurerm_databricks_workspace.databricks.name
  azure_resource_group        = azurerm_databricks_workspace.databricks.resource_group_name
  azure_managed_resource_group = azurerm_databricks_workspace.databricks.managed_resource_group_name
}
```

This fails with a 
```
Error: Unsupported argument

  on modules/cloud_modules/databricks/main.tf line 38, in provider "databricks":
  38:   azure_managed_resource_group = azurerm_databricks_workspace.databricks.managed_resource_group_name

An argument named "azure_managed_resource_group" is not expected here.
```

So what is the way to specify the managed resource group for databricks?

**Comment by nfx** [comment]
Hi @mivano managed resource group id takes no part in authentication process (e.g. it’s not part of azure resource id), therefore it doesn’t really belong to this provider. It may belong to AzureRM provider, so I’d suggest to file a ticket there. 

Please reply if you think it’s not the case :)

**Comment by mivano** [comment]
I m not sure where it belongs, but indeed it makes not a lot of sense in the authentication ticket. I tried following the steps as listed here: https://github.com/databrickslabs/terraform-provider-databricks/issues/223

Specifying it in the `resource "azurerm_databricks_workspace" ` or in the provider; both options wont work. So I m looking for some guidance how to specify the managed resource group. I cannot find any documentation expect how to use it as an output variable (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/databricks_workspace#managed_resource_group_id)

**Comment by nfx** [comment]
@mivano , #223 is no longer valid. Legacy `managed_resource_group` is removed. closing this issue
