### ISSUE TITLE
[ISSUE] Provider bug

### ISSUE THREAD

**Issue by ccapellan** [databrickslabs/terraform-provider-databricks#461]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.
Terraform v0.14.4
+ provider registry.terraform.io/databrickslabs/databricks v0.2.9
+ provider registry.terraform.io/hashicorp/azurerm v2.43.0
+ provider registry.terraform.io/hashicorp/external v2.0.0

### Affected Resource(s)
Please list the resources as a list, for example:
- all

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Environment variable names
To get relevant environment variable _names_ please copypaste the output of the following command:
not using env vars

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```
provider "azurerm" {
  version = "2.43.0"
  subscription_id = var.arm_subscription_id
  client_id       = var.arm_principal
  client_secret   = var.arm_password
  tenant_id       = var.tenant_id
  environment     = var.arm_environment
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
}

resource "azurerm_databricks_workspace" "cit_workspace" {
  name                = "${local.prefix_name}-Databricks"
  resource_group_name = module.rg_bi_data_warehouse.resource_group_name
  location            = var.resource_location
  sku                 = "standard"
}

provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.cit_workspace.id
}

resource "databricks_notebook" "notebook" {
  content = base64encode("# Welcome to your Python notebook")
  path = "/mynotebook"
  overwrite = false
  mkdirs = true
  language = "PYTHON"
  format = "SOURCE"
}

### Debug Output
Please add turn on logging, e.g. `TF_LOG=DEBUG terraform apply` and run command again, paste it to gist & provide the link to gist. If you're still willing to paste in log output, make sure you provide only relevant log lines with requests.

It would make it more readable, if you pipe the log through `| grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'`, e.g.:

```
TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
```

2021-01-19T15:19:44.257-0500 [WARN]  plugin.stdio: received EOF, stopping recv loop: err="rpc error: code = Unavailable desc = transport is closing"

2021-01-19T15:19:44.287-0500 [DEBUG] plugin: plugin process exited: path=.terraform/providers/registry.terraform.io/databrickslabs/databricks/0.2.9/windows_amd64/terraform-provider-databricks_v0.2.9.exe pid=12792
2021-01-19T15:19:44.287-0500 [DEBUG] plugin: plugin exited

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?
Notebook to be created

### Actual Behavior
What actually happened?
Receive following error:

Error: Response from server (404 Not Found) {"error":{"code":"SubscriptionNotFound","message":"The subscription '[removed]' could not be found."}}: json: cannot unmarshal object into Go struct field APIErrorBody.error of type string
(404 on /subscriptions/[removed]/resourceGroups/CIT-build2-BIDataWarehouse/providers/Microsoft.Databricks/workspaces/CIT-build2-Databricks)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
terraform apply plan.tf

Note: using Azure US Government cloud, and logged in using Azure CLI.

### Important Factoids
Are there anything atypical about your accounts that we should know?

**Comment by nfx** [comment]
@ccapellan are you sure this is provider bug and not an issue with your subscription id?

**Comment by ccapellan** [comment]
@nfx This is just a snippet of my codebase.  I'm successfully deploying other resources already using the Azure provider.  I have removed the real subscription id in this post.

**Comment by nfx** [comment]
but you're getting `SubscriptionNotFound` error in the logs... could you please cleanup the issue and add more logs to explain the behavior?

if it's govcloud, it'll be supported in upcoming 0.3.0 release - https://github.com/databrickslabs/terraform-provider-databricks/commit/1172ad60521eead56c40156a5bafd10c7ec3801e

**Comment by ccapellan** [comment]
@nfx it actually is govcloud.  Thanks for the update! I'll wait to test it with 0.3.0 version.

**Comment by nfx** [comment]
@ccapellan 0.3.0 released, please test it :)
