### ISSUE TITLE
[FEATURE] Custom docker images for clusters

### ISSUE THREAD

**Issue by nfx** [databrickslabs/terraform-provider-databricks#462]
Support launching clusters with custom docker images. Even though API supports it, there were no customers using it and fields were removed in [0.2.4](https://github.com/databrickslabs/terraform-provider-databricks/blob/master/CHANGELOG.md#024) refactoring. This fix should add struct field and unit test

**Comment by sdebruyn** [comment]
I'd be the first customer using this :)

**Comment by nfx** [comment]
@sdebruyn do you want to add it? :) it's as simple as ClusterInfo struct mod + new struct + unit test for job and cluster.

**Comment by sdebruyn** [comment]
@nfx Are you sure that it's not already in there? Maybe it's just not documented?

https://github.com/databrickslabs/terraform-provider-databricks/blob/7a0170342fca97a8455e3343754e1c108f8d80fb/compute/model.go#L250
and
https://github.com/databrickslabs/terraform-provider-databricks/blob/7a0170342fca97a8455e3343754e1c108f8d80fb/compute/model.go#L289

**Comment by sdebruyn** [comment]
Regardless of the answer to the question above: apparently this functionality is disabled by default in the workspace and has to be enabled by an admin. Since I'm managing 20+ workspaces, I'd like to do this automatically through Terraform. Is there an API for that as well?

**Comment by sdebruyn** [comment]
I don't have a Databricks Partner Team. It would be for internal use only. Should I contact Azure support for this?
