### ISSUE TITLE
[FEATURE] Add support for SAS Token Auth for ADLSv2 mounts

### ISSUE THREAD

**Issue by alexott** [databrickslabs/terraform-provider-databricks#463]
Newer [DBR versions](https://docs.databricks.com/release-notes/runtime/7.5.html#adls-gen-2-storage-connector-based-on-hadoop-33-for-abfs) include new implementation of the connector for ADLSv2 that supports [SAS tokens authentication](https://issues.apache.org/jira/browse/HADOOP-16730). It would be useful to support that in the terraform provider.

**Comment by nfx** [comment]
most likely we'd need to refactor mounting data source semantics a bit. to start with, we should create single `databricks_mount` resource and coordinate how would it look like with @adriana-tufa and @bogdanghita-db. probably it should happen in few months. I don't really want to add more mounting options with hacks and aim for a generic solution.

**Comment by alexott** [comment]
Agree on generic solution. I’ve filed it just not to forget about new option

**Comment by nfx** [comment]
@alexott shall you take on designing this resource and we discuss in a small group? :)

**Comment by nfx** [comment]
Closing in favor of #497
