### ISSUE TITLE
[ENHANCEMENT] Add option to force a set of credentials

### ISSUE THREAD

**Issue by CrowderKroger** [databrickslabs/terraform-provider-databricks#473]
When the azurerm provider is configured for one use and the databricks provider for another, there should be an option to force a set of credentials instead of erroring.

```More than one authorization method configured: azure and token```

I understand that you cannot decide which to use for the user, so the error is valid. I would like an option to force_credentials = "token" (or something) so both providers can be used without having to break up a project or repo.

Note: The azurerm provider is configured using ARM_* environment variables.
```
provider "azurerm" {
  skip_provider_registration = "true"
  subscription_id                  = var.subscription-id
  features {}
}

provider "databricks" {
  host                        = var.databricks_host
  token                      = var.databricks_token
}
```

Results in:
```More than one authorization method configured: azure and token```

**Comment by nfx** [comment]
@CrowderKroger can you show how you configure both of the providers? maybe it's a quickfix (or change of config). not errorring may result in bigger confusion for users 🤷‍♂️

**Comment by CrowderKroger** [comment]
Yes, sorry for the lack of information and wrong label applied. I could not edit the labels after creation.

**Comment by nfx** [comment]
@CrowderKroger what exact ARM_* variables are set? 

and do you use Azure Databricks or AWS Databricks in your case? E.g. why don't you use AAD JWT tokens?...

you can explicitly disable any azure auth by setting all `azure_*` provider config properties to `""`.

**Comment by CrowderKroger** [comment]
These ARM variables are set:

```
ARM_CLIENT_ID: ""
ARM_CLIENT_SECRET: ""
ARM_SUBSCRIPTION_ID: ""
ARM_TENANT_ID: ""
```

Setting the azure_* properties may be a good workaround

**Comment by CrowderKroger** [comment]
Updating our provider to the following allows a successful plan with both azurerm and databricks configured:

```
provider "databricks" {
  azure_workspace_resource_id = var.azure_workspace_resource_id 
  host                        = var.databricks_host
  token                       = var.databricks_token
  azure_subscription_id       = ""
  azure_client_secret         = ""
  azure_client_id             = ""
  azure_tenant_id             = ""
}
```

**Comment by CrowderKroger** [comment]
So, that got us to be able to use the provider, but when calling a resource; I get the same error.  I don't see where it checks the credentials twice, so I am confused.

```
provider "databricks" {
  azure_workspace_resource_id = var.azure_workspace_resource_id 
  host                        = var.databricks_host
  token                       = var.databricks_token
  azure_subscription_id       = ""
  azure_client_secret         = ""
  azure_client_id             = ""
  azure_tenant_id             = ""
}

data "databricks_node_type" "smallest" {
  local_disk = true
}

data "databricks_spark_version" "latest_lts" {
  long_term_support = true
}

resource "databricks_cluster" "shared_autoscaling" {
  cluster_name            = "Shared Autoscaling"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 20
  autoscale {
    min_workers = 1
    max_workers = 50
  }
}```

Results in:
```More than one authorization method configured: azure and token```

**Comment by CrowderKroger** [comment]
I think I found the issue ... if anything azure_* is set it throws the error. So we have to move azure_workspace_resource_id to an environment variable. Surely there is an easier way?

**Comment by nfx** [comment]
@travis-crowder-kr this was recently implemented in https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs#auth_type
