### ISSUE TITLE
[ISSUE] add extra_configs / param to databricks_aws_s3_mount

### ISSUE THREAD

**Issue by ebarault** [databrickslabs/terraform-provider-databricks#474]
Hi there,

### Terraform Version
0.14

### Affected Resource(s)
databricks_aws_s3_mount

Hi,
as per the doc of the resource 
https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/aws_s3_mount

the databricks_aws_s3_mount resource does not support the extra_configs param of the related dbutils.fs.mount() command

In particular I use the extra_configs param to configure the IAM role to use to mount the bucket:

```
extra_configs = {
  "fs.s3a.credentialsType" : "AssumeRole",
  "fs.s3a.stsAssumeRole.arn" : ASSUME_ROLE,
  "spark.hadoop.fs.s3a.canned.acl" : "BucketOwnerFullControl",
  "spark.hadoop.fs.s3a.acl.default" : "BucketOwnerFullControl"
}
```

cc:@fouadchamoun

**Comment by nfx** [comment]
most likely we'd need to refactor mounting data source semantics a bit. to start with, we should create single `databricks_mount` resource and coordinate how would it look like with @adriana-tufa and @bogdanghita-db. probably it should happen in few months. I don't really want to add more mounting options with hacks and aim for a generic solution.

**Comment by nfx** [comment]
Closing in favor of #497
