### ISSUE TITLE
[DOC] databricks_notebook data source requires format

### ISSUE THREAD

**Issue by abij** [databrickslabs/terraform-provider-databricks#483]
Hi there,

The resource databricks_notebook requires the field **format**, but is not reflected in the docs.

Docs:
https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/data-sources/notebook

Source:
https://github.com/databrickslabs/terraform-provider-databricks/blob/94bd7c4810e6952413f4738d40bc95a33b374e12/workspace/data_notebook.go#L22

**Comment by nfx** [comment]
@abij thanks for mentioning this! just in case - which format do you export it with in terraform workflow?

**Comment by abij** [comment]
Not sure, we use plain `terraform apply`.

**Comment by nfx** [comment]
i mean - how do you use the result of this data source output? i can get GoDataDriven guys a 30-60-minute deep-dive on usage of it all, btw.

**Comment by abij** [comment]
He Serge,

At the moment I have a simple setup and databricks in the ‘end result’
Output from the Workspace (azurerm) into Databricks provider.
We use some mounts blob + gen2 and following the Guide/workspace-management. It’s great.

It would be awesome if you can do a deep-dive about this provider!
I see/remembered you speaking at GoDataFest. We have XKE (XebiaKnowledgeSharing) at Tuesday 9th.

Maybe 14:30-15:00 suits you. (I reserved a virtual spot)
https://xke.xebia.com/event/2021-02-09/3596/databricks-terraform-provider

You can reach me directly using firstname+lastname @ company.com

--
Alexander Bij
