### ISSUE TITLE
[ISSUE] Uses `.databrickscfg` instead of env variables

### ISSUE THREAD

**Issue by bramrodenburg** [databrickslabs/terraform-provider-databricks#485]
When environment variables are used for authentication, and basic authentication is set in `provider "databricks"`, and credentials are specified for the DEFAULT profile in `.databrickscfg`, then the provider will use the configuration from `.databrickscfg` instead of config specified in the environment variables.

`$ env | sort | grep -E 'DATABRICKS|AWS|AZURE|ARM|TEST' | awk -F= '{print $1}'`
```
DATABRICKS_ACCOUNT_ID
DATABRICKS_DEBUG_HEADERS
DATABRICKS_HOST
DATABRICKS_PASSWORD
DATABRICKS_USERNAME
```

**Comment by nfx** [comment]
@bramrodenburg can you build from source the referenced PR and try reproducing?
