### ISSUE TITLE
[FEATURE] Support Azure Key Vault secret scope

### ISSUE THREAD

**Issue by mikemowgli** [databrickslabs/terraform-provider-databricks#49]
**Is your feature request related to a problem? Please describe.**
It is not supported creating a secret scope backed by Azure Key Vault at the moment

**Describe the solution you'd like**
An extra setting in a `databricks_secret_scope` resource to link with an Azure Key Vault

**Describe alternatives you've considered**
Only alternative so far is using a databricks backed secret scope.

**Comment by lawrencegripper** [comment]
Would be great to see this feature too. 

Is this doable at the moment? I'd look at this myself via another route and the docs suggested it was only configurable via the UI

**Comment by stikkireddy** [comment]
Currently key vault is not supported via rest apis.

**Comment by mikemowgli** [comment]
Hi, i gave it a try and was actuallt able to create an Azure Key Vault backed Databricks secret scope with:
`curl -iL -X POST --data @create-secret-scope-body.json -H 'Host: adb-redacted.4.azuredatabricks.net' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'X-Databricks-Org-Id: 510<redacted>04' -H 'X-CSRF-Token: <redacted>' -H 'X-Requested-With: XMLHttpRequest' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Origin: https://adb-<redacted>.4.azuredatabricks.net' -H 'Referer: https://adb-<redacted>.4.azuredatabricks.net/?o=<redacted>' -H 'x-forwarded-port: 443' -H 'Cookie: workspace-url=adb-<redacted>.4.azuredatabricks.net; JSESSIONID=auth-auth-<redacted>2ijrd03wi.webapp-cons-webapp-6' 'https://adb-<redacted>.4.azuredatabricks.net/ajax-api/2.0/secrets/scopes/create'`

the body being:
`cat create-secret-scope-body.json
{"scope":"testmb2","initial_manage_acl":null,"initial_manage_principal":null,"scope_backend_type":2,"backend_azure_keyvault":{"resource_id":"/subscriptions/<REDACTED_FOR_GITHUB>/resourceGroups/whatever/providers/Microsoft.KeyVault/vaults/whateverkeyvault","dns_name":"https://whateverkeyvault.vault.azure.net/"},"is_databricks_managed":null,"encrypt_with_customer_key":null}`

Could this help to support the feature?

**Comment by stikkireddy** [comment]
I believe this is the webform http request, unfortunately this is not supported via api and those types of requests are potentially subject to change. I am a bit averse in attempting to add stuff not supported by rest api to this provider as I wont be able to get support internally on breaking changes if they are not part of the API. But I will also let other folks weigh in. Generating the session cookie would also effect the way the provider is getting configured. Let me verify internally if this is on the roadmap to the API as that way we do not need to worry about making the session and saving the cookie with the client.

**Comment by rafaelpierre** [comment]
This would help a lot. Currently this is one of the only manual steps in any Databricks Workspace deployment that we have.

**Comment by sdebruyn** [comment]
> Hi,
> I gave it a try and was actually able to create an Azure Key Vault backed Databricks secret scope with:
> `curl -iL -X POST --data @create-secret-scope-body.json -H 'Host: adb-redacted.4.azuredatabricks.net' -H 'Accept: application/json, text/javascript, */*; q=0.01' -H 'X-Databricks-Org-Id: 510<redacted>04' -H 'X-CSRF-Token: <redacted>' -H 'X-Requested-With: XMLHttpRequest' -H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' -H 'Origin: https://adb-<redacted>.4.azuredatabricks.net' -H 'Referer: https://adb-<redacted>.4.azuredatabricks.net/?o=<redacted>' -H 'x-forwarded-port: 443' -H 'Cookie: workspace-url=adb-<redacted>.4.azuredatabricks.net; JSESSIONID=auth-auth-<redacted>2ijrd03wi.webapp-cons-webapp-6' 'https://adb-<redacted>.4.azuredatabricks.net/ajax-api/2.0/secrets/scopes/create'`
> 
> the body being:
> `cat create-secret-scope-body.json {"scope":"testmb2","initial_manage_acl":null,"initial_manage_principal":null,"scope_backend_type":2,"backend_azure_keyvault":{"resource_id":"/subscriptions/<REDACTED_FOR_GITHUB>/resourceGroups/whatever/providers/Microsoft.KeyVault/vaults/whateverkeyvault","dns_name":"https://whateverkeyvault.vault.azure.net/"},"is_databricks_managed":null,"encrypt_with_customer_key":null}`
> 
> Could this help supporting the feature?
> 
> EDIT: typo

I also agree that it would be better to have an API endpoint to set this up. However, as a temporary workaround, I was wondering how I can use your solution. Where did you get the redacted values from? Like the CSRF token, the JSESSIONID etc.

**Comment by mikemowgli** [comment]
Developer mode in Chrome. I didn't do further reverse engineering...

**Comment by rafaelpierre** [comment]
Any news on this? This looks like something so simple to and valuable... would make a lot of sense of at least have in the roadmap

**Comment by stikkireddy** [comment]
@rafaelpierre at this time no, there is no rest api support for this at this point in time

**Comment by nfx** [comment]
trimming down the number of open issues and closing this one until backend will support it.
