### ISSUE TITLE
[ISSUE] Provider bug: preloaded_spark_versions (type list) allows only 1 version

### ISSUE THREAD

**Issue by abij** [databrickslabs/terraform-provider-databricks#493]
### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_instance_pool

### Expected Behavior
Since it's a list I want to have at least 2 versions of spark.
In my case: Latest-LTS _(no autocomplete, sigh...)_ and latest stable

### Actual Behavior
Validation error: `must be less than or equal to 1 images. Preloading too many images slows down cluster start time.`

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` (terraform plan does not catch this exception)

It's also not allowed through the UI, so maybe change into a field, instead of list.

Greetings, Alexander & Robert

**Comment by alexott** [comment]
please execute `TF_LOG=debug terraform apply 2>&1 |tee debug.log` and attach the log.  It could be a change in the API behavior, because [API spec](https://docs.databricks.com/dev-tools/api/latest/instance-pools.html#request-structure) shows that as an array of strings.

**Comment by nfx** [comment]
@abij you can have "latest LTS" autocomplete, but the terraform way: https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/data-sources/spark_version#long_term_support, thanks to @alexott .

**Comment by abij** [comment]
My point is, the Databricks UI notebooks do not have autocomplete for the 7.3 runtime version, which is the LongTimeSupport version.... 

![image](https://user-images.githubusercontent.com/1022013/107502637-33504900-6b99-11eb-941c-5e2afb160168.png)

I'm using the data element to select Runtimes, works great!

```
data "databricks_spark_version" "latest_lts" {
  long_term_support = true
}

data "databricks_spark_version" "latest_stable" {
  long_term_support = false
  beta = false
}
```


From the debug logs:
```
2021-02-10T12:12:37.145+0100 [DEBUG] plugin.terraform-provider-databricks_v0.3.0: POST /instance-pools/create {
  "enable_elastic_disk": true,
  "idle_instance_autotermination_minutes": 180,
  "instance_pool_name": "SmallNodes",
  "max_capacity": 5,
  "node_type_id": "Standard_F4s_v2",
  "preloaded_spark_versions": [
    "7.6.x-scala2.12",
    "7.3.x-scala2.12"
  ]
}: timestamp=2021-02-10T12:12:37.144+0100
2021-02-10T12:12:37.941+0100 [INFO]  plugin.terraform-provider-databricks_v0.3.0: 400 Bad Request {
  "error_code": "INVALID_PARAMETER_VALUE",
  "message": "'preloaded_spark_versions' must be less than or equal to 1 images. Preloading too many images sl... (28 more bytes)"
}: timestamp=2021-02-10T12:12:37.941+0100
2021/02/10 12:12:37 [DEBUG] module.databricks.databricks_instance_pool.small_nodes_pool: apply errored, but we're indicating that via the Error pointer rather than returning it: 'preloaded_spark_versions' must be less than or equal to 1 images. Preloading too many images slows down cluster start time.
Please consult API docs at https://docs.databricks.com/dev-tools/api/latest/instance-pools.html#create for details.
```

**Comment by abij** [comment]
I see that it is described in the API, so it's not a bug from TF provider.

- **preloaded_spark_versions**: A list with _at **most** one runtime version_ the pool installs on each instance. Pool clusters that use a preloaded runtime version start faster as they do have to wait for the image to download. You can retrieve a list of available runtime versions by using the Runtime versions API call.
- **preloaded_docker_images** | An array of DockerImage | A list with _at **least** one Docker image_ the pool installs on each instance. Pool clusters that use a preloaded Docker image start faster as they do have to wait for the image to download. Available only if your account has Databricks Container Services enabled.

**Comment by nfx** [comment]
@abij i see that yesterday's session did have a positive effect :) i'm curious about the feedback.
