### ISSUE TITLE
[FEATURE] Support Git Integration

### ISSUE THREAD

**Issue by mikemowgli** [databrickslabs/terraform-provider-databricks#50]
**Is your feature request related to a problem? Please describe.**
It is not supported to configure the git integration of notebooks in terraform (at least, on Azure Databricks)

**Describe the solution you'd like**
Ability to define git integration for a notebook in the `databricks_notebook` resource.

**Describe alternatives you've considered**
In Azure Databricks (not sure about other flavors), need to manually configure git repo in the notebook UI.

**Comment by lawrencegripper** [comment]
I'd be happy to look at building out a PR for this feature. Is there an API endpoint that allows this to be configured?

**Comment by stikkireddy** [comment]
@mikemowgli There is currently no api to support git integration via rest api for this at this point in time.

**Comment by nfx** [comment]
This issue won't fix in the nearest future, so closing this for now.

**Comment by shan0809** [comment]
bumping this up, if there are any plans to include API  to integrate Azure databricks with Azure DevOps git automatically via API rather than manually

**Comment by alexott** [comment]
@ shan0809 there is no **official** API yet, that's why it's not implemented
