### ISSUE TITLE
[ISSUE] DocumentationURL fn prints wrong URL for token resource

### ISSUE THREAD

**Issue by nirav24** [databrickslabs/terraform-provider-databricks#501]
Sorry If this is very trivial issue.

I see the code https://github.com/databrickslabs/terraform-provider-databricks/blob/b7216353017eecb2de615bbf17e6a89283be640f/common/http.go#L82 which populate URL to Databricks official documentation on API errors.

This code is broken for **Token** resource. The reason is the difference between API endpoint and official docs link.

API Endpoint is `/token/ACTION` while official docs uses [tokens.html](https://docs.databricks.com/dev-tools/api/latest/tokens.html)#ACTION

Another one would be [account](https://docs.databricks.com/dev-tools/api/latest/account.html)

**Comment by nfx** [comment]
Unfortunately, this won’t fix. Most likely we’ll just remove doc links later.
