### ISSUE TITLE
[DOC] Issue Short Description

### ISSUE THREAD

**Issue by cegladanych** [databrickslabs/terraform-provider-databricks#503]
Hi 
I have an issue with terraform documentation relating to [databricks_cluster_resource](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster)

I am trying to get jar from Azure Artifacts but there is on details on documentation what the format of the coordinates should be. There is only an example of external packages. What coordinates format should be for Azure Artifact or AWS CodeArtifact

library {
  maven {
    coordinates = "com.amazon.deequ:deequ:1.0.4"
    // exlusions block is optional
    exclusions = ["org.apache.avro:avro"]
  }
}

**Comment by nfx** [comment]
@cegladanych try `repo` field:

https://github.com/databrickslabs/terraform-provider-databricks/blob/master/compute/model.go#L587

no custom auth is supported, so make sure you have open network access through endpoints.

**Comment by nfx** [comment]
@cegladanych https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster#library-configuration-block it was specified in docs. 

> You can also optionally specify a **repo parameter for custom Maven-style repository**, that should be accessible without any authentication for the network that cluster runs in. It can even be properly configured maven s3 wagon, AWS CodeArtifact or Azure Artifacts.
