### ISSUE TITLE
[Feature Request] Notebook cant identify differences

### ISSUE THREAD

**Issue by stikkireddy** [databrickslabs/terraform-provider-databricks#523]
Hi there,

There is an issue with notebooks. Accidental deletes from the remote environment are not identified as differences in terraform plan.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_notebook

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` with notebook resource
2. Delete a cell in the databricks notebook in the workspace
3. Re run terraform apply
4. I should expect a change but terraform does not recognize the change.

**Comment by nfx** [comment]
https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/notebook#argument-reference

> Notebook on Databricks workspace would only be changed, if Terraform stage did change. This means that any manual changes to managed notebook won't be overwritten by Terraform, if there's no local change to notebook sources. Notebooks are identified by their path, so changing notebook's name manually on the workspace and then applying Terraform state would result in creation of notebook from Terraform state.
