### ISSUE TITLE
[ISSUE] Cannot Provision 'Single Node' Cluster

### ISSUE THREAD

**Issue by m1nkeh** [databrickslabs/terraform-provider-databricks#525]
Hi,

When I run the following code, a cluster is provisioned (no errors), but it is a `Standard` type.. even though the docs suggest this is the correct method to achieve a Single Node cluster

Terraform version: 0.14.6
Provider version: 0.3.0
Affected Resource: databricks_cluster

I upgraded to 0.3.0 at the suggestion of #411 , and https://github.com/databrickslabs/terraform-provider-databricks/pull/454

```
resource "databricks_cluster" "shared_exploratory_gpu" {
  cluster_name  = "gpu-cluster"
  spark_version = "7.3.x-gpu-ml-scala2.12" # 7.3 LTS ML w. GPU
  node_type_id  = "Standard_NC6s_v3"
  # num_workers  = 0

  spark_conf = {
    # Single-node
    "spark.databricks.cluster.profile" : "singleNode"
    "spark.master" : "local[*]"
  }
}
```

This then yields the following error in the config as shown below:

<img width="919" alt="image" src="https://user-images.githubusercontent.com/13475141/108259237-24e9ca80-7161-11eb-94ad-3aadae8d002b.png">

**Comment by nfx** [comment]
Uncomment num_workers = 0 and it should be working

**Comment by m1nkeh** [comment]
Hey @nfx, couple of things.. firstly thanks for the reply, very fast and much appreciated.

Secondly though, this is what it says on the terraform site (https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster#fixed-size-or-autoscaling-cluster) where it very clearly states that the `num_workers` value will default to 0 if not supplied

<img width="668" alt="image" src="https://user-images.githubusercontent.com/13475141/108266529-806c8600-716a-11eb-9e8a-611b58e52b2f.png">

The main thing though, how come you have closed this issue before I actually come back to say yay or nay to the solution working?

Spolier: Uncommenting `num_workers = 0` did not do the job as you suggested 🙃

**Comment by m1nkeh** [comment]
In an added twist, I was looking at the Json from the Databricks UI, and noticed a "custom tag" applied to the single node cluster I was creating in the portal..

This code actually did work as expected - should I raise a PR an update the doco?

```
resource "databricks_cluster" "shared_exploratory_gpu" {
  cluster_name            = "[SingleNode] Exploratory GPU"
  spark_version           = "7.3.x-gpu-ml-scala2.12" # 7.3 LTS ML w. GPU
  node_type_id            = "Standard_NC6s_v3"
  autotermination_minutes = 30

  spark_conf = {
    # Single-node
    "spark.databricks.cluster.profile" : "singleNode"
    "spark.master" : "local[*]"
  }

  custom_tags = {
    "ResourceClass" = "SingleNode"
  }
}
```

![image](https://user-images.githubusercontent.com/13475141/108268132-692e9800-716c-11eb-98a2-74a0290460a6.png)

**Comment by nfx** [comment]
@m1nkeh from the looks of your cluster config, you may find cluster policy interesting

**Comment by m1nkeh** [comment]
> @m1nkeh from the looks of your cluster config, you may find cluster policy interesting

oh?

**Comment by nfx** [comment]
@m1nkeh https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster_policy create a policy, assign it to users and they'll be able to create restricted exploratory clusters without bothering you :) don't forget to put strict autotermination and max_dbu restrictions.

**Comment by m1nkeh** [comment]
oo, that does sound like a nice option, i like - ty!
