### ISSUE TITLE
[ISSUE] Plan shows change for email_notifications block in databricks_job when not set

### ISSUE THREAD

**Issue by travisemichael** [databrickslabs/terraform-provider-databricks#530]
### Terraform Version
Terraform v0.14.6
+ provider registry.terraform.io/databrickslabs/databricks v0.3.0

### Affected Resource(s)
- databricks_job

### Environment variable names
None

### Expected Behavior
Plan shows no change between applies when email_notification block is not provided

### Actual Behavior
Plan shows a change for email_notifications between applies when email_notifications block is not provided
```
  # module.databricks_jobs["data_export"].databricks_job.job will be updated in-place
  ~ resource "databricks_job" "job" {
        id                        = "XXX"
        name                      = "XXX"
        # (6 unchanged attributes hidden)

      - email_notifications {
          - no_alert_for_skipped_runs = false -> null
          - on_failure                = [] -> null
          - on_start                  = [] -> null
          - on_success                = [] -> null
        }



        # (3 unchanged blocks hidden)
    }
```

### Steps to Reproduce
1. Create a databricks_job resource with no email_notifications block
2. run `terraform apply`
3. run `terraform plan` or `terraform apply` to see the plan with erroneous change

**Comment by nfx** [comment]
@travisemichael please include empty notification block, for now

**Comment by travisemichael** [comment]
@nfx yes I am using that workaround, I just didn't see this issue filed so I wanted to file it.
