### ISSUE TITLE
[FEATURE] Add support for Databricks on GCP

### ISSUE THREAD

**Issue by alexott** [databrickslabs/terraform-provider-databricks#531]
With the official preview of Databricks on GCP, it's necessary that terraform provider works with GCP as well - this should be done before official release. The task includes:
* making sure that all places with cloud-specific functionality are supporting GCP
* adding GCP-specific resources, for example, mount points

**Comment by nfx** [comment]
To keep number of open issues smaller, closing this one. Please open PRs for specific parts of it
