### ISSUE TITLE
[ISSUE] Global Init Script bug

### ISSUE THREAD

**Issue by Radaeld** [databrickslabs/terraform-provider-databricks#533]
**Terraform version:** 12.25
**Resource:** databricks_global_init_script

**Problem:** Regex does not allow spaces
For example: 
name = "my init script"

This results in the following error:
**Error**: invalid value for name (Name should match regex!)

Tried with the regex used in the code: ^[-a-zA-Z0-9_.]{1,100}$
and it seems it fails when spaces are passed

**Possible Regex Solution:** ^[-a-zA-Z0-9_. ]{1,100}$
(Just added a space between the dot and ]

**Comment by nfx** [comment]
@Radaeld you may open a PR with `^[a-zA-Z0-9_\-\. ]*$` regex :)
