### ISSUE TITLE
[DOC] SPOT_WITH_FALLBACK missing from aws_attributes documentation

### ISSUE THREAD

**Issue by subaduba** [databrickslabs/terraform-provider-databricks#546]
Hello,

On the documentation for **databricks_cluster** aws_attributes found at https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster#aws_attributes, the availability type of **SPOT_WITH_FALLBACK** is missing as an option. I found that it is in the code and works, but just missing from the documentation.

Thanks!
Subhash

**Comment by alexott** [comment]
I have a fix that will be submitted as part of another PR (will be submitted next week)

**Comment by nfx** [comment]
@alexott we can close this one, right?

**Comment by alexott** [comment]
fixed by #571
