### ISSUE TITLE
[ISSUE] Cannot remove Dataricks Workspace and Cluster at the same time

### ISSUE THREAD

**Issue by KSLiquid** [databrickslabs/terraform-provider-databricks#552]
### Terraform Version
0.14.7

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_cluster

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    databricks = {
      source  = "databrickslabs/databricks"
      version = "0.3.1"
    }
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.49.0"
    }
  }
}

provider "azurerm" {
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
    }
  }
  skip_provider_registration = true
}

locals {
  resourceCount = 1
}

resource "azurerm_databricks_workspace" "this" {
  name                = "dummy-db-demo-space-313"
  resource_group_name = "my-rg-name"
  location            = "westeurope"
  sku                 = "standard"
  count               = local.resourceCount
}

provider "databricks" {
  host                        = "https://${azurerm_databricks_workspace.this[0].workspace_url}/"
  azure_workspace_resource_id = azurerm_databricks_workspace.this[0].id
}

resource "databricks_cluster" "this" {
  cluster_name            = "myClusterName"
  spark_version           = "7.3.x-cpu-ml-scala2.12"
  node_type_id            = "Standard_DS3_v2"
  autotermination_minutes = 20
  autoscale {
    min_workers = 1
    max_workers = 3
  }
  count = local.resourceCount
}
```

### Debug Output
https://gist.github.com/KSLiquid/d9bac54f312b3d47021fde305b54b0c9

### Expected Behavior
When I set the resource count to 0, the resources should get deleted.

### Actual Behavior
I get the following error:
```
Error: Invalid index

  on main.tf line 37, in provider "databricks":
  37:   azure_workspace_resource_id = azurerm_databricks_workspace.this[0].id
    |----------------
    | azurerm_databricks_workspace.this is empty tuple
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Take the obove script and do. `terraform apply`
2. Set the local "resourceCount" to 0
3. again `terraform apply` -> you will get the error

### Possible Solution
The problem is that in this case the workspace info is unknown.
The workspace ID/URL should be stored in the state of the cluster resources.
This is e.g. how it is done in the azurerm provider with storage accounts and storage containers to solve that problem

**Comment by nfx** [comment]
hi @KSLiquid , please follow this guide https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/guides/azure-workspace#data-resources-and-authentication-is-not-configured-errors and put databricks resources in a separate module.

**Comment by KSLiquid** [comment]
@nfx Thanks for the fast reply! However, this does not solve the problem. I think the provider is not capable of handing the situation where the databricks workspace is provisioned via count.

I've put the resources in a seperate module like you said and attached the code to the issue.
Would be greaf if you can reopen it, thanks!

**Comment by nfx** [comment]
@KSLiquid what is the use-case of provisioning workspaces via count? i don't think it's a good idea to do that. Terraform doesn't know the URL of a workspace before it's actually provisioned and therefore it cannot fill in the proper configuration for the provider. it's not the plugin issue, it's the way how terraform works.

**Comment by KSLiquid** [comment]
@nfx We need a switch to enable/disable databricks depending on a variable. As far as I know terraform does not offer another solution to do that. With the azurerm provider it is completely possible.
