### ISSUE TITLE
[ISSUE] Provider bug

### ISSUE THREAD

**Issue by dkataria1990** [databrickslabs/terraform-provider-databricks#560]
Hi, 

I am not able to find documentation to authenticate the databricks provider with SPN and client certificate. On the docs page, these are the only schema options available: 
provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.this.id
  azure_client_id             = var.client_id
  azure_client_secret         = var.client_secret
  azure_tenant_id             = var.tenant_id
}

Could you please share if there is a way to use client certificate instead? 

Azurerm provider allows the following:

provider "azurerm" {
  subscription_id             = var.subscription_id
  client_id                   = var.spn_object_id
  client_certificate_path     = var.spn_client_certificate_path
  client_certificate_password = var.spn_client_certificate_password
  tenant_id                   = var.tenant_id
}

**Comment by nfx** [comment]
Current provider doesn’t support SP certificate auth. Feel free to open up pull request with implementation, tests and documentation updates.
