### ISSUE TITLE
[ISSUE] Multiple authentication methods

### ISSUE THREAD

**Issue by dsfrederic** [databrickslabs/terraform-provider-databricks#572]
### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v0.14.7
+ provider registry.terraform.io/databrickslabs/databricks v0.3.1
+ provider registry.terraform.io/hashicorp/azurerm v2.51.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks provider

### Expected Behavior
What should have happened?

```
provider "databricks" {
  alias                       = "azure_auth"
  azure_workspace_resource_id = module.azurerm_databricks_workspace.adb_resource_id
}


resource "databricks_token" "pat" {
  provider = databricks.azure_auth
  comment  = "Terraform Provisioning"
  // 100 day token
  lifetime_seconds = 8640000
}

provider "databricks" {
  alias = "token_auth"

  host  = module.azurerm_databricks_workspace.adb_host
  token = databricks_token.pat.token_value
}

resource "databricks_secret_scope" "kv" {
  name = "KRCG-KV-001"

  provider = databricks.token_auth
  keyvault_metadata {
    resource_id = module.azurerm_key_vault.kv_id
    dns_name    = module.azurerm_key_vault.kv_uri
  }
}
```

I expected it to use multiple providers side by side since I explicitly added aliases. 

### Actual Behavior
What actually happened?

```
Error: More than one authorization method configured: azure and token
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know?

**Comment by nfx** [comment]
@dsfrederic i think some of the environment variables are set, so you're getting this error.

**Comment by dsfrederic** [comment]
@nfx that's right! But I use these to authenticate another part of my terraform file.

**Comment by dsfrederic** [comment]
@nfx anyway the workaround I tried won't be working anyhow. 

I changed the auth method to NOT use environment variables. This way I was able to continue. 

BUT: to create an Azure Keyvault Backed Secret Scope I need this:  
````
Error: Scope with Azure KeyVault must have userAADToken defined!
```
 
Is there really no way to create KV backed secret scopes with some kind of service principal?

**Comment by nfx** [comment]
You can explicitly set those variables to empty strings in provider block.

AKV SPN auth is known limitation of the backend.
