### ISSUE TITLE
[ISSUE] Json Marshaling issue with symbols

### ISSUE THREAD

**Issue by stikkireddy** [databrickslabs/terraform-provider-databricks#574]
Hi there,

There is am issue with the json marshall implementation in the provider using the default encoding with `json.MarshalIndent ` of package "encoding/json". By default when marshaling a struct to json bytes/string all the following unicode symbols "<", ">", "&", U+2028, and U+2029 are escaped to "\u003c","\u003e", "\u0026", "\u2028", and "\u2029". This replacement can be disabled when using an Encoder, by calling SetEscapeHTML(false). Read more here: https://golang.org/pkg/encoding/json/.

This would impact notebook naming and cluster naming convention. This is also impacted in notebooks when encoding them in the url as we do not use params encode so both the post and read requests for the following HCL examples will fail with the 0.3.1 provider.

### Provider Version
0.3.1

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_cluster
- databricks_job
- databricks_notebook
- maybe others idk

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    databricks = {
      source = "databrickslabs/databricks"
      version = "0.3.1"
    }
  }
}

provider "databricks" {}

resource "databricks_notebook" "ddl" {
  source = "tf-test-python2.py"
  path = "/Users/...../Demo &%<> Demo/test"
  language = "PYTHON"
}

resource "databricks_notebook" "ddl1" {
  source = "tf-test-python2.py"
  path = "/Users/...../Demo &<> Demo/test"
  language = "PYTHON"
}

resource "databricks_notebook" "ddl2" {
  source = "tf-test-python2.py"
  path = "/Users/...../Demo %<> Demo/test"
  language = "PYTHON"
}
```

### Debug Output
Please add turn on logging, e.g. `TF_LOG=DEBUG terraform apply` and run command again, paste it to gist & provide the link to gist. If you're still willing to paste in log output, make sure you provide only relevant log lines with requests.

It would make it more readable, if you pipe the log through `| grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'`, e.g.:

post request:
```
2021-03-24T13:49:23.174-0400 [DEBUG] plugin.terraform-provider-databricks_v0.3.1: POST /workspace/import {
  "content": "**REDACTED**",
  "format": "SOURCE",
  "language": "PYTHON",
  "overwrite": true,
  "path": "/Users/...../Demo %\u003c\u003e Demo/test"
}: timestamp=2021-03-24T13:49:23.174-0400
```

get request:
```
/workspace/get-status?path=%2FUsers%2Fsri.tikkireddy@databricks.com%2FDemo%20&%3C%3E%20Demo%2Ftest
```

As you can see the post request has the path modified when it shouldnt be modified. And the get request does not escape the & symbol which indicates that it is another query parameter and should be encoded.

### Expected Behavior
The payload for the post should have the exact path described as indicated in the hcl.
The get request should have the "&" symbol encoded as well. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by alexott** [comment]
check 0.3.2 - it should be already fixed by #566
