### ISSUE TITLE
[ISSUE] AWS S3 Mount does not use cluster_id during plan

### ISSUE THREAD

**Issue by theesen** [databrickslabs/terraform-provider-databricks#585]
### Terraform Version
Terraform v0.12.30
+ provider.aws v3.32.0
+ provider.databricks v0.3.2

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_aws_s3_mount

### Terraform Configuration Files
```hcl
resource "databricks_aws_s3_mount" "generic" {
  for_each = toset(var.buckets)

  cluster_id       = "999"
  instance_profile = "some_instance_profile"
  s3_bucket_name   = each.key
  mount_name       = "data/${replace(each.key, "/[^0-9A-Za-z_]/", "_")}"
}
```

### Debug Output
```
  # module.mountpoints.databricks_aws_s3_mount.generic["com.my.bucket"] must be replaced
-/+ resource "databricks_aws_s3_mount" "generic" {
      ~ cluster_id       = "123" -> "999" # forces replacement
      ~ id               = "com.my.bucket" -> (known after apply)
        instance_profile = "arn:aws:iam::XXXXX:instance-profile/databricks-shared-instance-profile"
        mount_name       = "data/com.my.bucket"
        s3_bucket_name   = "com.my.bucket"
      ~ source           = "s3a://com.my.bucket" -> (known after apply)
    }

```
Cluster ID: `999` is the ID of the actual cluster I would like the mount to use, while `123` is the ID of a temporary cluster that is auto created by the terraform plan.

### Expected Behavior
Mounting should happen on the provided cluster_id during `terraform plan & apply`.

### Actual Behavior
A new cluster is being launched every time `terraform plan` is executed.

### Steps to Reproduce
1. Create a mountpoint using a cluster_id with terraform.
2. Rerun the same terraform plan without any changes.
3. Terraform will plan and apply the changes on a different cluster then specified (In my example on `123` instead of `999`)

**Comment by nfx** [comment]
will be fixed in #497
