### ISSUE TITLE
[ISSUE] Provider bug | missing required field validation

### ISSUE THREAD

**Issue by bofaalsarah** [databrickslabs/terraform-provider-databricks#591]
### Terraform Version

Terraform v0.12.30

    provider.aws v3.34.0
    provider.databricks v0.3.1

### Affected Resource(s)

    databricks_cluster_policy

### Terraform Configuration Files

```
resource "databricks_cluster_policy" "cluster_policy" {
  name = "Policy with submarine plugin"
  definition = jsonencode({
    "spark_conf.spark.sql.extensions": {
      "value": "org.apache.submarine.spark.security.api.RangerSparkSQLExtension"
    }
  })
}
```

### Expected Behavior

It should throws an error for the missing type parameter in `spark_conf.spark.sql.extensions` block

### Actual Behavior

Terraform plan is being applied but the cluster can't be launched due to the invalid policy

**Comment by nfx** [comment]
it's rather an issue with REST API, than provider. closing this one.
