### ISSUE TITLE
Exporter does not export AKV scopes properly

### ISSUE THREAD

**Issue by nfx** [databrickslabs/terraform-provider-databricks#594]
We should not fill in secret values with variables for AKV scopes. And we should make proper generation of AKV scope resource

**Comment by alexott** [comment]
Hmmm, I thought that I did that - maybe it was lost during the rebase/merge.  I should have corresponding patch somewhere

**Comment by alexott** [comment]
the first part should be covered by this: https://github.com/databrickslabs/terraform-provider-databricks/blob/master/exporter/importables.go#L555 - until dev team didn't change the name...
will fix tomorrow

**Comment by nfx** [comment]
did the AZURE_KEYVAULT constant change? this means that other AKV scopes are broken.

**Comment by alexott** [comment]
I couldn't reproduce this behaviour - I just re-run everything, and see that for AKV-based secret scopes we export only scope definition and scope ACL, but not the secrets...
