### ISSUE TITLE
[ISSUE] Provider bug: Creation of Azure Key Vault secret scope using Terraform Cloud

### ISSUE THREAD

**Issue by SebastianBalle** [databrickslabs/terraform-provider-databricks#595]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.14.10

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_secret_scope

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Environment variable names
No environment variables used as provisioned from Terraform Cloud. Using the following environment variables on Terraform Cloud:
* ARM_CLIENT_ID
* ARM_CLIENT_SECRET
* ARM_SUBSCRIPTION_ID
* ARM_TENANT_ID

### Terraform Configuration Files
```hcl
 # module.application.module.databricks.databricks_secret_acl.kv_acl[0] will be created
  + resource "databricks_secret_acl" "kv_acl" {
      + id         = (known after apply)
      + permission = "READ"
      + principal  = "data-scientists"
      + scope      = "AZURE_KEYVAULT"
    }

  # module.application.module.databricks.databricks_secret_scope.kv[0] will be created
  + resource "databricks_secret_scope" "kv" {
      + backend_type = (known after apply)
      + id           = (known after apply)
      + name         = "AZURE_KEYVAULT"

      + keyvault_metadata {
          + dns_name    = "(redacted)"
          + resource_id = "(redacted)"
        }
    }
```

### Debug Output

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # module.application.module.databricks.databricks_secret_acl.kv_acl[0] will be created
  + resource "databricks_secret_acl" "kv_acl" {
      + id         = (known after apply)
      + permission = "READ"
      + principal  = "data-scientists"
      + scope      = "AZURE_KEYVAULT"
    }

  # module.application.module.databricks.databricks_secret_scope.kv[0] will be created
  + resource "databricks_secret_scope" "kv" {
      + backend_type = (known after apply)
      + id           = (known after apply)
      + name         = "AZURE_KEYVAULT"

      + keyvault_metadata {
          + dns_name    = "(redacted)"
          + resource_id = "(redacted)"
        }
    }

Plan: 2 to add, 0 to change, 0 to destroy.
2021/04/15 14:09:19 [DEBUG] command: asking for input: "\nDo you want to perform these actions in workspace \"(redacted)\"?"

Do you want to perform these actions in workspace "(redacted)"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

Error: Azure KeyVault cannot yet be configured for Service Principal authorization

  on .terraform/modules/application/modules/databricks/main.tf line 25, in resource "databricks_secret_scope" "kv":
  25: resource "databricks_secret_scope" "kv" {

```

### Expected Behavior
The service principal should, with the use of Terraform Cloud, create the secret scope for Azure Key Vault and the acl for the secret scope. The Service Principal have admin permissions on the Key Vault. 

### Actual Behavior
The error: "Azure KeyVault cannot yet be configured for Service Principal authorization" is returned 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

Must be using Terraform Cloud with the user being a Service Principal.

### Important Factoids
It was possible to create this when using personal credentials for the deployment but when using a Service Principal it fails.

**Comment by nfx** [comment]
Azure KeyVault **cannot yet be configured** for Service Principal authorization. Currently you cannot create AKV scope because **_OBO flow is not supported yet for SPNs on AAD side_**. Please reach out to your Azure and Databricks representatives.
