### ISSUE TITLE
[DOC] New Workspace setup - Auth warning

### ISSUE THREAD

**Issue by felixsafegraph** [databrickslabs/terraform-provider-databricks#596]
### Affected Resource(s)
Auth

### Expected Details
```
│ Error: Accounts API (/api/2.0/accounts/xxx/credentials) requires you to set accounts.cloud.databricks.com as DATABRICKS_HOST, but you have specified https://dbc-xxx.cloud.databricks.com/ instead. This error may happen if you're using provider in both normal and multiworkspace mode. Please refactor your code into different modules. Runnable example that we use for integration testing can be found in this repository at https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/guides/aws-workspace
```

### List of things to potentially add/remove:

Doc should call out that if you have a .databrickscfg

you should rename/move the file - otherwise terraform will pick up the "wrong credentials"

**Comment by nfx** [comment]
@felixsafegraph, it is documented https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs#empty-provider-block

**Comment by felixsafegraph** [comment]
Is the doc describing a precedence? because in my setup I had user + pass (point 4) but the tool was using the databrickscfg anyway (and failed) (point 7)

this is not how I would expect it

**Comment by nfx** [comment]
@felixsafegraph precedence is as documented. 

> because in my setup I had user + pass (point 4)

I think you were missing the host?..

what i can advise is `TF_LOG=DEBUG terraform apply`(a bit verbose, so do grep on terraform-provider-databricks). I should give couple of hints.

**Comment by felixsafegraph** [comment]
not sure I understand. the exact same thing, it worked when I delete my .databickscfg file.

**Comment by nfx** [comment]
@felixsafegraph hm.. what env variables do you have and what does TF_LOG=DEBUG say?
