### ISSUE TITLE
Remove managed library that failed to install on refresh

### ISSUE THREAD

**Issue by nfx** [databrickslabs/terraform-provider-databricks#599]
Remove managed library that failed to install on refresh

**Comment by nfx** [comment]
how to reproduce: 

1. install the library that failed to install on a cluster
2. see TF apply end with the error
3. run apply again
4. see same installation error :(

**Comment by nfx** [comment]
@psg2 this might be interesting for you to look at

**Comment by psg2** [comment]
> @psg2 this might be interesting for you to look at

I will give a look into this next week.

Unrelated to the issue itself, but just found it interesting that the `terraform refresh` command is being deprecated. Ref: https://www.terraform.io/docs/cli/commands/refresh.html

**Comment by nfx** [comment]
@psg2 Refresh is more of a stage name, that calls Read callback of a resource

**Comment by nfx** [comment]
@psg2 do you still want to pick this one up?

**Comment by psg2** [comment]
I won't have time to do it soon so I won't make a compromise for now. ):
