### ISSUE TITLE
[DOC] spark_conf configuration example errors in terraform

### ISSUE THREAD

**Issue by capitancambio** [databrickslabs/terraform-provider-databricks#603]
Hey there's a typo/error in the examples involving `spark_conf` when terraform

### Affected Resource(s)

https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster#spark_conf

```
 spark_conf {
    "spark.databricks.io.cache.enabled": true,
    "spark.databricks.io.cache.maxDiskUsage": "50g",
    "spark.databricks.io.cache.maxMetaDataCache": "1g"
  }
```
That piece of config fails with terraform 0.13 with a `Argument names must not be quoted.`
### List of things to potentially add/remove:
The examples should read as
```
 spark_conf = {
    "spark.databricks.io.cache.enabled": true,
    "spark.databricks.io.cache.maxDiskUsage": "50g",
    "spark.databricks.io.cache.maxMetaDataCache": "1g"
  }
```
for them work

**Comment by nfx** [comment]
thanks @capitancambio , next release will have the fix
