### ISSUE TITLE
[ISSUE] databricks_notebook does not recognize changes made in workspace

### ISSUE THREAD

**Issue by jonathan-dorsey** [databrickslabs/terraform-provider-databricks#614]
### Terraform Version
0.13.5

### Provider Version
0.3.0

### Affected Resource(s)
- databricks_notebook

### Terraform Configuration Files
```hcl
resource databricks_notebook {
  source = "./notebook_file.scala"
  path   = "/test_notebook"
}
```

### Expected Behavior
When a notebook is deployed via the provider with content, it should recognize changes made to the file in the workspace to prevent configuration drift. When the terraform is applied after a change, it should revert the file contents back to the content specified in the terraform source.

### Actual Behavior
The state only compares the existing state to the new terraform code to determine if a change is necessary. Changes made within the workspace are not reverted or overwritten. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
2. Change the content of the notebook within the Databricks workspace
3. `terraform plan`
4. Notice no changes are listed in the plan

### Important Factoids
It appears this was considered in https://github.com/databrickslabs/terraform-provider-databricks/issues/183 but I can't tell if it was not supported intentionally.

**Comment by nfx** [comment]
@jonathan-dorsey Currently, workspace status backend APIs don't give any information If notebook was manually changed or not. Fetching remote notebook source creates certain issues, once many notebooks are being checked, so this route was deliberately moved away from.

And this is mentioned on documentation as known issue, for now. This may change in the future. Please stay tuned with upcoming releases.
