### ISSUE TITLE
[DOC] Issue Short Description

### ISSUE THREAD

**Issue by steve148** [databrickslabs/terraform-provider-databricks#616]
### Affected Resource(s)

https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/resources/instance_pool.md#aws_attributes-configuration-block

### Expected Details

Docs mention `zone_id` as being optional, but when trying to create an instance pool with the provider I ran into the following error.

```
Error: Missing required argument

  on main.tf line 33, in resource "databricks_instance_pool" "this":
  33:   aws_attributes {

The argument "zone_id" is required, but no definition was found.
```

Looking at the [resource file](https://github.com/databrickslabs/terraform-provider-databricks/blob/22cdf2fc9d50f67b14b49d11e7fbaacce0f52399/compute/resource_instance_pool.go#L90) and going through the databricks UI to create an instance pool, it seems as if the zone id is required. If that's the case, the docs should mention the field is required / not-optional.

### List of things to potentially add/remove:

Current definition of `zone_id` in `instance_pool.md` docs.

```
* `zone_id` - (Optional) (String) Identifier for the availability zone/datacenter in which the instance pool resides. This string is of a form like `"us-west-2a"`. The provided availability zone must be in the same region as the Databricks deployment. For example, `"us-west-2a"` is not a valid zone ID if the Databricks deployment resides in the `"us-east-1"` region. This is an optional field. If not specified, a default zone is used. You can find the list of available zones as well as the default value by using the [List Zones API](https://docs.databricks.com/dev-tools/api/latest/clusters.html#clusterclusterservicelistavailablezones).
```

What I think the docs should be.

```
* `zone_id` - (String) Identifier for the availability zone/datacenter in which the instance pool resides. This string is of a form like `"us-west-2a"`. The provided availability zone must be in the same region as the Databricks deployment. For example, `"us-west-2a"` is not a valid zone ID if the Databricks deployment resides in the `"us-east-1"` region. This is an optional field. If not specified, a default zone is used. You can find the list of available zones as well as the default value by using the [List Zones API](https://docs.databricks.com/dev-tools/api/latest/clusters.html#clusterclusterservicelistavailablezones).
```

### Important Factoids

-

### References

-

**Comment by nfx** [comment]
@steve148 could you please do another small PR to close this issue? :)

**Comment by steve148** [comment]
@nfx of course, was just about to say I don't mind.
