### ISSUE TITLE
[DOC] Token value is not available in output

### ISSUE THREAD

**Issue by tomarv2** [databrickslabs/terraform-provider-databricks#618]
Hi Team,

I was looking at this doc: https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/guides/aws-workspace#provider-configuration

### Expected Details
I was expecting `token_value` in output:

```
// export token for integration tests to run on
output "databricks_token" {
  value     = databricks_token.pat.token_value
  sensitive = true
}
```

I don't see `token_value` in output:

<img width="542" alt="Screen Shot 2021-04-28 at 2 24 29 PM" src="https://user-images.githubusercontent.com/11890959/116474640-9ca53700-a82d-11eb-9acb-3af61303b5fa.png">

**Comment by nfx** [comment]
this is the issue of intellij plugin
