### ISSUE TITLE
[ISSUE] databricks_sql_permissions causes perpetual plan changes

### ISSUE THREAD

**Issue by vynaloze** [databrickslabs/terraform-provider-databricks#619]
### Terraform Version
```
Terraform v0.14.10
+ provider registry.terraform.io/databrickslabs/databricks v0.3.3
```

### Affected Resource(s)
- databricks_sql_permissions

### Environment variable names
```
DATABRICKS_HOST
DATABRICKS_TOKEN
```

#### Case 1: "swapping groups"
```hcl
resource "databricks_sql_permissions" "database" {
  database = "test"

  privilege_assignments {
    principal = "data_admin"
    privileges = [
      "SELECT",
      "CREATE",
      "MODIFY",
      "USAGE",
      "READ_METADATA",
    ]
  }

  privilege_assignments {
    principal = "data_science"
    privileges = [
      "SELECT",
      "USAGE",
      "READ_METADATA",
    ]
  }

  privilege_assignments {
    principal = "data_read_only"
    privileges = [
      "SELECT",
      "USAGE",
      "READ_METADATA",
    ]
  }
}
```
#### Case 2: "catalog becomes database/default"
see #620 

#### Case 3: "ALL PRIVILEGES becomes all privileges listed"
```hcl
resource "databricks_sql_permissions" "database" {
  database = "test"

  privilege_assignments {
    principal  = "data_admin"
    privileges = ["ALL PRIVILEGES"]
  }
}
```

### Expected Behavior
No changes should be detected when running subsequent `plan`s after initial `apply`

### Actual Behavior
After initial `apply`, running `plan` produces following outputs, given configuration files above:

#### Case 1: "swapping groups"
```
  # databricks_sql_permissions.database will be updated in-place
  ~ resource "databricks_sql_permissions" "database" {
        id                 = "database/test"
        # (5 unchanged attributes hidden)

      ~ privilege_assignments {
          ~ principal  = "data_read_only" -> "data_admin"
          ~ privileges = [
              + "CREATE",
              + "MODIFY",
                # (3 unchanged elements hidden)
            ]
        }
      ~ privilege_assignments {
          ~ principal  = "data_admin" -> "data_read_only"
          ~ privileges = [
              - "CREATE",
              - "MODIFY",
                # (3 unchanged elements hidden)
            ]
        }
        # (1 unchanged block hidden)
    }
```
#### Case 2: "catalog becomes database/default"
see #620 

#### Case 3: "ALL PRIVILEGES becomes all privileges listed"
```
  # databricks_sql_permissions.database will be updated in-place
  ~ resource "databricks_sql_permissions" "database" {
        id                 = "database/test"
        # (5 unchanged attributes hidden)

      ~ privilege_assignments {
          ~ privileges = [
              + "ALL PRIVILEGES",
              - "CREATE",
              - "CREATE_NAMED_FUNCTION",
              - "MODIFY",
              - "READ_METADATA",
              - "SELECT",
              - "USAGE",
            ]
            # (1 unchanged attribute hidden)
        }
    }
```

### Steps to Reproduce
1. `terraform apply`
2. `terraform plan` (or `apply`, whatever)

### Important factoids
Of course, there may be more cases like that - I'm not a QA, I'm submitting cases that bug me now.

**Comment by nfx** [comment]
thank you for submitting the issue.

Case 3 won't fix. There's no way to validate lists in terraform in the moment.

Could you pull Case 2 into separate issue?

**Comment by vynaloze** [comment]
>Case 3 won't fix. There's no way to validate lists in terraform in the moment.
That's a shame. Can you maybe update the documentation to indicate that "ALL PRIVILEGES" permission is pretty much useless (unless anyone is fine with constant plan changes)?

>Could you pull Case 2 into separate issue?
Sure: #620.

**Comment by nfx** [comment]
> That's a shame. Can you maybe update the documentation to indicate that "ALL PRIVILEGES" permission is pretty much useless (unless anyone is fine with constant plan changes)?

yep, i'll just add a note in documentation.
