### ISSUE TITLE
Unable to create E2 workspace using terraform - MALFORMED_REQUEST

### ISSUE THREAD

**Issue by premjayaraj** [databrickslabs/terraform-provider-databricks#622]
Customer is deploying databricks workspace via terraform. Its throwing the below error saying,

"MALFORMED_REQUEST: Failed parameter validation checks: Deployment name cannot be used until a deployment name prefix is defined. Please contact your Databricks representative"

<img width="710" alt="Screen Shot 2021-04-29 at 6 18 25 PM" src="https://user-images.githubusercontent.com/66770956/116677075-64d0f780-a9c5-11eb-8453-c4092f13c4bc.png">
<img width="957" alt="Screen Shot 2021-04-29 at 6 37 37 PM" src="https://user-images.githubusercontent.com/66770956/116677085-68fd1500-a9c5-11eb-8df2-dbb717218c94.png">

**Comment by nfx** [comment]
@premjayaraj well, Databricks sales team has to be contacted to enable the deployment prefix :) this is not an issue of the provider, _Please contact your Databricks representative_ (as mentioned in the error message).
