### ISSUE TITLE
[ISSUE] Pool is not replaced on Spark version update

### ISSUE THREAD

**Issue by sdebruyn** [databrickslabs/terraform-provider-databricks#623]
I updated the preloaded_spark_versions of my instance_pool from 7.3 to 8.1 in 2 Terraform projects. In one of them it correctly indicated that it needed to replace the pool because this version had changed.

On the other one, it proposes an in-place update:

```
  # databricks_instance_pool.pool will be updated in-place
  ~ resource "databricks_instance_pool" "pool" {
        id                                    = "xxx-pool-xxx"
      ~ preloaded_spark_versions              = [
          - "7.3.x-scala2.12",
          + "8.1.x-scala2.12",
        ]
        # (7 unchanged attributes hidden)

        # (1 unchanged block hidden)
    }
```

If you apply this, you get
```
Error: Requested instance pool field change is not supported on existing pools: preloaded_spark_versions. Please check Databricks documentations to see which fields can be edited.
```

Provider version 0.3.2 and same with 0.3.3.
Terraform 0.14.6 on the broken one and Terraform 0.15.1 on the working one

**Comment by nfx** [comment]
@sdebruyn we'll just say, that you should use Terraform 0.15 :)

**Comment by sdebruyn** [comment]
@nfx same issue after update to 0.15.1
