### ISSUE TITLE
[ISSUE] databricks_service_principal:  application_id field is required by the provider but the API endpoint does not accept it

### ISSUE THREAD

**Issue by alafanechere** [databrickslabs/terraform-provider-databricks#630]
Hello,
I activated SCIM for service principal preview on the databricks AWS workspace I manage, but I fail at creating a service principal using your provider. 

It looks like their is an inconsistency between the provider implementation and your rest API : 
* The `application_id` field is required by the provider but is not expected by the REST API.
* It causes an HTTP `400` response and a final `Error: Request is unparsable, syntactically incorrect, or violates schema.` error in Terraform.

### Terraform Version
Terraform v0.14.10
+ provider registry.terraform.io/databrickslabs/databricks v0.3.3
+ provider registry.terraform.io/hashicorp/aws v3.38.0

### Affected Resource(s)

- databricks_service_principal

### Terraform Configuration Files
```hcl
resource "databricks_service_principal" "airflow" {
  application_id    = "00000000-1234-5678-0000-000000000001"
  display_name = "Airflow service principal"
  allow_cluster_create = true
}

```

### Debug Output

```
2021-05-03T16:05:10.333+0200 [DEBUG] plugin.terraform-provider-databricks_v0.3.3: 400 Bad Request {
  "detail": "Request is unparsable, syntactically incorrect, or violates schema.",
  "schemas": [
    "urn:ietf:params:scim:api:messages:2.0:Error"
  ],
  "scimType": "Attribute applicationID cannot be specified for the SCIM Object.",
  "status": "400"
}: timestamp=2021-05-03T16:05:10.332+0200
2021-05-03T16:05:10.333+0200 [WARN]  plugin.terraform-provider-databricks_v0.3.3: /api/2.0/preview/scim/v2/ServicePrincipals:400 - Request is unparsable, syntactically incorrect, or violates schema.: timestamp=2021-05-03T16:05:10.333+0200
```

###  Behavior
According to the provider documentation and implementation we shall pass an `application_id` field in `databricks_service_principal` resource. But according to your REST API documentation the application is automatically generated by your back-end. This inconsistency makes it impossible to create a service principal resource.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
* I activated SCIM service principal preview

**Comment by nfx** [comment]
This resource only works for azure databricks at the moment
