### ISSUE TITLE
AUTO CLUSTER CREATION  FOR ADLS GEN2 MOUNT DOES NOT DELETING AUTOMATICALLY  

### ISSUE THREAD

**Issue by gaddaak** [databrickslabs/terraform-provider-databricks#632]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_adls_gen2_mount

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior
After attaching adls gen2 mount to a cluster it doesn't delete the cluster automatically

### Actual Behavior
The cluster doesn't delete and its in terminated state which we don't want a cluster sitting in production in terminated state.

### Steps to Reproduce
create azurerm databricks workspace with terraform and add adls gen2 mount to the workspace.

**Comment by alexott** [comment]
it's intended behavior, because you may create multiple mount points at time and won't wait until new cluster is created for each mount point.

**Comment by nfx** [comment]
Clusters will be autoterminated after 10 minutes. This is the only way to do mounting, as of now.
