### ISSUE TITLE
[ISSUE] Token refresh error terraform plan and apply

### ISSUE THREAD

**Issue by choukimasri** [databrickslabs/terraform-provider-databricks#643]
Hi there, I'm having trouble re-applying my terraform plan following a sucessful deploiement

### Terraform Version
14.0.3

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_token

### Environment variable names
Azure Managed

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    databricks = {
      source  = "databrickslabs/databricks"
      version = "0.3.3"
    }
  }
}

provider "databricks" {
  alias = "case_databricks"
  host  = azurerm_databricks_workspace.case_databricks.workspace_url
}

// create PAT token to provision entities within workspace
resource "databricks_token" "pat" {
  provider = databricks.case_databricks
  comment  = "Terraform Provisioning"
  // 100 day token
  lifetime_seconds = 8640000
}

resource "azurerm_databricks_workspace" "case_databricks" {
}
```

### Debug Output
Error: Post https://adb-xx.azuredatabricks.netapi/2.0/token/create: dial tcp: lookup adb-xx.azuredatabricks.netapi: no such host

### Expected Behavior
No Errors as first Run, 0 changes plan

### Actual Behavior
What actually happened?
Terraform Error 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply ` with no resources deployed
2. `terraform apply ` or `terraform plan`

### Important Factoids
- Nothing special

**Comment by nfx** [comment]
does `azurerm_databricks_workspace.case_databricks.workspace_url` have slash in the end?

**Comment by nfx** [comment]
Please use 

```
provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.this.id
}
```

(also - you don't have to specify `alias`, if you use only one provider instance in the module

https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/guides/azure-workspace#provider-configuration

**Comment by choukimasri** [comment]
according to azurerm provider docs

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/databricks_workspace
```
workspace_url - The workspace URL which is of the format 'adb-{workspaceId}.{random}.azuredatabricks.net'
```
So I guess not,

Thank you I will reflect these changes.

**Comment by choukimasri** [comment]
it's fixed ?
