### ISSUE TITLE
[FEATURE] Support databricks_user data source

### ISSUE THREAD

**Issue by psg2** [databrickslabs/terraform-provider-databricks#647]
Hi there,

I would like to ask for support for a data source for databricks_user, similar to the data source databricks_current_user, but allowing to get any user information based on user_name.

The use case is the following:
After we enabled SSO in our workspaces, users are managed from an external Identity Provider, but we still manage groups through Terraform and we need to manage the memberships as well and to do that we need the user ID which isn't easy to get on Terraform, one way to do it is to create a resource databricks_user and import it manually or try some automation. Internally we created a module called `terraform-databricks-team` that receives a list of user emails and does the following:

```tf
## Internal
data "databricks_user" "user" {
  count     = length(var.users)
  user_name = var.users[count.index]
}

data "databricks_group" "group" {
  count        = length(var.groups)
  display_name = var.groups[count.index]
}

resource "databricks_scim_group" "databricks_group" {
  display_name = var.name
  entitlements = var.entitlements
  roles        = var.roles
  members      = concat(data.databricks_user.user.*.id, data.databricks_group.group.*.id)
}

## Usage
module "squad_example" {
  source = "../"

  name = "squad_example"

  roles = []

  users = [
    "foo.bar@example.com",
    "foobar@example.com",
  ]
}
```

We maintain a forked version of this provider to do this and would like to if it's a good idea to have this data source on the original provider itself so others can take advantage of this and we can possibly drop our fork.

**Comment by nfx** [comment]
Hi @psg2 , would you be able to PR that one in?

**Comment by psg2** [comment]
Sure! Will do.

**Comment by psg2** [comment]
Hi, @nfx. Just started the pull request here for review: https://github.com/databrickslabs/terraform-provider-databricks/pull/648

**Comment by nfx** [comment]
@psg2 make fmt requested :)

And we'll be so happy for you to finally use the latest versions :-)

**Comment by nfx** [comment]
Btw, @psg2 databricks_scim_group is removed in favor of simplified databricks_group. Make sure to read 0.3.x migration guide

**Comment by psg2** [comment]
> Btw, @psg2 databricks_scim_group is removed in favor of simplified databricks_group. Make sure to read 0.3.x migration guide

I'm aware, it's just that internally we're using multiple versions it's a bit of a mess TBH.

With this PR I hope that we can start using the latest and open source provider for good this time.

**Comment by nfx** [comment]
@psg2 is has grown a long way since you've started using it :)

**Comment by psg2** [comment]
It truly did, I loved how you all evolved the solution.

**Comment by nfx** [comment]
What I generally tell is to manage groups with TF and get users SCIM provisioned into those groups by IDP

Sometimes people don't have access to SCIM provisioners, though

**Comment by psg2** [comment]
I understand and I would love to have it managed by IDP, but we're a long way from this stage still with our current Okta management.

**Comment by nfx** [comment]
Pr merged. Release in a few weeks, though you can mail me, if you want to get it sooner. It's approximately half of day overhead to roll out the release.

**Comment by psg2** [comment]
The sooner would be better for us, but I guess you just did a release yesterday. So take your time, so you don't need to spend your time doing follow-up releases like this.

I'm also looking forward to this https://github.com/databrickslabs/terraform-provider-databricks/issues/555 on the 0.4 milestone. Let me know if I can help with this feature as well.

**Comment by nfx** [comment]
@psg2 if you'll PR in #555, that would be great. Milestones are indicative of priorities for core maintaining team (@nfx & @alexott). Though, community is always welcome to submit a PR if they want to see certain functionality sooner.

If you'd like to pick #555, please make sure to

1. Read [contributing guide](https://github.com/databrickslabs/terraform-provider-databricks/blob/master/CONTRIBUTING.md)
2. Register new resources in [provider.go](https://github.com/databrickslabs/terraform-provider-databricks/commit/b4a5500cd690fda9d5e2ddc40dffd024d4d84706)
3. `make test` & `make fmt` before every push (i think CI didn't run only for the first-time contributors)
4. add (and run) basic acceptance test

Closing this ticket, as #648 is merged.

**Comment by carlosfrancia** [comment]
Hi @nfx, we are implementing Databricks in our company and we are really interested in having this feature in the provider to manage our group members under Terraform while using SSO. Do you have an idea when will this be released? 

Thank you,
Carlos

**Comment by nfx** [comment]
@carlosfrancia it was released this week
