### ISSUE TITLE
[ISSUE] databricks_aws_s3_mount do not work with instance profile which have a path

### ISSUE THREAD

**Issue by alangmdb** [databrickslabs/terraform-provider-databricks#651]
Provider version: 0.3.4

I am using paths for my roles/instance profiles ([see here](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_identifiers.html)).

I was expecting the following to work (given the profile exists):
```
resource "databricks_aws_s3_mount" "this" {
  instance_profile = "arn:aws:iam::0123456789:instance-profile/my/path/role"
  s3_bucket_name = "bla"
  mount_name = "logs"
}
```

Yet I get:
`should have gotten two parts: [instance-profile my path role]`

There is no issue using the API directly to add these instance profiles (nor in the databricks UI). Might be just a validation which is too aggressive?

**Comment by nfx** [comment]
@alangmdb would you be able to make a PR for this?

**Comment by alangmdb** [comment]
This is the offending code, do not know the reasoning behind it, but if there should be a reasonably unique cluster name, then it would be probably better to build the cluster name based on all the parts: `strings.Join(instanceProfileParts[1:], "_")`. @nfx Not very good at go, I can try to create a pull request, but will take me a bit to set up my environment.

```go
// GetOrCreateMountingClusterWithInstanceProfile ...
func GetOrCreateMountingClusterWithInstanceProfile(
	clustersAPI compute.ClustersAPI, instanceProfile string) (i compute.ClusterInfo, err error) {
	ia, err := arn.Parse(instanceProfile)
	if err != nil {
		return i, err
	}
	instanceProfileParts := strings.Split(ia.Resource, "/")
	if len(instanceProfileParts) != 2 {
		return i, fmt.Errorf("should have gotten two parts: %v", instanceProfileParts)
	}
	clusterName := fmt.Sprintf("terraform-mount-%s", instanceProfileParts[1])
	return clustersAPI.GetOrCreateRunningCluster(clusterName, compute.Cluster{
		NumWorkers:  1,
		ClusterName: clusterName,
		SparkVersion: clustersAPI.LatestSparkVersionOrDefault(
			compute.SparkVersionRequest{
				Latest:          true,
				LongTermSupport: true,
			}),
		NodeTypeID: clustersAPI.GetSmallestNodeType(
			compute.NodeTypeRequest{
				LocalDisk: true,
			}),
		AutoterminationMinutes: 10,
		AwsAttributes: &compute.AwsAttributes{
			InstanceProfileArn: instanceProfile,
			Availability:       "SPOT",
		},
	})
}
```

**Comment by alangmdb** [comment]
@nfx Created a pull request, but see my note regarding testing in it.
