### ISSUE TITLE
[ISSUE] skip_validation false on databricks_instance_profile

### ISSUE THREAD

**Issue by psg2** [databrickslabs/terraform-provider-databricks#654]
Hi there,

According to the changelog on version 0.3, we have the following note, but on [the code it's always set to false](https://github.com/databrickslabs/terraform-provider-databricks/blob/master/identity/resource_instance_profile.go#L48)

```
skip_validation from databricks_instance_profile was removed and is always set to true.
```

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_instance_profile

### Expected Behavior
What should have happened?
Databricks instance profile created successfully without the validation

### Actual Behavior
What actually happened?
AWS error while the trying to validate the instance profile.
```
Error: Verification of the instance profile failed. AWS error: You are not authorized to perform this operation. Encoded authorization failure message: 7MwWBEFCWvK7bl7B7YL3OmAOtP5wWIxZByl8UN-2Sa9mkQhFhqMa21GkCFt3GIWnABywGXAXBmFfdR4q9ODs7FfVzu5k18tOwpLk8NKZ8aVTV7vh9Pk0abdRyZHVuM50H3y_CVi1COvX35tmDzulBci82YIV-mD4gelNzmO5FWrv-ydybjlLAv82W1LHB4MF-cMb6VNmLA4dAmJARtyi_QdETot5YSV32XY6g07UKRCuBX4r3yRqOOFbmxrXFxOWBIzHTq1pZbBJfCJ9OR-BR2EF1OWeHtIoQnzQlxinpFCfBE2Qo7gg1JEQBl240dkSFa-yx-6NJKVfujnLwRERJAenZlTpJ9CKFdTuiKgxR3EmacqoQC8-kIwW1Bg-oF_VHGrySF1BOnTXFMrf5oDzVIEgyg-pz3f49gohZKKNnHWAobwI71Oddm4f78SrgIlOQNsd-Re8A_wWqNWO0OM13S_DlMIrlTJtvqPfT4lY31rmbgWm3BtBQ9AZyDmkJ8BcnfiM3XPbFGwA08xb9mS61FvwKpm75NRKGOIOFnQb08fLqCSh357IfwlsBB-G6GQ5vWVwm8BLUr_UY5V2jGoaPvRvPh8P4yGm4AfpvVvQiyHF6AU8Wp79x4eYJRjFJAzBBqxn7AlTIgoO6t_1Jiun7b4bLW8ikvclV48lYcAuiV_-B3V6maX1jvIjuI92jA2r0QaSObB2P-JvhJEpH7PHuqvqdKiQrvsPOu0JBOGfEXTPaP2TcQTBSBr3cVYhIJrityT_ZOoFE5qXycZYTq4HH6Jq6XDhjzig7OZqmGLH3Z6uNyu65cFpxA339c1kR0xTYKEuPPZ_AVwoOiYmncSl3GRk-mOTW7ISCZ1f_epo3GpnhCkbYib1rxb9CyhUqBYm0QEjVodH84tFh6c98Za6KG5ScrJxg6U0Ts0kS-LTFCw91wgqWCXvDZCS0lx7xg
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by nfx** [comment]
@psg2 we always validate the instance profile in TF, before adding it. Please decode the failure of the message https://aws.amazon.com/premiumsupport/knowledge-center/aws-backup-encoded-authorization-failure/

**Comment by psg2** [comment]
I know the failure of the message, and there is no workaround that AFAIK. If I'm correct Databricks tries to validate the instance profile by creating a new EC2 instance with it on AWS, but our infrastructure team has some global policies that block the creation of EC2 instances without default tags that Databricks doesn't use on the validation.

**Comment by nfx** [comment]
@psg2 unfortunately it's not possible to add/change tags for that verification part.. technically, you can try adding some exclusions on policies just for these "verification ec2" instances

**Comment by psg2** [comment]
> @psg2 unfortunately it's not possible to add/change tags for that verification part.. technically, you can try adding some exclusions on policies just for these "verification ec2" instances

I know but was so much simpler with the skip_validation. ):
For now, what I did was create almost everything with Terraform and created the instance profiles on Databricks UI with the skip_validation checkbox.

Also, I don't know how to identify those verification instances since this isn't like publicly available for us to add the exclusion and might leave like an edge case or backdoor on top of our SRE's team rules.

**Comment by nfx** [comment]
@psg2 the problem with `skip_validation` was that we were receiving plenty of bug reports on instance profiles, that didn't work 🤷 also, it's in terraform ideology to make a resource, that is guaranteed to work after creation, hence the skip omission 🤷 e.g. smaller surface to support in the long term. 

do you have CloudTrail logs collected? you can take a look at ec2 tags used in the verification instance. one filtering rule for sure - that those requests would be coming from a known databricks account and your cross-account role.

**Comment by psg2** [comment]
Why does the provider need to remove a Databricks API feature? 🤔 
The attribute could be kept with the `false` default and the user is responsible for dealing with errors if wants to skip_validation.

Maintaining an exclusion list based on CloudTrails on something that is internal to Databricks and hard to track if it changes over time might be error-prone and hard to maintain, we might even end up with something like a backdoor on our SRE's global rules and teams can start creating instances without the proper tagging.

> @psg2 the problem with skip_validation was that we were receiving plenty of bug reports on instance profiles, that didn't work 🤷 also, it's in terraform ideology to make a resource, that is guaranteed to work after creation, hence the skip omission 🤷 e.g. smaller surface to support in the long term.

Can you clarify what sort of bug reports you were receiving? I didn't understand so well why this might be a provider's fault.

**Comment by nfx** [comment]
> Why does the provider need to remove a Databricks API feature? 🤔

Because Terraform should not create resources, that might be invalid :)

**Comment by psg2** [comment]
But this is also providing false positives validations that are breaking our current implementation, and unlike the case when we had this attribute that we could add warnings to the users about the validation and they would be aware of possible failures and they most likely would notice those failures when creating clusters, we don't have this luxury.

We need to troubleshoot CloudTrail logs without any guidance and deal with AWS and Databricks internal just to use a role that we know works, or skip the provider entirely and have unreproducible steps done through the UI. This seems like such an easy attribute to maintain with good defaults that wouldn't justify a fork.

Also regardless of the output would be nice to update the changelog that is misleading when compared to the code.

**Comment by nfx** [comment]
@psg2 indeed we'll fix the changelog

**Comment by psg2** [comment]
Hi, @nfx. Commenting just to let you know that we managed to add an exception rule after inspecting Cloud Trail.

Do you think would be interesting to add something related to it to the documentation?

Below is an example IAM policy that could help with it.
```json
        {
            "Sid": "YourCustomDenyEC2CreationStatement",
            "Effect": "Deny",
            "Action": [
                "ec2:RunInstances",
                "ec2:CreateTags"
            ],
            "Resource": [
                "arn:aws:ec2:*:*:instance/*"
            ],
            "Condition": {
                .... Your conditions here ....
                "StringNotEquals": {
                    "aws:username": [
                        "databricks"
                    ],
                    "aws:RequestTag/Vendor": [
                        "Databricks"
                    ],
                    "aws:RequestTag/Creator": [
                        "fake creator"
                    ],
                    "aws:RequestTag/ClusterName": [
                        "fake cluster"
                    ],
                    "aws:RequestTag/ClusterId": [
                        "fake-cluster-id"
                    ]
                }
            }
        },
```

**Comment by Tagar** [comment]
+1 to allow passing `skip_validation` through. We have another customer that also has mandatory ec2 tags so the validation always fails. Databricks supports skips validation in UI and REST API, would make sense to support the same in TF. 

Internal discussion - https://databricks.slack.com/archives/C531MJ480/p1627299547453600?thread_ts=1626970947.387300&cid=C531MJ480
