### ISSUE TITLE
[ISSUE] databricks_user allow_sql_analytics_access no longer persists

### ISSUE THREAD

**Issue by KoenR3** [databrickslabs/terraform-provider-databricks#667]
### Terraform Version
Terraform v0.15.3

### Affected Resource(s)
- databricks_user

### Environment variable names
None

### Terraform Configuration Files
```hcl
resource "databricks_user" "user" {
  for_each  = local.users
  user_name = each.key
  allow_sql_analytics_access = each.value
}
```

### Debug Output
Too much sensitive information in the debug output to paste it here...

### Expected Behavior
When putting the argument `allow_sql_analytics_access` to `true` and SQL Analytics is enabled, it should be set.

### Actual Behavior
This worked until the new deployment of Databricks.  Now this is not set.  If you manually enable `Databricks SQL access` in the Admin console, it is also removed when running an apply.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
- SQL Analytics enabled
- New Databricks Workspace interface
- Running on AWS

**Comment by KoenR3** [comment]
This also means that all users lose SQL Analytics access once we run Terraform again

**Comment by alexott** [comment]
can you send me the debug log? alexey.ott at databricks.com

**Comment by nfx** [comment]
Does the issue still persist?

**Comment by KoenR3** [comment]
I have tried with Terraform v1.0.0 and Databricks Provider v0.3.5 and the issue still persists with this configuration

**Comment by nfx** [comment]
We'll look into it in the following release

**Comment by KoenR3** [comment]
Do you have an ETA on this per chance?  We will start onboarding users on SQL analytics next week and currently every time we run Terraform we all have to give them access again manually.
