### ISSUE TITLE
library_cran.Messages should be type list string like other libraries

### ISSUE THREAD

**Issue by psg2** [databrickslabs/terraform-provider-databricks#67]
https://github.com/databrickslabs/databricks-terraform/blob/20e0acb2eacfe1c93f436002e8bc94a5698ab5d2/databricks/resource_databricks_cluster.go#L457

This can break the provider during a refresh operation if the library has messages and the provider is expecting a single string.

**Comment by nfx** [comment]
Messages have no use in state, but only library installation statuses. They will be removed in future versions.
