### ISSUE TITLE
[FEATURE] Support creation of directories on the workspace

### ISSUE THREAD

**Issue by psg2** [databrickslabs/terraform-provider-databricks#672]
Hi there,

I would like to know if it's possible to add a new resource to the provider that would support the creation of directories on the workspace. Looking at the code I saw that we already have the Mdkirs implemented, we just don't expose it yet through a resource.

The use case here would be to create a folder on the root directory for teams to put shared resources that are not for the whole workspace like the Shared folder. Could be something like:

```hcl
data "databricks_directory" "directory_foo" {
  path = "/Foo"
}

resource "databricks_permissions" "folder_usage" {
    directory_path = "/Foo"

    access_control {
        group_name = "users"
        permission_level = "CAN_READ"
    }
}
```

Also looking at the docs and code, the databricks_permissions already works for both directory_id and path.

Does it make sense to add this resource or should we use placeholder notebooks to generate directories through terraform?

```hcl
resource "databricks_notebook" "this" {
    content_base64 = base64encode("# Welcome to your Python notebook")
    path = "/Production/ETL/Features"
    language = "PYTHON"
}
```

If this is something that the maintainers agree with, I can take it and do a pull request later on.

**Comment by alexott** [comment]
I personally thinking that we should have it - some users are complaining about having a useless notebook polluting the directories. There was already the #373, but it was closed.   I have this item in my todo list for a some time, but if you can make it - that would be nice.

@nfx WDYT?

**Comment by nfx** [comment]
@psg2 please go ahead and make the PR, but don't forget to add a mutex shared with `databricks_notebook`. I foresee those 10 concurrent TF requests to conflict a lot for customer with plenty of notebooks in different folders.

https://docs.databricks.com/dev-tools/api/latest/workspace.html#import
https://docs.databricks.com/dev-tools/api/latest/workspace.html#get-status

we'll help you with reviews :)

**Comment by alexott** [comment]
I only thought about calling it `databricks_folder` to match the UI naming

**Comment by psg2** [comment]
> I only thought about calling it `databricks_folder` to match the UI naming

I thought about `directory` because we already use `directory_id` and `directory_path` attributes on the permissions resource. If we use `folder` instead I would think about renaming the permissions attributes, but that would be a breaking change for anyone upgrading the provider. Thoughts?

**Comment by alexott** [comment]
that's ok - let keep it `databricks_directory`

**Comment by nfx** [comment]
@psg2 Any updates on the upcoming PR? Willing to keep amount of open issues low.

**Comment by psg2** [comment]
> @psg2 Any updates on the upcoming PR? Willing to keep amount of open issues low.

Not yet. ):

I probably will be able to tackle this by next week, but not before that.

**Comment by nfx** [comment]
by next week is very good.

**Comment by nfx** [comment]
Hi @psg2 :) a weekly reminder

**Comment by psg2** [comment]
Hi, @nfx . I'm going to try and start working on this today, but the reality is that I'm not likely to accomplish this for this week, as we're nearing the end of the quarter some other priorities emerged on the company.

**Comment by psg2** [comment]
Hi, @nfx . Just opened a draft pull request (https://github.com/databrickslabs/terraform-provider-databricks/pull/690) to start the discussion about the new code.

**Comment by nfx** [comment]
thank you for the contribution, @psg2 !
