### ISSUE TITLE
[ISSUE] Unable to create single node cluster with high concurrency

### ISSUE THREAD

**Issue by psg2** [databrickslabs/terraform-provider-databricks#680]
Hi there,

The resource `databricks_sql_permissions` works fine on its own, but if you try to provide the cluster_id yourself based on the internal cluster ([code](https://github.com/databrickslabs/terraform-provider-databricks/blob/master/access/resource_sql_permissions.go#L260)) managed by the provider it fails with the error message: "NumWorkers could be 0 only for SingleNode clusters. See https://docs.databricks.com/clusters/single-node.html for more details" ([code](https://github.com/databrickslabs/terraform-provider-databricks/blob/master/compute/resource_cluster.go#L123)). But based on the `databricks_sql_permissions` it looks like this should work and could be supported.

Likely we need to update the validation to identify single-node clusters for the serverless profile.

Unrelated to this issue, I just noticed a typo on the managed cluster using `terrraform` with 3 R's [here](https://github.com/databrickslabs/terraform-provider-databricks/blob/master/access/resource_sql_permissions.go#L262)

Related issue: https://github.com/databrickslabs/terraform-provider-databricks/issues/678

### Terraform Version
N/A

### Affected Resource(s)
- databricks_cluster

### Environment variable names
N/A

### Terraform Configuration Files

```hcl
resource "databricks_cluster" "terraform_stable_acl" {
  cluster_name            = "terraform_stable_acl"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 10

  spark_conf = {
    "spark.databricks.acl.dfAclsEnabled" : "true"
    "spark.databricks.repl.allowedLanguages" : "python,sql"
    "spark.databricks.cluster.profile" : "serverless"
    "spark.master" : "local[*]"
  }

  custom_tags = {
    "ResourceClass" = "SingleNode",
  }
}
```

### Debug Output
https://gist.github.com/psg2/ae519cb83b9907c30d0fe78d83b277e9

### Expected Behavior
What should have happened?
The cluster created with success with 0 workers

### Actual Behavior
What actually happened?
Error message blocking the apply on the provider itself prior to calling Databricks API.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know? 
N/A

**Comment by nfx** [comment]
> Error message blocking the apply on the provider itself prior to calling Databricks API.

What is the error message?

**Comment by nfx** [comment]
Try creating single-worker cluster

**Comment by psg2** [comment]
> > Error message blocking the apply on the provider itself prior to calling Databricks API.
> 
> What is the error message?

It's on the gist of debug output, https://gist.github.com/psg2/ae519cb83b9907c30d0fe78d83b277e9, and the beginning of the issue, "NumWorkers could be 0 only for SingleNode clusters. See https://docs.databricks.com/clusters/single-node.html for more details" (code).

A single-worker cluster works, but then it will bill for 2 EC2 instances and it display some errors on the UI if you go to the edit page.

![image](https://user-images.githubusercontent.com/14082115/120925491-3ecb0100-c6af-11eb-866a-4bb16f4952f9.png)

**Comment by nfx** [comment]
@psg2 single-node, high-concurrency - those are just special cluster configs. They are responsible for different things. It almost never makes sense to have them both enabled unless this specific case. 

https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/sql_permissions did you also try configs in this page?

**Comment by psg2** [comment]
> https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/sql_permissions did you also try configs in this page?

Yes. Just to be sure my issue here isn't about failing to launch a usual high concurrency cluster, but the fact that to use sql_permissions given my organization rules, I need to create a separate cluster with specific tagging and I can't use the same config the provider uses internally of a single node cluster having to pay for 2 EC2 instances.

**Comment by alexott** [comment]
Really to set Table ACLs we need only following configs (see [example of REST API](https://docs.databricks.com/dev-tools/api/latest/examples.html#cluster-table-acl-example)):

```hcl
  spark_conf = {
    "spark.databricks.acl.dfAclsEnabled": "true",
    "spark.databricks.repl.allowedLanguages": "python,sql",
  }
```

that could be combined with either high-concurrency, or with single-node clusters.

Here is working config for single node cluster with Table ACLs:

```hcl
resource "databricks_cluster" "terraform_stable_acl" {
  cluster_name            = "terraform_stable_acl"
  spark_version           = data.databricks_spark_version.latest_lts.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = 10

  spark_conf = {
    "spark.databricks.acl.dfAclsEnabled" : "true"
    "spark.databricks.repl.allowedLanguages" : "python,sql"
    "spark.databricks.cluster.profile" : "singleNode"
    "spark.master" : "local[*]"
  }

  custom_tags = {
    "ResourceClass" = "SingleNode",
  }
}
```

I'll update documentation for that.
