### ISSUE TITLE
[ISSUE/FEATURE?] SQL Analytics Query/Dashboard Run as Viewer/Owner setting

### ISSUE THREAD

**Issue by andreaslang** [databrickslabs/terraform-provider-databricks#683]
### Terraform Version
v0.15.4

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_sql_query
- databricks_sql_dashboard
- databricks_permissions

### Terraform Configuration Files
```hcl
resource "databricks_sql_query" "test" {
  data_source_id = databricks_sql_endpoint.default.data_source_id
  name = "Terraform Example Query"
  query = "SELECT {{ p1 }} AS p1, 2 as p2"

  parameter {
    name = "p1"
    title = "Title for p1"
    text {
      value = "default"
    }
  }

  tags = [
    "test"
  ]
}

resource "databricks_permissions" "test" {
  sql_query_id = databricks_sql_query.test.id

  access_control {
    group_name       = data.databricks_group.users.display_name
    permission_level = "CAN_RUN"
  }

  access_control {
    group_name       = databricks_group.engineering_maintenance.display_name
    permission_level = "CAN_EDIT"
  }
}
```

### Debug Output
```
╷
│ Error: Can't give CAN_EDIT permission with Run As Owner setting.
│ 
│   with databricks_permissions.test,
│   on sql_analytics_queries.tf line 21, in resource "databricks_permissions" "test":
│   21: resource "databricks_permissions" "test" {
│ 
╵
```

### Expected Behavior
Ideally there would be a way to set the Credentials setting via terraform. This is how it looks like in the query permissions:

![Screenshot 2021-06-08 at 15 34 13](https://user-images.githubusercontent.com/3317075/121204814-12f67980-c86f-11eb-8f59-631cc1f2f539.png)

If I call `/preview/sql/queries/<query-id>` I can see the option:
```json
{
  "id": "123", 
  "latest_query_data_id": null, 
  "name": "column_stats", 
  ...
  "options": {"run_as_role": "viewer", ...
```

Note though, other docs mention changing Run as Owner/Run as Viewer apparently needs cleaning out all permissions. Might make this a bit more tricky to implement.

### Actual Behavior
Just the error which likely comes from the API call.

### Steps to Reproduce
1. `terraform apply`

**Comment by nfx** [comment]
@andreaslang i think you should be able to specify this as parameters - https://github.com/databrickslabs/terraform-provider-databricks/blob/master/sqlanalytics/api/query.go#L42

@pietern - it'll be a quick one for you to answer

**Comment by pietern** [comment]
@nfx That's the right struct, but it doesn't have a field to set `run_as_role`. I'll take a look.

**Comment by andreaslang** [comment]
That was quick, thank you.
