### ISSUE TITLE
[ISSUE] Improve speed of mount refresh

### ISSUE THREAD

**Issue by w0ut0** [databrickslabs/terraform-provider-databricks#687]
### Terraform Version
Terraform v0.15.5

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_azure_adls_gen2_mount

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "databricks_azure_adls_gen2_mount" "marketing" {
    container_name         = azurerm_storage_container.this.name
    storage_account_name   = azurerm_storage_account.this.name
    mount_name             = "marketing"
    tenant_id              = data.azurerm_client_config.current.tenant_id
    client_id              = data.azurerm_client_config.current.client_id
    client_secret_scope    = databricks_secret_scope.terraform.name
    client_secret_key      = databricks_secret.service_principal_key.key
    initialize_file_system = true
}
```

### Expected Behavior
`terraform refresh` should take only a couple of seconds per resource, and not be blocked by a single resource.

### Actual Behavior
`terraform refresh` (as part of `terraform plan`) takes a long time (+/- 5 minutes) because in order for the mounts to refresh, a cluster needs to be started/created. The Databricks resources are only a small(er) part of our environment, so the existence of mounts delays our other, unrelated deployments.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform refresh`

### Important Factoids
I know why this is (and it's very well described in [the docs](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/azure_adls_gen2_mount)), but I am looking for potential workarounds, or even possible improvements to the provider that can make this process smoother.

Things I thought about:

- Execute our `terraform refresh` periodically (eg. at night), and run `terraform plan -refresh=false`  --> might introduce inconsistencies
- Make a seperate Terraform project for our Databricks resources --> possible solution. However we have a big monorepo for all other resources, so I would prefer not to do this
- Exclude the impacted resources from a refresh. --> This is [not yet possible](https://github.com/hashicorp/terraform/issues/2253) in Terraform 
- Any other suggestions?

**Comment by nfx** [comment]
@w0ut0 **mounts rely on a cluster**. by default it's spinning up a minimal cluster. you can specify existing cluster id, which points it to "Shared Autoscaling" cluster, which might be always on. you can also have always running single-node cluster, which you'd use for mounting (and probably some other low-overhead tasks). those are the only feasible workarounds until backend API is implemented for this. 

Once normal backend REST API is there, mounts would refresh pretty fast. There's no timeline for this yet. Please contact your Databricks representatives to increase the priority for Mount REST API :)
