### ISSUE TITLE
[DOC] Customer managed keys setup could be easier to find

### ISSUE THREAD

**Issue by KneeShard** [databrickslabs/terraform-provider-databricks#691]
### Affected Resource(s)
* https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/guides/aws-workspace.md
* https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/resources/mws_customer_managed_keys.md

### Expected Details
It would be great to have an optional section on setting up keys and the key grant policy in the AWS Workspace guide. It seems to me that this code is already available in the aws-mws-common folder: https://github.com/databrickslabs/terraform-provider-databricks/blob/master/scripts/modules/aws-mws-common/kms.tf

However, it's not obvious if you don't know to look for it, and it's not entirely clear how to use it.

### List of things to potentially add/remove:
- [ ] Add an optional section to the AWS Workspace guide with code for setting up the customer managed key, grant, and alias
- [ ] In the resource documentation, it would be good to add the `provider = databricks.mws` line to the example code to prevent `host is empty` errors from terraform
- [ ] In the AWS Workspace guide, in the Databricks E2 Workspace section, add optional lines to set `managed_services_customer_managed_key_id` and `storage_customer_managed_key_id`

### Important Factoids
None

### References
None

**Comment by nfx** [comment]
@KneeShard pull requests are welcome :) this is not something I'd currently see as priority for the maintenance team
