### ISSUE TITLE
[FEATURE] databricks_aws_crossaccount_policy is too permissive

### ISSUE THREAD

**Issue by KneeShard** [databrickslabs/terraform-provider-databricks#692]
### Terraform Version
0.14.11
AWS provider 3.46.0
Databricks provider 0.3.5

### Affected Resource(s)
- databricks_aws_crossaccount_policy

### Environment variable names
N/A

### Terraform Configuration Files
```hcl
data "databricks_aws_crossaccount_policy" "this" {
  provider = databricks.mws
}
```

### Expected Behavior
It would be great to provide a parameter that determines what set of permissions is included in this policy, e.g. the 'Your VPC, default' policy doesn't allow VPC creation and deletion. The link on the documentation page (https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/data-sources/aws_crossaccount_policy.md) actually points to the 'Your VPC, default' policy document.

### Actual Behavior
The policy seems to always provide the permissions from the 'Databricks VPC' page, which is too permissive in the scenario of setting up the VPC using the `terraform-aws-modules` block as described on the AWS Workspace guide (https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/guides/aws-workspace.md)

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
None

**Comment by nfx** [comment]
@KneeShard currently there are no cycles for this feature. would you like to make a PR for this one?

**Comment by nfx** [comment]
@psg2 this might be interesting for you

**Comment by psg2** [comment]
> @psg2 this might be interesting for you

I will take a look into this next week, I believe internally we already have a different set of policies through a module that could be a good fit here.

**Comment by nfx** [comment]
@psg2 it would be great if you contribute that one - less to maintain internally :)
