### ISSUE TITLE
[DOC] Adding repository path for "databricks_notebook_paths"

### ISSUE THREAD

**Issue by RaccoonForever** [databrickslabs/terraform-provider-databricks#703]
### Affected Resource(s)
Link to the page affected: https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/data-sources/notebook_paths

### Expected Details
![image](https://user-images.githubusercontent.com/4057852/124148131-a9dddc80-da8f-11eb-96ec-cba2201556a3.png)
I was looking to terraform jobs based on a Repo notebook and I didn't find anything.

### List of things to potentially add/remove:
- [ ] Maybe add in parenthesis how to access to repos (/Repos/....)

I agree that the answer is pretty obvious, but more clarity is better in my opinion. 
By the way, thanks for your work !

**Comment by nfx** [comment]
@RaccoonForever just prefix it with `/Repos`. Please send a PR if you want to have it documented sooner.

Documentation will be of course updated, when `databricks_repo` resource is there. For now the Repos CRUD API is being developed.
