### ISSUE TITLE
Unable to create Multiple Azure Databricks Workspaces with same cluster & permissions using Terraform

### ISSUE THREAD

**Issue by mahmood2103015** [databrickslabs/terraform-provider-databricks#709]
### Expected Behavior
Hi
I am using provider Databricks, but it has option to add only 1 workspacec ID.
I able to create 2 Databricks workspaces but the cluster & permissions are set only on workspace that is mentioned in provider but not both. Please help me in resolving this issue.

provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.cropdbr.id
}
### Actual Behavior
The cluster, user group &  permissions should be created in both the workspaces, but its creating only in the workspace that is mentioned in Provider.

Please help me how to refer both workspaces in provider?
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
M#############  MY Terraform code ######

resource "azurerm_databricks_workspace" "dbr" {
 name                = "${var.prefix}-dbr-${var.environment}"
 resource_group_name = azurerm_resource_group.RG.name
 location            = azurerm_resource_group.RG.location
 sku                 = "premium"
 managed_resource_group_name =   "DATABRICKS_${local.prefix_upper}_RG_${local.environment_upper}"

custom_parameters {
  public_subnet_name  = azurerm_subnet.pubsubnet.name
  private_subnet_name = azurerm_subnet.prvsubnet.name
  virtual_network_id  = azurerm_virtual_network.vnet.id
  no_public_ip        = var.environment != "dev" ? true : false
}
 tags = {
   SGI_Country  = var.country
  SGI_Region   = var.location
 }
}

# create cluster
resource "databricks_cluster" "analyticscluster" {
 cluster_name            = "analyticscluster"
 spark_version           = "7.3.x-cpu-ml-scala2.12"
 node_type_id            = "Standard_DS4_v2"
 autotermination_minutes = 20
 spark_conf = {
   # Single-node
   "spark.databricks.cluster.profile" : "singleNode"
   "spark.master" : "local[*]"
#   "spark.artifact" : "{{secrets/artifacts/artifactstoken}}"
 }

 custom_tags = {
   "ResourceClass" = "SingleNode"
 }
}

########################

resource "azurerm_databricks_workspace" "cropdbr" {
 name                = "${var.prefix}-crop-dbr-${var.environment}"
 resource_group_name = azurerm_resource_group.RG.name
 location            = azurerm_resource_group.RG.location
 sku                 = "premium"
 managed_resource_group_name =   "DATABRICKS_${local.prefix_upper}_CR_RG_${local.environment_upper}"

custom_parameters {
  public_subnet_name  = azurerm_subnet.pubcrsubnet.name
  private_subnet_name = azurerm_subnet.prvcrsubnet.name
  virtual_network_id  = azurerm_virtual_network.crvnet.id
  no_public_ip        = var.environment != "dev" ? true : false
}
 tags = {
   SGI_Country  = var.country
  SGI_Region   = var.location
 }
}

resource "databricks_cluster" "analyticscrpcluster" {
 cluster_name            = "analyticscrpcluster"
 spark_version           = "7.3.x-cpu-ml-scala2.12"
 node_type_id            = "Standard_DS4_v2"
 autotermination_minutes = 20
 spark_conf = {
 Single-node
   "spark.databricks.cluster.profile" : "singleNode"
   "spark.master" : "local[*]"
   "spark.artifact" : "{{secrets/artifacts/artifactstoken}}"
}

 custom_tags = {
   "ResourceClass" = "SingleNode"
 }
}

**Comment by nfx** [comment]
You should use "provider alias" feature, with you should find references for in Terraform documentation. This is not related to provider.
