### ISSUE TITLE
You should use "provider alias" feature, with you should find references for in Terraform documentation. This is not related to provider.

### ISSUE THREAD

**Issue by mahmood2103015** [databrickslabs/terraform-provider-databricks#710]
You should use "provider alias" feature, with you should find references for in Terraform documentation. This is not related to provider.
@nfx
Hi Smertin,
can you please help me with the snippet? i am not sure how to use alias.

_Originally posted by @nfx in https://github.com/databrickslabs/terraform-provider-databricks/issues/709#issuecomment-873610060_

**Comment by nfx** [comment]
Please read the landing page of documentation
