### ISSUE TITLE
Unable to create Multiple Azure Databricks Workspaces with same cluster & permissions using Terraform 

### ISSUE THREAD

**Issue by mahmood2103015** [databrickslabs/terraform-provider-databricks#711]
You should use "provider alias" feature, with you should find references for in Terraform documentation. This is not related to provider.

@nfx

https://www.terraform.io/docs/language/providers/configuration.html

As per document the provider alias is for other regions. But i want to create 2 Databricks workspaces in same region.

I used code as :

provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.dbr.id
}

provider "databricks" {
  alias = "crop"
  azure_workspace_resource_id = azurerm_databricks_workspace.cropdbr.id
}

Then in resource i used provider as :

resource "azurerm_databricks_workspace" "cropdbr" {
 provider            = databricks.crop
 name                = "${var.prefix}-crop-dbr-${var.environment}"
 resource_group_name = azurerm_resource_group.RG.name
 location            = azurerm_resource_group.RG.location
 sku                 = "premium"
 managed_resource_group_name =   "DATABRICKS_${local.prefix_upper}_CR_RG_${local.environment_upper}"

custom_parameters {
  public_subnet_name  = azurerm_subnet.pubcrsubnet.name
  private_subnet_name = azurerm_subnet.prvcrsubnet.name
  virtual_network_id  = azurerm_virtual_network.crvnet.id
  no_public_ip        = var.environment != "dev" ? true : false
}
 tags = {
   SGI_Country  = var.country
  SGI_Region   = var.location
 }
}

I am getting this error after execution:

Error: Cycle: provider["registry.terraform.io/databrickslabs/databricks"].crop, azurerm_databricks_workspace.cropdbr

Please correct me if i am wrong with provider alias.

_Originally posted by @nfx in https://github.com/databrickslabs/terraform-provider-databricks/issues/709#issuecomment-873610060_

**Comment by nfx** [comment]
In the given example, you're adding the "provider" attribute to the resource of azurerm provider, whereas it should be added to Databricks resources on the other respective workspace.

This is the issue related to Terraform HCL syntax, not particularly related to this provider.
