### ISSUE TITLE
[FEATURE] Support for Databricks repos

### ISSUE THREAD

**Issue by w0ut0** [databrickslabs/terraform-provider-databricks#712]
I would like support for Databricks repos in the Terraform provider.

I read in [this article](https://databricks.com/blog/2021/03/16/productionize-data-science-with-repos-on-databricks.html) that the repos API is protected, so I guess this resource has to wait until that API is available?

Or is this something that can be included using the [databricks_workspace_conf](databricks_workspace_conf) resource?

**Comment by alexott** [comment]
It will be available only after the Repos CRUD API is available, until that time we can't do anything with it.  workspace conf could be used only to enable/disable Repos, but it's also not official way right now

**Comment by w0ut0** [comment]
Thanks @alexott! Is there an ETA on that CRUD API?

**Comment by alexott** [comment]
I can't say exactly, most probably with Repos GA somewhere in our Q3 (starting in August). But I can't say authoritatively

**Comment by nfx** [comment]
@w0ut0 currently terraform could only enable repos, just in case. I'll close this issue until the API is available.
