### ISSUE TITLE
Unable to read admins group using data{} ro add user in admin group if there are 2 databricks workspaces

### ISSUE THREAD

**Issue by mahmood2103015** [databrickslabs/terraform-provider-databricks#713]
Hi there,

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_cluster
- databricks_job

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Environment variable names
To get relevant environment variable _names_ please copypaste the output of the following command:
`$ env | sort | grep -E 'DATABRICKS|AWS|AZURE|ARM|TEST' | awk -F= '{print $1}'`

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please add turn on logging, e.g. `TF_LOG=DEBUG terraform apply` and run command again, paste it to gist & provide the link to gist. If you're still willing to paste in log output, make sure you provide only relevant log lines with requests.

It would make it more readable, if you pipe the log through `| grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'`, e.g.:

```
TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
```

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
I am creating 2 Databricks workspaces using provider databricks & alias of databricks provider.

While adding permissions i am unable to read admins  group from cropdbr databricks workspace. I am trying to add users in admin group of cropdbr workspace that i am creatng with alias provider of databricks. Please help me to resolve this.

data "databricks_group" "admins" {
  display_name = "admins"
  depends_on   = [
      azurerm_databricks_workspace.dbr,
      azurerm_databricks_workspace.cropdbr
  ]
}
resource "databricks_user" "crpalibhai" {
  provider         = databricks.crop
  user_name     = "alis@cloudlevel001hotmail.onmicrosoft.com"
  display_name = "ALIbHAIyya"
}

resource "databricks_group_member" "cropalibhai" {
  provider  = databricks.crop
  group_id  = data.databricks_group.admins.id
  member_id = databricks_user.crpalibhai.id
}

### Actual Behavior
I am getting error as
Error: Group with id 1554441089369248 not found.

  on databrickspermissions.tf line 91, in resource "databricks_group_member" "cropalibhai":
  91: resource "databricks_group_member" "cropalibhai" {

Please help me how can i get admins group id of cropdbr workspace. As by default it is trying to read admin group of  dbr workspace.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know?

**Comment by nfx** [comment]
`provider` attribute should also be allocated to data resources. https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs#multiple-provider-configurations

this is not the issue with provider and is more related to general terraform usage, which preferably should take place on https://discuss.hashicorp.com/c/terraform-core/27
