### ISSUE TITLE
Unable to create Databricks workspace with environment based restriction![ISSUE] Provider bug

### ISSUE THREAD

**Issue by mahmood2103015** [databrickslabs/terraform-provider-databricks#718]
Hi there,

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_cluster
- databricks_job

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Environment variable names
To get relevant environment variable _names_ please copypaste the output of the following command:
`$ env | sort | grep -E 'DATABRICKS|AWS|AZURE|ARM|TEST' | awk -F= '{print $1}'`

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Error: Invalid index

  on provider.tf line 28, in provider "databricks":
  28:   azure_workspace_resource_id = azurerm_databricks_workspace.cropdbr[1]
    |----------------
    | azurerm_databricks_workspace.cropdbr is tuple with 1 element

The given key does not identify an element in this collection value.

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
What should have happened?

### Actual Behavior
I am trying to deploy Databricks workspace in only QA & PROD env but not in Dev.
Using CODE as
provider "databricks" {
  alias = "crop"
  azure_workspace_resource_id = azurerm_databricks_workspace.cropdbr[1]
}

resource "azurerm_databricks_workspace" "cropdbr" {
 count = var.environment == "dev" ?  0 : 1
 name                = "${var.prefix}-crop-dbr-${var.environment}"
 resource_group_name = azurerm_resource_group.RG.name
 location            = azurerm_resource_group.RG.location
 sku                 = "premium"
 managed_resource_group_name =   "DATABRICKS_${local.prefix_upper}_CR_RG_${local.environment_upper}"

 custom_parameters {
  public_subnet_name  = azurerm_subnet.pubcrsubnet.name
  private_subnet_name = azurerm_subnet.prvcrsubnet.name
  virtual_network_id  = azurerm_virtual_network.crvnet.id
  no_public_ip        = var.environment != "dev" ? true : false
}
# tags = {
#   SGI_Country  = var.country
#  SGI_Region   = var.location
# }
}

resource "databricks_cluster" "analyticscrpcluster" {
 provider                = databricks.crop
 cluster_name            = "analyticscrpcluster"
 spark_version           = "7.3.x-cpu-ml-scala2.12"
 node_type_id            = "Standard_DS4_v2"
 autotermination_minutes = 20
 spark_conf = {
#   Single-node
   "spark.databricks.cluster.profile" : "singleNode"
   "spark.master" : "local[*]"
#   "spark.artifact" : "{{secrets/artifacts/artifactstoken}}"
 }

 custom_tags = {
   "ResourceClass" = "SingleNode"
 }
}

Then i am getting ERROR in plan as 

Error: Invalid index

  on provider.tf line 28, in provider "databricks":
  28:   azure_workspace_resource_id = azurerm_databricks_workspace.cropdbr[1]
    |----------------
    | azurerm_databricks_workspace.cropdbr is tuple with 1 element

The given key does not identify an element in this collection value.
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
Are there anything atypical about your accounts that we should know?

**Comment by nfx** [comment]
This is HCL issue, not provider specific issue.
