### ISSUE TITLE
Unable to create Databricks workspace with environment based restriction![ISSUE] Provider bug

### ISSUE THREAD

**Issue by mahmood2103015** [databrickslabs/terraform-provider-databricks#719]
Hi there,

I need help.

Trying to create databricks workspace in QA & PROD by restricting in Dev Env. Please  help.

My code i sbelow attached.

### Affected Resource(s)
Link to the page with issues and a screenshot/description of what section has an issue.

I am trying to deploy Databricks workspace in only QA & PROD env but not in Dev.
Using CODE as
provider "databricks" {
alias = "crop"
azure_workspace_resource_id = azurerm_databricks_workspace.cropdbr[1]
}

resource "azurerm_databricks_workspace" "cropdbr" {
count = var.environment == "dev" ? 0 : 1
name = "${var.prefix}-crop-dbr-${var.environment}"
resource_group_name = azurerm_resource_group.RG.name
location = azurerm_resource_group.RG.location
sku = "premium"
managed_resource_group_name = "DATABRICKS_${local.prefix_upper}CR_RG${local.environment_upper}"

custom_parameters {
public_subnet_name = azurerm_subnet.pubcrsubnet.name
private_subnet_name = azurerm_subnet.prvcrsubnet.name
virtual_network_id = azurerm_virtual_network.crvnet.id
no_public_ip = var.environment != "dev" ? true : false
}

tags = {
SGI_Country = var.country
SGI_Region = var.location
}
}

resource "databricks_cluster" "analyticscrpcluster" {
provider = databricks.crop
cluster_name = "analyticscrpcluster"
spark_version = "7.3.x-cpu-ml-scala2.12"
node_type_id = "Standard_DS4_v2"
autotermination_minutes = 20
spark_conf = {

Single-node
"spark.databricks.cluster.profile" : "singleNode"
"spark.master" : "local[*]"

"spark.artifact" : "{{secrets/artifacts/artifactstoken}}"
}

custom_tags = {
"ResourceClass" = "SingleNode"
}
}

Then i am getting ERROR in plan as

Error: Invalid index

on provider.tf line 28, in provider "databricks":
28: azure_workspace_resource_id = azurerm_databricks_workspace.cropdbr[1]
|----------------
| azurerm_databricks_workspace.cropdbr is tuple with 1 element

The given key does not identify an element in this collection value.
### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] First item to change
- [ ] Second item to change 

### Important Factoids
Any links to external documentation that may prove your case, i.e Databricks public docs or Terraform public docs. 

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #158

**Comment by nfx** [comment]
Configuration is missing ".id"
