### ISSUE TITLE
Unable to create Databricks workspace with environment based restriction!

### ISSUE THREAD

**Issue by mahmood2103015** [databrickslabs/terraform-provider-databricks#720]
This is HCL issue, not the provider issue. Configuration is missing ".id" attribute reference:

azure_workspace_resource_id = azurerm_databricks_workspace.cropdbr[1].id

_Originally posted by @nfx in https://github.com/databrickslabs/terraform-provider-databricks/issues/719#issuecomment-877063418_

Hi nfx,
Added condition in Databricks resource as below : 

resource "azurerm_databricks_workspace" "cropdbr" {
 count = var.environment == "dev" ?  0 : 1
 name                = "${var.prefix}-crop-dbr-${var.environment}"
 resource_group_name = azurerm_resource_group.RG.name
 location            = azurerm_resource_group.RG.location
 sku                 = "premium"
 managed_resource_group_name =   "DATABRICKS_${local.prefix_upper}_CR_RG_${local.environment_upper}"

 custom_parameters {
  public_subnet_name  = azurerm_subnet.pubcrsubnet.name
  private_subnet_name = azurerm_subnet.prvcrsubnet.name
  virtual_network_id  = azurerm_virtual_network.crvnet.id
  no_public_ip        = var.environment != "dev" ? true : false
}
# tags = {
#   SGI_Country  = var.country
#  SGI_Region   = var.location
# }
}
Still i am unable to read Databricks workspace ID .
Error: Invalid index

  on provider.tf line 28, in provider "databricks":
  28:   azure_workspace_resource_id = azurerm_databricks_workspace.cropdbr[1].id
    |----------------
    | azurerm_databricks_workspace.cropdbr is tuple with 1 element

The given key does not identify an element in this collection value.

**Comment by nfx** [comment]
This issue is related to HCL syntax, please post it on Terraform community discussion board:
https://discuss.hashicorp.com/c/terraform-core/27
