### ISSUE TITLE
[ISSUE] databricks cluster azure_attributes 'availability' setting fails to converge

### ISSUE THREAD

**Issue by mikemowgli** [databrickslabs/terraform-provider-databricks#729]
### Terraform Version
terraform v0.15.5
databricks v0.3.5

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_cluster

### Terraform Configuration Files
```hcl
resource "databricks_cluster" "tamers-databricks-cluster" {
     <...>
      
      azure_attributes {
          availability       = "SPOT_WITH_FALLBACK"
          first_on_demand    = 1
          spot_bid_max_price = -1
      }
  }
```

### Expected Behavior
the "SPOT_WITH_FALLBACK" value is terraform applied, seemingly with success, but the next terraform apply (or plan) shows that the current value is "ON_DEMAND_AZURE". The config never converges.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Factoids
Running a premium databricks workspace in the West Europe region with vnet injected clusters.

**Comment by nfx** [comment]
@mikemowgli please run `TF_LOG=debug DATABRICKS_DEBUG_TRUNCATE_BYTES=1024 terraform apply` and get the API log.

**Comment by mikemowgli** [comment]
here you go: https://gist.github.com/mikemowgli/a2b604f63b3225c84de5d16360524230

**Comment by stikkireddy** [comment]
i believe in azure it should be something like this:
```
 "azure_attributes": {
        "first_on_demand": 1,
        "availability": "SPOT_WITH_FALLBACK_AZURE",
        "spot_bid_max_price": -1
    },
```
you should use SPOT_WITH_FALLBACK_AZURE.

**Comment by alexott** [comment]
Yes, it's [clearly documented](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/cluster#availability)

**Comment by mikemowgli** [comment]
Works like a charm. My bad.
