### ISSUE TITLE
[ISSUE] New users aren't receiving sign-up email reliably

### ISSUE THREAD

**Issue by jamesdowning-chip** [databrickslabs/terraform-provider-databricks#731]
### Terraform Version
```
Terraform v1.0.2
on darwin_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.3.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_user

### Terraform Configuration Files
```hcl
variable "data_engineering_users" {
  description = "Data engineering users."
  type        = map(string)
  default = {
    "Jimmy Test" = "jimmy.test@myemail.com"
    "Billy Bob"  = "billy.bob@myemail.com"
  }
}

resource "databricks_user" "data_engineering_user" {
  for_each     = var.data_engineering_users
  display_name = each.key
  user_name    = each.value
}

```

### Expected Behavior
Once the user is created in the workspace an invitation email is sent to the user.

### Actual Behavior
User is successfully created however the user does not always receive a sign-up email. The only way to reliably trigger the sign-up email is by creating the user through the UI.

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
The invitation email seems sporadic, sometimes user's will receive the sign-up email and not others. Apologies if this is a Databricks issue rather than the Terraform provider, please let me know and I'll contact DataBricks themselves.

**Comment by nfx** [comment]
@jamesdowning-chip this is related to backend. i've just pinged the identity management team - let's see if we need to construct the SCIM request differently. Sometimes it's desired for users not to receive email - e.g. when SSO & invite all users to newly created workspaces and performing some last checks.

but please contact your CSE or AE on this as well

**Comment by jamesdowning-chip** [comment]
Brilliant, thank you @nfx. I've already been in touch with our solutions architect from DataBricks as well 👍

**Comment by nfx** [comment]
@jamesdowning-chip Let him know to  Slack me if he finds a solution faster :)

**Comment by nfx** [comment]
@jamesdowning-chip i've got some updates. Email is sent whenever user is added for the first time. It's not possible to force sending through underlying SCIM API, because there's nothing in the protocol about it. Closing this one, as we cannot do anything about it on the client library level. Please raise platform feature request through your dedicated SA/AE.
