### ISSUE TITLE
[FEATURE] Support for MSI authentication on Azure

### ISSUE THREAD

**Issue by JamesDLD** [databrickslabs/terraform-provider-databricks#741]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v1.0.0
on darwin_amd64
provider registry.terraform.io/databrickslabs/databricks v0.3.6
provider registry.terraform.io/hashicorp/azurerm v2.69.0

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_node_type
- databricks_instance_pool

This issue affect all resources, the provider authentication doesn't work when using an [Azure Managed Identity](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-arm?WT.mc_id=DOP-MVP-5003548).

### Terraform Configuration Files
```hcl
terraform {
  backend "azurerm" {
  }
  required_version = "1.0.0"
}

terraform {
  required_providers {
    databricks = {
      source  = "databrickslabs/databricks"
      version = "0.3.6"
    }
  }
}

provider "azurerm" {
  features {}
  subscription_id = var.subscription_id
}

provider "databricks" {
  azure_workspace_resource_id = var.workspace_id
}

data "databricks_node_type" "smallest" {
}

resource "databricks_instance_pool" "smallest_nodes" {
  instance_pool_name = "Smallest Nodes"
  min_idle_instances = 0
  max_capacity       = 300
  node_type_id       = data.databricks_node_type.smallest.id
  aws_attributes {
    availability = "ON_DEMAND"
    zone_id = "us-east-1a"
    spot_bid_price_percent = "100"
  }
  idle_instance_autotermination_minutes = 10
  disk_spec {
    disk_type {
      ebs_volume_type = "GENERAL_PURPOSE_SSD"
    }
    disk_size = 80
    disk_count = 1
  }
}
```

### Panic Output
Not concerned.

### Expected Behavior
Authenticate to Databricks and create an Instance Pool.

### Actual Behavior
Output this error `Error: Management API token must be provided for service principal admin user login`

### Steps to Reproduce
Connect to a [Virtual Machine that has an Azure Managed Identity (MI)](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/tutorial-linux-vm-access-arm?WT.mc_id=DOP-MVP-5003548) and ensure that this MI is has the [Contributor](https://docs.microsoft.com/en-us/azure/databricks/administration-guide/?WT.mc_id=DOP-MVP-5003548) role on the Azure Databricks resource.
1. `az login --identity`
2. `terraform init`
3. `terraform plan`

### Important Factoids
This works with an Azure AD account but fails when using an Azure Managed Identity.

**Comment by nfx** [comment]
Hi @JamesDLD , this is related to MSI auth. it's currently not supported.
