### ISSUE TITLE
[ISSUE] databricks_sql_widget parameter ordering causes plan changes

### ISSUE THREAD

**Issue by pietern** [databrickslabs/terraform-provider-databricks#749]
Repeatedly applying the same state can cause churn on the parameter ordering in `databricks_sql_widget` resources.

Need to figure out how to make the ordering in the API payloads match the ordering in the state.

Likely possible by writing a custom `DiffSuppressFunc`.

**Comment by nfx** [comment]
@pietern should also be possible with `tf:"slice_as_set"`

or you can sort widgets by something

**Comment by pietern** [comment]
Can you use `slice_as_set` with non-primitive types?

**Comment by nfx** [comment]
yes - tf creates a map, where part of the key is the hash of all values inside of non-primitive
