### ISSUE TITLE
[ISSUE] Provider bug with databricks_user resource

### ISSUE THREAD

**Issue by joselcaguilar** [databrickslabs/terraform-provider-databricks#754]
### Terraform Version
1.0.3

### Databricks Provider Version
Tested on 0.3.5 and 0.3.6

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_user

### Environment variable names
AzureRM auth is working due to I'm deploying the databricks_cluster and databricks_group without issues.

### Terraform Configuration Files
```hcl
locals {
  adbGroupUsers = length(var.aadGroupOwnersUPN) == 0 && length(var.aadGroupMembersUPN) != 0 ? split(",", var.aadGroupMembersUPN) : (
    length(var.aadGroupOwnersUPN) != 0 && length(var.aadGroupMembersUPN) == 0 ? split(",", var.aadGroupOwnersUPN) : (
      length(var.aadGroupOwnersUPN) != 0 && length(var.aadGroupMembersUPN) != 0 ? concat(split(",", var.aadGroupOwnersUPN), split(",", var.aadGroupMembersUPN)) : []
    )
  )
}

resource "databricks_user" "adbUser" {
  count     = length(local.adbGroupUsers)
  user_name = local.adbGroupUsers[count.index]
}
```

### Debug Output
Error: MALFORMED_REQUEST: RPC class com.databricks.api.proto.users.UpdateUser is not supported in Directory service

with module.adbGroup.databricks_user.adbUser[65],
on ../../../../products/databricks-workspace/extensions/aad-group/users.tf line 1, in resource "databricks_user" "adbUser":
 1: resource "databricks_user" "adbUser" {

### Panic Output
N/A

### Expected Behavior
All users creation without issues.

### Actual Behavior
The error is raised with one user

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform init && terraform plan`
2. `terraform apply`

### Important Factoids
N/A

**Comment by nfx** [comment]
Hi @joselcaguilar - there's internal ticket about this issue already, as this is a platform issue. Please raise this to Azure Support or Databricks Support.

**Comment by joselcaguilar** [comment]
@nfx Could be related with a blankspace in the display_name autogenerated (which is optional based on the Databricks provider docs)? At least in my test, the error is raised only with 1 user which Databricks Workspace has added a blankspace:
`xxx@corp.com Surname`

I have tried adding `display_name = trimspace(local.adbGroupUsers[count.index])` without success but maybe can be fixed internally?

Thanks again!
