### ISSUE TITLE
token permission added to a group in Terraform workspace is removed by token permission added to another group in a different Terraform workspace

### ISSUE THREAD

**Issue by spunuru** [databrickslabs/terraform-provider-databricks#757]
Multiple projects use same Databricks Airgapped Private cloud Databricks environment/workspace.
Each project has its own Terraform workspace. Each project in its Terraform workspace, has below block of code to grant token authorization, to the project specific group.

```
resource "databricks_permissions" "token_usage_sa" {
  authorization = "tokens"
  access_control {
    group_name = databricks_group.service_accounts.display_name
    permission_level = "CAN_USE"
  }
}
```

Once a project applied Terraform, it granted the token permission to its group. When I apply Terraform for second project, it  removes the token authorization from first project group and adds the second group. Can you please fix the issue?

**Comment by spunuru** [comment]
The issue does not seem specific to token authorization, but also other resources like folders, jobs, clusters etc.

**Comment by nfx** [comment]
@spunuru This is strange. Can you contact support with debugged (TF_LOG=debug terraform apply) logs? Doesn't seem to be plugin issue.

**Comment by nfx** [comment]
@spunuru this is not a plugin issue.
