### ISSUE TITLE
[ISSUE] Provider failing to authenticate using Azure Service Principal

### ISSUE THREAD

**Issue by JuanCepedaM** [databrickslabs/terraform-provider-databricks#765]
Hello.

We're trying to use databricks provider with azure service principal authentication, to be able to deploy our clusters, notebooks and jobs, however, we cannot authenticate with the SP even with the permissions granted on Databricks type of resources and the token being generated correctly (see gist).

Service principal code is as follows:

```
# Creating the Service Principal
resource "azuread_application" "databricks" {
  display_name = "${local.prefix}-databricks"
}

resource "azuread_service_principal" "databricks" {
  application_id = azuread_application.databricks.application_id
}

resource "random_string" "password" {
  length  = 64
  special = true
}

resource "azuread_service_principal_password" "databricks" {
  service_principal_id = azuread_service_principal.databricks.object_id
  value                = "${random_string.password.result}"
}

# Creating the role for databricks and the role assignment for service principal

resource "azurerm_role_definition" "databricks_sp_role" {
  name = "databricks-sp-role"
  description = "Role definition to enable workspace read on resource group for Databricks SP"

  permissions {
    actions = [      
      "Microsoft.Databricks/*"
    ]
    not_actions = []
  }

  scope = resource.azurerm_resource_group.databricks.id
  assignable_scopes = [resource.azurerm_resource_group.databricks.id]
}

resource "azurerm_role_assignment" "databricks_role_assignation" {
  scope = azurerm_resource_group.databricks.id
  role_definition_id = azurerm_role_definition.databricks_sp_role.role_definition_resource_id
  principal_id = azuread_service_principal.databricks.object_id
}

```

This might be a permissions issue but we can't find documentation that can help us solve the issue.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

```
Terraform v0.15.5
on linux_amd64

```
### Affected Resource(s)
Please list the resources as a list, for example:
```
- databricks_cluster
- databricks_secret_scope
- databricks_job
- databricks_acl
- databricks_notebook
- databricks_service_principal

```
If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files

Config on TFE as secrets.

### Debug Output

https://gist.github.com/JuanCepedaM/75f06855c7cbafea4441b2fab2070c5f

### Panic Output
If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Expected Behavior
Authenticated using SP to create all resources inside the recent Workspace.

### Actual Behavior
Though roles of databricks were granted to SP, it fails to authenticate.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
```
1. terraform plan works
2. terraform apply to create workspace with azurerm.
3. terraform apply again to add databricks workspace and resources (fails)
```

### Important Factoids
Are there anything atypical about your accounts that we should know? 

`None, regular azure account and tenant.`

**Comment by nfx** [comment]
@JuanCepedaM 

You cannot create secret scope by a principal

**Comment by JuanCepedaM** [comment]
@nfx Thanks for the reply, How should I create and authenticate?, before trying terraform I did this manually using the API and it worked.

Which permissions should I give the Service Principal to be able to create all the other resources, and how can I create a Secret Scope?.

**Comment by alexott** [comment]
KeyVault-baked secret scopes could be created only with user's AAD token - it's a limitation on Azure side, and it's clearly documented: https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/secret_scope#keyvault_metadata

**Comment by nfx** [comment]
@JuanCepedaM 

1. the version you're using is too old - `v0.3.2` - please switch to v0.3.7. 
2. service principal has to get `Contributor` role assignment
