### ISSUE TITLE
[DOC] https://registry.terraform.io/providers/databrickslabs/databricks/0.3.6/docs/resources/group doesnt include workspace_access argument

### ISSUE THREAD

**Issue by waqarkhankpmg** [databrickslabs/terraform-provider-databricks#766]
### Affected Resource(s)
databricks_group

### Expected Details
workspace_access is not documented

### List of things to potentially add/remove:
add workspace_access to args list
https://registry.terraform.io/providers/databrickslabs/databricks/0.3.6/docs/resources/group

**Comment by nfx** [comment]
@waqarkhankpmg PR welcome :)
