### ISSUE TITLE
[DOC] Explaining spark_version string in cluster resource usage example

### ISSUE THREAD

**Issue by masoncusack** [databrickslabs/terraform-provider-databricks#77]
I had some trouble finding a valid `spark_version` string for a cluster resource. 

It'd be nice if the generic format of the string, or a selection of valid options to use from which this could be inferred, were provided under [the usage example](https://databrickslabs.github.io/databricks-terraform/resources/cluster/#example-usage) in the cluster resource documentation.

I guess the choice of documenting a generic format or specific working examples should depend on whether all spark versions that a user can select in the Databricks UI will always be supported by the TF resource. If this ***is*** the case, users can just translate the details there into a valid string.

**Comment by stikkireddy** [comment]
Maybe a reference to this may help the user: https://docs.databricks.com/dev-tools/api/latest/index.html#runtime-version-strings

An additional help would be to add a data source object for the following api: https://docs.databricks.com/dev-tools/api/latest/clusters.html#runtime-versions

**Comment by masoncusack** [comment]
Agreed, these would be great additions.

**Comment by nfx** [comment]
closing in favor of #347
