### ISSUE TITLE
[ISSUE] Service Principal part of group does not have permissions on Secret scope

### ISSUE THREAD

**Issue by abij** [databrickslabs/terraform-provider-databricks#777]
### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_permissions
- databricks_service_principal
- databricks_group_member

The issue is more a Databricks bug, terraform is doing the right thing, not sure. whats the best place to report it:

- Group is created.
- SP is created
- SP is added to the group
- Group has READ access to Secret Scope.
- Group has Cluster-policy with rights CAN_USE
- Cluster policy has entry with a spark_conf with secret reference like: {{secret/scope_name/secret_key}}

```yaml
# This group contains a SP next to normal users

# For permissions it does work correclty:
resource "databricks_permissions" "policy_etl-job-singlenode" {
    cluster_policy_id = databricks_cluster_policy.etl-job-singlenode.id

    access_control {
        group_name = databricks_group.airflow.display_name
        permission_level = "CAN_USE"
    }
}

# But for secrets for the  group with an SP's does NOT work.
resource "databricks_secret_acl" "jdbc_airflow" {
    principal = databricks_group.airflow.display_name
    permission = "READ"
    scope = databricks_secret_scope.jdbc.name
}
```

**Issue:**
The SP _(hello airflow)_ can start a new Job cluster using the policy, but cannot access the secret scope, although its part of the Group with READ access!

**Workaround**
Add SP with the Client_ID to READ the scope.

```yaml
# Fix:
resource "databricks_secret_acl" "jdbc_airflow_sp" {
    principal = 'CLIENT UUID FROM THE SP'
    permission = "READ"
    scope = databricks_secret_scope.jdbc.name
}
```

**Comment by abij** [comment]
Lucky number?

**Comment by abij** [comment]
Extra note: the SP is part of the default group `users`, granting this group READ access to a Secret Scope will also not work for the SP.

**Comment by nfx** [comment]
@abij is this terraform problem or platform problem? :) did you raise the ticket already? :)

**Comment by abij** [comment]
No, sorry for the late response. It's a platform ticket. Can you point me to correct place to open ticket?
(I'll close ticket)

**Comment by nfx** [comment]
@abij contact your CSE :)
