### ISSUE TITLE
[ISSUE] "Inconsistent final plan" error when updating cluster local dependencies.

### ISSUE THREAD

**Issue by dugernierg** [databrickslabs/terraform-provider-databricks#780]
Hello,

I'm encountering a strange error whenever I upload a new version of a local wheel and add it to my cluster library. Whenever I update the local file, I'll get a `Error: Provider produced inconsistent final plan` for all the libraries listed on my cluster during the apply stage (see full error message below). However, the same terraform file will run without issue the second time around.

This bug only appeared with the latest version of the provider, as it was working fine with 0.3.6

### Resources Version
Terraform v0.15.4
databrick provider v0.3.7

### Affected Resource(s)
- databricks_cluster
- databricks_dbfs_file 

### Terraform Configuration Files
Shortened version of the terraform file, to reduce it to the relevant resources
```hcl

resource "databricks_dbfs_file" "my_library" {
  source = "${path.module}/dependencies/my_library.whl"
  path = "/FileStore/wheels/my_library.whl"
}

resource "databricks_cluster" "my_cluster" {
  cluster_name            = "my_cluster"
  spark_version           = "7.3.x-scala2.12"
  node_type_id            = "i3.xlarge"
  driver_node_type_id     = "i3.xlarge"
  autotermination_minutes = 20
  enable_local_disk_encryption = true

  spark_env_vars          = {
    PYSPARK_PYTHON = "/databricks/python3/bin/python3"
  }
  
  autoscale {
    min_workers = 1
    max_workers = 4
  }

  cluster_log_conf {
    dbfs {
      destination = "dbfs:/cluster-logs"
    }
  }  
  
  aws_attributes {
    instance_profile_arn    = local.instance_profile_arn
    availability            = "SPOT"
    first_on_demand         = 1
    spot_bid_price_percent  = 100
    zone_id                 = "eu-west-1"
  }

  library {
    whl = "dbfs://${databricks_dbfs_file.my_library.id}" 
  }
}
```

### Error message
```
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for databricks_cluster.my_cluster
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/databrickslabs/databricks" produced an invalid new
│ value for .library: planned set element
│ cty.ObjectVal(map[string]cty.Value{"cran":cty.ListValEmpty(cty.Object(map[string]cty.Type{"package":cty.String,
│ "repo":cty.String})), "egg":cty.NullVal(cty.String),
│ "jar":cty.NullVal(cty.String),
│ "maven":cty.ListValEmpty(cty.Object(map[string]cty.Type{"coordinates":cty.String,
│ "exclusions":cty.List(cty.String), "repo":cty.String})),
│ "pypi":cty.ListValEmpty(cty.Object(map[string]cty.Type{"package":cty.String,
│ "repo":cty.String})),
│ "whl":cty.StringVal("dbfs:///FileStore/wheels/my_library.whl")})
│ does not correlate with any element in actual.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
```

### Steps to reproduce
1. Create a databricks_dbfs_file for a local .whl
2. Add the file as a library of a databricks_cluster in the same project
3. terraform apply
4. modify the .whl
5. terraform apply

Thanks for the great work!
Kind regards,
G.D.

**Comment by nfx** [comment]
@dugernierg we're thinking about adding `databricks_library` resource in long term instead of `library` blocks - would you think it's a better approach?

**Comment by dugernierg** [comment]
@nfx Well, I don't know if I'm the right person to take that decision, but since you ask me to weight in on the matter:

On one hand, I can see `databricks_library` to make logical sense as a separate resource unit. On the other hand, if a cluster has a lot of libraries attached to it, it will significantly lengthen the overall terraform file since the user would have to repeat the cluster id inside every  `databricks_library` resource. If the goal is to limit the length of a single  `databricks_cluster` declaration, maybe the right middleground would be a  `databricks_libraries` instead, that would look something like this:

```
resource "databricks_libraries" "my_libraries" {
   cluster = databricks_cluster.my_cluster.cluster_id
   libraries = {
       "pypi": [
          "foo>=1.0.0", 
          "bar = 2.1"
       ]
       "maven": [
          "baz >= 3.16"
       ]
       "whl": [
          "dbfs://path/to/my/wheel.whl"
       ]
       "jar": [
          "dbfs://path/to/my/jar.jar"
       ]
   }
}
```  
I'm using a map here so it can be declared as an environment variable and be reused on multiple clusters.

Now it's coming from a purely front user experience, it might not make sense with how things run in the background. 

I'm not sure if it has any bearing on the aforementioned bug though.

**Comment by nfx** [comment]
@dugernierg `databricks_libraries` won't happen - it'll have the same problems as `library` block.

**Comment by shivanigoyal0705** [comment]
Hi @dugernierg - I have similar setup and I am also getting same error 👍  Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for databricks_job.dbr_job_data_account_streaming
│ to include new values learned so far during apply, provider
│ "registry.terraform.io/databricks/databricks" produced an invalid new value
│ for .task[1].library: planned set element
│ cty.ObjectVal(map[string]cty.Value{"cran":cty.ListValEmpty(cty.Object(map[string]cty.Type{"package":cty.String,
│ "repo":cty.String})), "egg":cty.NullVal(cty.String),
│ "jar":cty.NullVal(cty.String),
│ "maven":cty.ListValEmpty(cty.Object(map[string]cty.Type{"coordinates":cty.String,
│ "exclusions":cty.List(cty.String), "repo":cty.String})),
│ "pypi":cty.ListVal([]cty.Value{cty.ObjectVal(map[string]cty.Value{"package":cty.StringVal("requests==2.28.2"),
│ "repo":cty.NullVal(cty.String)})}), "whl":cty.NullVal(cty.String)}) does
│ not correlate with any element in actual.
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

Is there any solution found for above problem?
