### ISSUE TITLE
Validation slow with multiple mountpoints

### ISSUE THREAD

**Issue by epa095** [databrickslabs/terraform-provider-databricks#784]
In
https://github.com/databrickslabs/terraform-provider-databricks/blob/dfa5e81875d17e6c806f814c414f09859dd0dbdc/storage/mounts.go#L35 the function `dbutils.fs.refreshMounts()` is called multiple times. This function is quite slow (ca 20 seconds for me), and running many of them makes validation very slow. Maybe its possible to make it such that it is ran only once?

**Comment by nfx** [comment]
@epa095 without refreshing mounts we can't guarantee the consistency state of removing or changing mounts. It'll going to be transparently replaced once proper REST API for mounts is there
