### ISSUE TITLE
[ISSUE] we can not provison databricks cluster through this provider

### ISSUE THREAD

**Issue by sunscorch** [databrickslabs/terraform-provider-databricks#786]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
+ provider registry.terraform.io/databrickslabs/databricks v0.3.7
+ provider registry.terraform.io/hashicorp/azurerm v2.72.0

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_cluster

### Environment variable names
To get relevant environment variable _names_ please copypaste the output of the following command:
`$ env | sort | grep -E 'DATABRICKS|AWS|AZURE|ARM|TEST' | awk -F= '{print $1}'`

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Debug Output
Please add turn on logging, e.g. `TF_LOG=DEBUG terraform apply` and run command again, paste it to gist & provide the link to gist. If you're still willing to paste in log output, make sure you provide only relevant log lines with requests.

It would make it more readable, if you pipe the log through `| grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'`, e.g.:

```
TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
main.tf:
```
terraform {
  required_providers {

    databricks = {
      source = "databrickslabs/databricks"
      version = "0.3.7"
    }
  }
}



provider "databricks" {
  host = "https://adb-8583429878437803.3.azuredatabricks.net/"
  token = "....."
}


data "databricks_current_user" "me" {}
data "databricks_spark_version" "latest" {}
data "databricks_node_type" "smallest" {
  local_disk = true
}

resource "databricks_cluster" "test123" {
  cluster_name            = "test123"
  spark_version           = data.databricks_spark_version.latest.id
  node_type_id            = data.databricks_node_type.smallest.id
  autotermination_minutes = "10"
  autoscale {
    min_workers = 1
    max_workers = 2
  }
}
```
 `terraform apply`

we get error:
``
Error: 0820-011931-hosts996 is not able to transition from TERMINATED to RUNNING: Self-bootstrap failure during launch. Please try again later and contact Databricks if the problem persists. databricks_error_message: Self-bootstrap failure during launch. Please try again later a..., Termination info: code: SELF_BOOTSTRAP_FAILURE, type: , parameters: map[databricks_error_message:Self-bootstrap failure during launch. Please try again later and contact Databricks if the problem persists. Node daemon fast failed and did not answer ping for instance 19b618560fb74fef82647d7535e82c76]. Please see https://docs.databricks.com/dev-tools/api/latest/clusters.html#clusterclusterstate for more details
│
│   with databricks_cluster.test123,
│   on main.tf line 25, in resource "databricks_cluster" "test123":
│   25: resource "databricks_cluster" "test123" {
``

### Important Factoids
Are there anything atypical about your accounts that we should know?

**Comment by alexott** [comment]
looks like general backend problem not related to terraform.

P.S. Please revoke your personal access token that was used here.  And in general either use [environment variables](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs#environment-variables) or use `~/.databrickscfg` file that is used by `databricks-cli`

**Comment by nfx** [comment]
@sunscorch Please contact support with error message you've received
