### ISSUE TITLE
[FEATURE]: Use a ephemeral job cluster for mount checking.

### ISSUE THREAD

**Issue by epa095** [databrickslabs/terraform-provider-databricks#795]
The checking of mounts for `databricks_azure_adls_gen2_mount ` take a long time with many mounts. With several concurrent PRs all checking the mounts, the mount-checking-cluster either scales to many many many nodes (if allowed), or PRs start to time out. If *each* PR could make their **own** ephemeral cluster (like the job-clusteres) then the different PRs would at least not interfer with each other.

### Affected Resource(s)
- databricks_azure_adls_gen2_mount (and also maybe other mounts)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
- Have 20 mounts.
- Make several concurrent calls to terraform validation

**Comment by nfx** [comment]
@epa095 Please create a bigger dedicated mounting cluster and specify it via existing cluster id attribute
