### ISSUE TITLE
[DOC] Link doesn't go to correct page 

### ISSUE THREAD

**Issue by johnc1996** [databrickslabs/terraform-provider-databricks#796]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general Terraform questions, please see: https://www.terraform.io/community.html.
This template is for both adding enhancement as well as pointing out issues with the provider documentation.

### Affected Resource(s)
https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/mws_workspaces
https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/mws_workspaces#workspace-with-databricks-managed-vpc

![screenshot-registry terraform io-2021 08 23-15_36_04](https://user-images.githubusercontent.com/55280089/130467902-cc2363e6-013b-4397-a8b2-d806c595e607.png)

Screenshot of the text that contains the link that goes to the incorrect page.

### Expected Details
The link highlighted in the screenshot takes the user to https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/notebook and not https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/mws_networks as expected

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] The text link of `databricks_mws_networks` takes the user to https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/mws_networks

**Comment by johnc1996** [comment]
Have just checked and the link still appears to be going to the wrong page

**Comment by alexott** [comment]
@johnc1996 it's not published yet.

**Comment by johnc1996** [comment]
@alexott ah thankyou
