### ISSUE TITLE
Error: Failed to install provider

### ISSUE THREAD

**Issue by Saikishore031** [databrickslabs/terraform-provider-databricks#804]
Trying to initialise the terraform for databricks but no luck, can you please help on this
<img width="557" alt="Capture" src="https://user-images.githubusercontent.com/50044342/130792645-06c0cbe4-1d96-400d-aa6f-6e2ce34436f3.PNG">

C:\Temp\Terraform\Test>terraform init -upgrade

Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching "2.29.0"...
- Finding databrickslabs/databricks versions matching "0.2.5"...
- Installing hashicorp/azurerm v2.29.0...
- Installed hashicorp/azurerm v2.29.0 (signed by HashiCorp)
- Installing databrickslabs/databricks v0.2.5...
╷
│ Error: Failed to install provider
│
│ Error while installing databrickslabs/databricks v0.2.5: archive has incorrect checksum
│ zh:2f07856c16054577156374448b63341223bbb088390df03fb0caf71ec9c1dc39 (expected
│ zh:d41a1c5d55931398db312ae567d1e435e01c7b6e898c87d2834ff18c857b28c6)

**Comment by nfx** [comment]
@Saikishore031 version is too old and no longer in support. please upgrade to 0.3.7
