### ISSUE TITLE
Error: Failed to install provider databricks

### ISSUE THREAD

**Issue by Saikishore031** [databrickslabs/terraform-provider-databricks#805]
still am facing the same issue please find the screenshot below 

![image](https://user-images.githubusercontent.com/50044342/130795952-c4f5bcd6-9e53-46fd-b344-5c849dbd0043.png)

C:\Temp\Terraform\Test>terraform init

Initializing the backend...

Initializing provider plugins...
- Finding databrickslabs/databricks versions matching "0.3.7"...
- Reusing previous version of hashicorp/azurerm from the dependency lock file
- Using previously-installed hashicorp/azurerm v2.73.0
- Installing databrickslabs/databricks v0.3.7...
╷
│ Error: Failed to install provider
│
│ Error while installing databrickslabs/databricks v0.3.7: archive has incorrect checksum
│ zh:298e63588879abf0dd4c8b5610312ac0644c806d2bda102ee3bcfb7f7eaa13a5 (expected
│ zh:fd2b875e9949371a0fb33c98565d352806ef8b448c8f0198acdae2e541712d5f)

**Comment by nfx** [comment]
what terraform version do you have? it looks like a general terraform question, ask it on discuss.hashicorp.com

**Comment by Saikishore031** [comment]
C:\Temp\Terraform\Test>terraform -version
Terraform v1.0.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.73.0

**Comment by Saikishore031** [comment]
> what terraform version do you have? it looks like a general terraform question, ask it on discuss.hashicorp.com

C:\Temp\Terraform\Test>terraform -version
Terraform v1.0.5
on windows_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.73.0
