### ISSUE TITLE
[DOC] Reference to databricks_mws_private_access_settings resource in docs

### ISSUE THREAD

**Issue by davehowell** [databrickslabs/terraform-provider-databricks#807]
### Affected Resource(s)
databricks_mws_vpc_endpoint
https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/mws_vpc_endpoint

This part ->
> Typically the next steps after this would be to create a [databricks_mws_private_access_settings](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/databricks_mws_private_access_settings) 

### Expected Details
The link to [databricks_mws_private_access_settings](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/databricks_mws_private_access_settings) resource goes to a page that says `This documentation page doesn't exist for version 0.3.7 of the databricks provider.` and on double checking I can't see the resource anywhere so I suppose the docs are outdated and that phrase referencing it should be removed.

### List of things to potentially add/remove:
I would change that section to the following (removed `databricks_mws_private_access_settings` references)

Typically the next steps after this would be to create a databricks_mws_networks configuration, before passing the databricks_mws_networks.this.network_id into a databricks_mws_workspaces resource:

resource "databricks_mws_workspaces" "this" {
  provider                   = databricks.mws
  account_id                 = var.databricks_account_id
  aws_region                 = var.region
  workspace_name             = local.prefix
  deployment_name            = local.prefix
  credentials_id             = databricks_mws_credentials.this.credentials_id
  storage_configuration_id   = databricks_mws_storage_configurations.this.storage_configuration_id
  network_id                 = databricks_mws_networks.this.network_id
  pricing_tier               = "ENTERPRISE"
  depends_on                 = [databricks_mws_networks.this]
}

### Important Factoids
Any links to external documentation that may prove your case, i.e Databricks public docs or Terraform public docs. 

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- #158

**Comment by neilpvirtualitics** [comment]
service_names are per-region as documented here: https://docs.databricks.com/en/resources/ip-domain-region.html#privatelink

Which is referenced in Step 2 Create VPC Endpoints (step 6) in the private link document: https://docs.databricks.com/en/security/network/classic/privatelink.html#back-end-connection-networking-requirements

This was difficult to find.
