### ISSUE TITLE
[ISSUE] Provider issue - Cannot delete databricks_permissions for job with error "Principal name not defined"

### ISSUE THREAD

**Issue by Hidoshi1** [databrickslabs/terraform-provider-databricks#822]
### Configuration
```hcl
resource "databricks_permissions" "test_permission" {
  job_id = databricks_job.test_job.id

  access_control {
    permission_level = "CAN_VIEW"
    group_name       = databricks_group.job-monitoring.display_name
  }
}
```

### Expected Behavior
Deleting the code block should delete the `databricks_permission` resource.

### Actual Behavior
`terraform plan` shows that the resource will be deleted, but running `terraform apply` results in the following error:

"Error: Principal name not defined"

Terraform plan:
```
# module.test_module.databricks_permissions.test_permission will be destroyed
  - resource "databricks_permissions" "test_permission" {
      - id          = "/jobs/1221" -> null
      - job_id      = "1221" -> null
      - object_type = "job" -> null

      - access_control {
          - permission_level = "CAN_VIEW" -> null
          - group_name        = "job-monitoring" -> null
        }
    }
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Declare a `databricks_permission` resource against a job, and run `terraform apply` to create it
2. Remove the code block and run `terraform apply` to destroy it

### Terraform and provider versions
Terraform v0.15.1
on darwin_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.3.7
+ provider registry.terraform.io/hashicorp/random v3.1.0

### Debug Output
Not willing to paste output.

### Important Factoids
N/A

### Other info
- The error occurs with both `user_name` and `group_name` specified for the resource.
- The error only occurs when deleting the entire resource. If the resource had multiple access controls declared, removing one of them did not result in the error, and successfully modified the job's permissions.

**Comment by nfx** [comment]
@Hidoshi1 I'm afraid issue has too little context. Is group/user deleted before deleting permissions? We need debug output

**Comment by nfx** [comment]
closing the issue, as the reporter failed to provide the necessary context. Please open the new issue if problem persists.
