### ISSUE TITLE
[FEATURE REQUEST] TFLint ruleset

### ISSUE THREAD

**Issue by jtaylor100** [databrickslabs/terraform-provider-databricks#829]
Currently I am using rules from the databricks provider in a CI/CD pipeline.

It would be great to have a layer of static code analysis to provide faster feedback, for obvious errors. For example: wrong attribute names on resource and data blocks.

Plugin rulesets for [tflint](https://github.com/terraform-linters/tflint) are currently in development for other providers for popular cloud platforms. A tflint ruleset for this provider would provide static code analysis.

Does such a plugin exist? If not, does anybody have any plans to create one? Potentially something I could look into if nobody already has it started.

**Comment by nfx** [comment]
@jtaylor100 team on our end doesn't have cycles to take on this feature request, but we'll be happy to support you if you decide to implement it.
