### ISSUE TITLE
[ISSUE] databricks_secret_scope failing at first attempt

### ISSUE THREAD

**Issue by davkohli** [databrickslabs/terraform-provider-databricks#835]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Configuration
```hcl
module "adb01" {
  source = "../.."

  resource_group_name        = local.resource_group
  adb_managed_resource_group = local.adb_managed_resource_group
  platform_name              = local.platform_name
  functional_role            = local.functional_role
  environment_name           = local.environment_name
  location                   = local.location
  tags                       = local.tags
}

provider "databricks" {
  azure_workspace_resource_id = module.adb01.id
  azure_client_id             = local.client_id
  azure_client_secret         = var.client_secret
  azure_tenant_id             = local.tenant_id
}

resource "azurerm_role_assignment" "adb" {
  scope                = module.adb01.id
  role_definition_name = "Contributor"
  principal_id         = local.object_id

  depends_on           = [module.adb01]
}

resource "azurerm_storage_account" "this" {
  name                     = "strgtfmdatalake001"
  resource_group_name      = local.resource_group
  location                 = local.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  min_tls_version          = "TLS1_2"
  is_hns_enabled           = true
}

resource "azurerm_role_assignment" "storage" {
  scope                = azurerm_storage_account.this.id
  role_definition_name = "Storage Blob Data Contributor"
  principal_id         = local.object_id

  depends_on = [azurerm_storage_account.this]
}

resource "time_sleep" "wait_timer1" {
  create_duration = "180s"

  depends_on = [azurerm_role_assignment.adb]
}

resource "databricks_secret_scope" "secret_scope" {
  name                     = "databricks1-scope"
  depends_on = [time_sleep.wait_timer1]
}

resource "databricks_secret_acl" "test_acl" {
  principal = "davinder.kohli@coles.com.au"
  permission = "MANAGE"
  scope = databricks_secret_scope.secret_scope.name

  depends_on = [databricks_secret_scope.secret_scope]
}

resource "databricks_secret" "token" {
  string_value = var.client_secret
  scope        = databricks_secret_scope.secret_scope.id
  key          = "dbtokenkey"

  depends_on = [time_sleep.wait_timer1]
}

resource "azurerm_storage_container" "this" {
  name                  = "strgcntr001"
  storage_account_name  = azurerm_storage_account.this.name
  container_access_type = "private"

  depends_on = [time_sleep.wait_timer1]
}

resource "databricks_azure_adls_gen2_mount" "this" {
  container_name         = azurerm_storage_container.this.name
  storage_account_name   = azurerm_storage_account.this.name
  mount_name             = "demo902"
  tenant_id              = local.tenant_id
  client_id              = local.client_id
  client_secret_scope    = databricks_secret_scope.secret_scope.name #tfsec:ignore:GEN003:exp:2023-01-01
  client_secret_key      = databricks_secret.token.key               #tfsec:ignore:GEN003:exp:2023-01-01
  initialize_file_system = true

  depends_on = [databricks_secret_scope.secret_scope]
}
```

### Expected Behavior
What should have happened?
Secret_Scope should be created

### Actual Behavior
What actually happened?
Secret_Scope creation failed after 30 seconds with timeout error.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

Gives Error

2. `terraform apply`
Complete without issue

### Terraform and provider versions
Terraform v1.0.7
databricks version = "~>0.3.7"

### Debug Output
https://gist.github.com/davkohli/24a1a47b3838867591964ca6c46ee2e4

### More Details

The secret_scope creation failed at first attempt, but subsequent attempt it works file.
I have tested with 3-10 minutes sleep time after creation of databricks workspace and giving role assignment, but no luck.

Thanks,
DK

**Comment by nfx** [comment]
@davkohli Please provide http debug logs

**Comment by davkohli** [comment]
Hi @nfx 

Thanks for your reply. Is there any document to generate http debug logs?

Thanks,
DK

**Comment by nfx** [comment]
@davkohli Terraform registry starting page should have one

**Comment by davkohli** [comment]
Hi @nfx 
I had provided logs as per the issue creation - https://gist.github.com/davkohli/24a1a47b3838867591964ca6c46ee2e4
I could not find anything relevant which states specifically about http logs.

Thanks,
DK

**Comment by nfx** [comment]
ah, i see what kind of timeout did you mean: `Post "https://adb-XXX.azuredatabricks.net/api/2.0/secrets/scopes/create": net/http: TLS handshake timeout`. My first guess is that DNS CNAME is not yet resolvable from the machine you're running TF. Could you try temporarily commenting out databricks resources, then reach databricks workspace through UI, then uncomment resources and see if TLS handshake issue persists? Most likely there's some proxy within the network, that obscures reachability, but you have to verify that. Technically, we can add a configurable option to tune TLS timeouts, but there are so many unknowns...

can you also try changing couple of things:

```hcl
provider "databricks" {
  host = module.adb01.workspace_url // workspace_url from azurerm_databricks_workspace instead if ID
  azure_client_id             = local.client_id
  azure_client_secret     = var.client_secret
  azure_tenant_id           = local.tenant_id
}
```

i'm not sure if you really need all those timers and `depends_on` meta-arguments, as TF should resolve DAG just fine.
