### ISSUE TITLE
[ISSUE] Inconsistent user groups deployment/state

### ISSUE THREAD

**Issue by masoncusack** [databrickslabs/terraform-provider-databricks#84]
### Terraform Version
0.12.26

### Affected Resource(s)
- databricks_scim_group (possibly)
- databricks_secret_scope (possibly)
- databricks_secret_acl (possibly)

### Terraform Configuration Files
```hcl
provider "databricks" {
  host  = var.databricks_host
  token = var.databricks_api_token
}

resource "databricks_scim_group" "privileged-user-group" {
  display_name = "Privileged user group"
}

resource "databricks_secret_scope" "privileged-scope" {
  name = "privileged-secret-scope"
}

resource "databricks_secret_acl" "privileged-acl" {
   principal = "Privileged user group"
   permission = "READ"
   scope = databricks_secret_scope.privileged-scope.name
}

resource "databricks_cluster" "standard_cluster" {
  cluster_name  = "standard-cluster"
  spark_version = "6.4.x-scala2.11"
  node_type_id = "Standard_DS13_v2"
  autoscale {
    min_workers = 1
    max_workers = 3
  }
  library_whl {
    path = "dbfs:/custom-whls/my_custom_whl.whl"
  }

}

# Create high concurrency cluster with AAD credential passthrough enabled
resource "databricks_cluster" "high_concurrency_cluster" {
  cluster_name  = "high-concurrency-cluster"
  spark_version = "6.4.x-scala2.11"
  node_type_id = "Standard_DS13_v2"
  autoscale {
    min_workers = 1
    max_workers = 3
  }
  spark_conf = {
    "spark.databricks.cluster.profile": "serverless"
    "spark.databricks.repl.allowedLanguages": "python, sql"
    "spark.databricks.passthrough.enabled": true
    "spark.databricks.pyspark.enableProcessIsolation": true
  }
}

 resource "databricks_notebook" "notebook" {
   content = base64encode("# Welcome to your Jupyter notebook")
   path = "/mynotebook"
   overwrite = false
   mkdirs = true
   language = "PYTHON"
   format = "SOURCE"
}
```

### Debug Output
https://gist.github.com/masoncusack/3806347b0ef5ed873ac77689c63a4ab6

### Expected Behavior
It should be recognised that a user group has been destroyed.

### Actual Behavior
TF seems to hold the user group as part of the present state even though it's been deleted, causing future plan/applies to fail with error "Error: status 400: err Response from server {"error_code":"INVALID_PARAMETER_VALUE","message":"User or Group Privileged user group does not exist."}"

If we look in tfstate, the associated acl resource seems to still exist. Perhaps this wasn't successfully deleted by `tf destroy`?

```hcl
  "resources": [
    {
      "mode": "managed",
      "type": "databricks_secret_acl",
      "name": "privileged-acl",
      "provider": "provider.databricks",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "id": "privileged-secret-scope|||Privileged user group",
            "permission": "READ",
            "principal": "Privileged user group",
            "scope": "privileged-secret-scope"
          }
        }
      ]
    },
```

### Steps to Reproduce
1. `terraform apply` (with associated `databricks_scim_group`, `secret_scope`, and `secret_acl` resources in main.tf)
2. `terraform destroy`
3. terraform apply
NOTE: this may be a periodic issue. I believe the "destroy" operation and subsequent applies have succeeded before with the same config.

**Comment by masoncusack** [comment]
I'm noticing that secret scopes aren't deleted by `terraform destroy`, which also causes crashes and inconsistent state.

**Comment by masoncusack** [comment]
Hi, is it not possible to smoothly apply and destroy these interdependent resources? This was the main issue I was coming across. A general destroy will cause errors on later applies because the user group no longer exists. We know that it no longer exists and this is the desired state, but why does the apply fail?

Perhaps this is a known issue that can't be fixed?
Could we mandate that `depends_on` is set for the resources which depend on the pre-existence of a principle?

**Comment by nfx** [comment]
This will go under the story of "combined resources", which will always have an "existence check". Should be part of bigger refactoring, along with migrating format of id separators.

**Comment by nfx** [comment]
@masoncusack would it be okay for you to rewrite the code with `databricks_group` instead of `databricks_scim_group`? this might help us removing this resource in v0.3 and have more stable user experience overall.

**Comment by nfx** [comment]
@masoncusack https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/resources/group.md
