### ISSUE TITLE
[ISSUE] allow_sql_analytics_access should be renamed

### ISSUE THREAD

**Issue by bilalaslamseattle** [databrickslabs/terraform-provider-databricks#844]
It's confusing that the property name for enabling Databricks SQL is `allow_sql_analytics_access`, whereas the product name is Databricks SQL. The property name should be `allow_db_sql_access`.

**Comment by nfx** [comment]
@bilalaslamseattle This would only be done in v0.4.0 or v1.0.0, as we have to maintain schema backwards compatibility within major versions

**Comment by bilalaslamseattle** [comment]
Roger that.
