### ISSUE TITLE
[ISSUE] Unable to Create Databricks Repo with v0.3.8

### ISSUE THREAD

**Issue by troyinsight** [databrickslabs/terraform-provider-databricks#852]
Howdy,

I'm trying to set up a new Repo within Databricks, pointing to a private GitHub repository. I have manually created a GitHub PAT and set up my Git Integration to use this. I can manually create the Repo using the Databricks UI. Trying to create the repo via Terraform fails with an 'Invalid access token' error.

### Configuration
```hcl
provider "databricks" {
  host  = module.databricks_workspace.workspace_url
}
```

### Expected Behavior
Creates a new Repo linked to my GitHub repository.

### Actual Behavior
I receive an error stating: Error: Invalid access token

### Steps to Reproduce
1. Create PAT token within GitHub
2. Update Git Integration to use this token
3. `terraform apply`

### Terraform and provider versions
Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.3.8
+ provider registry.terraform.io/hashicorp/azuread v2.6.0
+ provider registry.terraform.io/hashicorp/azurerm v2.79.1
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/integrations/github v4.16.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.7

**Comment by troyinsight** [comment]
Thanks guys. I'm just doing some more testing this morning. I totally understand that at this stage we need to manually add our GitHub PAT token into the workspace, which I have done. As mentioned, I can create the repo within the Databricks UI and it works fine. As a test I've also tried using Terraform to create a Repo pointing to a different (and Public) GitHub repository. This didn't work either, so it doesn't seem to matter if the GitHub repo is public or private. I'll post a Gist soon.

**Comment by alexott** [comment]
Hmmmm, it’s strange - for cluster I see azcli auth, but not for repos. Can you post your terraform code to alexey.ott at databricks.com

**Comment by nfx** [comment]
@alexott aren't you on vacation? 🥸🤫

**Comment by nfx** [comment]
@troyinsight can you confirm that provider has no initialization in the module with a repo declaration? And it works, once you explicitly pass the host of the workspace? 

I've reopened #821 to make auth messages less confusing.
