### ISSUE TITLE
Support Data Access configuration for SQL endpoint (Azure)

### ISSUE THREAD

**Issue by planetjones** [databrickslabs/terraform-provider-databricks#855]
I cannot find the option to terraform the Service Principal configuration in Databricks SQL on Azure.  This is in the SQL Endpoint Settings of the admin console:

![image](https://user-images.githubusercontent.com/56391/136996773-ea051c00-0f7a-46cc-ac71-db074a2c492d.png)

Can support for this be added to the provider please?

**Comment by alexott** [comment]
Just for reference: https://docs.databricks.com/sql/api/sql-endpoints.html#global-sql-endpoints-api & https://docs.microsoft.com/en-us/azure/databricks/sql/api/sql-endpoints#global-sql-endpoints-api
