### ISSUE TITLE
GCP to databricks workspace creation - SA authentication

### ISSUE THREAD

**Issue by abdulhkhan** [databrickslabs/terraform-provider-databricks#859]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Configuration
```hcl
data "google_client_openid_userinfo" "me" {}
data "google_client_config" "current" {}

resource "databricks_mws_workspaces" "this" {
  provider       = databricks.accounts
  account_id     = var.databricks_account_id
  workspace_name = "my-workspace"
  location       = data.google_client_config.current.region
  cloud_resource_bucket {
    gcp {
      project_id = var.google_project
    }
  }
}
```

### Expected Behavior
authenticate using GCP service account, allowing databricks to use GCP SA login.
### Actual Behavior

Errors out with following:
```bash
╷
│ Error: failed to get oidc token: impersonate: status code 404: {
│   "error": {
│     "code": 404,
│     "message": "Requested entity was not found.",
│     "status": "NOT_FOUND"
│   }
│ }
│
│
│   with databricks_mws_workspaces.this,
│   on main.tf line 52, in resource "databricks_mws_workspaces" "this":
│   52: resource "databricks_mws_workspaces" "this" {
│
```
### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions

Please paste the output of `terraform version`. If version of `databricks` provider is not the latest (https://github.com/databrickslabs/terraform-provider-databricks/releases), please make sure to use the latest one.

```bash
Terraform v1.0.8
on darwin_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.3.7
+ provider registry.terraform.io/hashicorp/google v3.5.0
+ provider registry.terraform.io/hashicorp/google-beta v3.87.0

Your version of Terraform is out of date! The latest version
is 1.0.9. You can update by downloading from https://www.terraform.io/downloads.html
```

**Comment by nfx** [comment]
@abdulhkhan Credentials files are currently not supported, only default application credentials would work

**Comment by abdulhkhan** [comment]
@nfx - are you recommending SA impersonation for GCP authentication?

**Comment by abdulhkhan** [comment]
@nfx Thanks for the information! I am able to proceed, however after the workspace is created, unable to add group or users. If this needs to be different issue, I can open it. You may close this issue.

Thanks 
Abdul!

**Comment by nfx** [comment]
@abdulhkhan glad that you're unblocked! :) 

it's strange that you cannot add groups/users, as pre-release integration tests say everything is working fine:

```
 identity/acceptance.TestAccGroupMemberResource (10.30s)
 identity/acceptance.TestAccGroupResource (10.58s)
 identity/acceptance.TestAccGroupResource_verify_entitlements (6.84s)
 identity/acceptance.TestAccTokenResource (6.12s)
 identity/acceptance.TestAccUserResource (7.43s)
```

Make sure that you have one module for creating workspace and another module for working with everything within that workspace (creating a separate instance of provider in that second module configured over the `workspace_url` output returned by `databricks_mws_workspaces`)

Auth docs may be helpful. Please also debug with `debug_headers` configured temporarily, as you'd need to see what host are you talking to - https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs#debug_headers

https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs#data-resources-and-authentication-is-not-configured-errors

Closing this issue, as please try to TF_LOG=DEBUG and contact your Databricks Solution Architect if problems persist - they should already have some basic TF troubleshooting skills.
