### ISSUE TITLE
[ISSUE] Automatically create folder if it does not exist in databricks_repo

### ISSUE THREAD

**Issue by Freia3** [databrickslabs/terraform-provider-databricks#862]
I want to add a repository to my databricks workspace and I want to put the checked out Repo anywhere **outside** my user's repo directory. However, when I specify a path in databricks_repo, I get an error the path is invalid, because the folder does not exist yet. I don't want to manually add a folder to the the repos all of my databricks workspaces. Is it possible to automatically create the folder if it does not exist yet?

### Configuration
```hcl
resource "databricks_repo" "databricks_client_repo" {
  url = "path_to_repo"
  path="/Repos/Client-Repo/repo_name"
  branch="master"
}
```

### Expected Behavior
Repository should have been added to the folder 'Client-Repo'

### Actual Behavior

│ Error: RESOURCE_DOES_NOT_EXIST: Parent directory /Repos/Client-Repo does not exist.
│ 
│   with databricks_repo.databricks_client_repo,
│   on main.tf line 89, in resource "databricks_repo" "databricks_client_repo":
│   89: resource "databricks_repo" "databricks_client_repo" {

### Steps to Reproduce
 `terraform apply`

### Terraform and provider versions
databrickslabs/databricks 0.3.9

**Comment by alexott** [comment]
By default it's creating in the user's folder. You can use `databricks_directory` to pre-create "non-standard" directories. But I'll look if it's possible to fix the code for that
