### ISSUE TITLE
[DOC][FEATURE][AWS] Repo Directory & Security 

### ISSUE THREAD

**Issue by jordancparker** [databrickslabs/terraform-provider-databricks#875]
Hello,

I have been reading the docs extensively, which identifies that a URL is "REQUIRED" as stated below:
The following arguments are supported:
url - (Required) The URL of the Git Repository to clone from. If value changes, repo is re-created

However i do not want to deploy a repo i just want to build the directory alot like :
https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/directory
https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/permissions#repos-usage
I want to add permissons to the Repo Directory like the below
https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/permissions#folder-usage

#Solved : 

The solution i found was to add "/Repos/******" infront of the databricks_directory and the add databricks_permissions as if it was a workspace directory. 

Please update your docs accordingly to help others find this functionality.

**Comment by nfx** [comment]
if `directory_path` works, why do we need to build `databricks_repo_directory`?

**Comment by jordancparker** [comment]
Hi @nfx 

I have no need for this functionality now. 

But im unsure everyone is going to start inspecting the Databricks GUI and debug the api's you send to work out Repos are actually an extension of the workspace directory API. Or the fact you can use the security control on a Directory_Path made Repo.

Subsequently i would recommend you update the Documentation to explain this can be achieved with directory path or build its own stanza for clear usage.

**Comment by nfx** [comment]
technically, adding `repo_path` is very simple

`{"repo_path", "repo", "repos", []string{"CAN_READ", "CAN_RUN", "CAN_EDIT", "CAN_MANAGE"}, PATH},`

@kivanc-databricks , this is your very simple go task ;)
