### ISSUE TITLE
[ISSUE] databricks_aws_s3_mount does not use an existing cluster if cluster_id is specified

### ISSUE THREAD

**Issue by SrihasaAkepati** [databrickslabs/terraform-provider-databricks#876]
Hi there,

databricks_aws_s3_mount resource to mount s3 bucket starts a new cluster starts even if cluster_id is specified. It does say it force replaces the cluster but it always starts a new cluster and uses the same new cluster if the operation is attempted couple of times. If i try to replace the tfstate file with existing cluster id, it still goes with new cluster. 

### Configuration
```hcl

resource "databricks_aws_s3_mount" "this" {
    cluster_id = "0503-221624-suing406"
    instance_profile = "arn:aws:iam::826763667205:instance-profile/SSE2383-iam-srihas-s3-roleIP"
    s3_bucket_name = "srihasr-test"
    mount_name = "exp"
}
```

### Expected Behavior
What should have happened?

If cluster_id is specified, new cluster should not be started/used. 

https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/aws_s3_mount#cluster_id

### Actual Behavior
What actually happened?

Terraform will perform the following actions:

  databricks_aws_s3_mount.this must be replaced
-/+ resource "databricks_aws_s3_mount" "this" {
      ~ cluster_id       = "1027-212500-9laj6vgj" -> "0503-221624-suing406" # forces replacement
      ~ id               = "exp" -> (known after apply)
      ~ source           = "s3a://srihasr-test" -> (known after apply)
        # (3 unchanged attributes hidden)
    }

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` on databricks_aws_s3_mount block mentioned above

### Terraform and provider versions

Terraform v1.0.9
on darwin_amd64

Provider version -

terraform {
  required_providers {
    databricks = {
      source = "databrickslabs/databricks"
      version = "0.3.9"
    }
  }
}

### Debug Output

2021-10-28T12:56:59.655+0530 [WARN]  Provider "registry.terraform.io/databrickslabs/databricks" produced an unexpected new value for databricks_aws_s3_mount.this during refresh.
      - .cluster_id: was cty.StringVal("0503-221624-suing406"), but now cty.StringVal("1027-212500-9laj6vgj")
2021-10-28T13:00:16.750+0530 [WARN]  Provider "provider[\"registry.terraform.io/databrickslabs/databricks\"]" produced an unexpected new value for databricks_aws_s3_mount.this, but we are tolerating it because it is using the legacy plugin SDK.
    The following problems may be the cause of any confusing errors from downstream operations:
      - .cluster_id: was cty.StringVal("0503-221624-suing406"), but now cty.StringVal("1027-212500-9laj6vgj")

**Comment by nfx** [comment]
Fixed in #737
