### ISSUE TITLE
[ISSUE] `databricks_secret_acl` scope property validation does not allow `/` characters

### ISSUE THREAD

**Issue by tylangesmith** [databrickslabs/terraform-provider-databricks#888]
Hey there, using the `databricks_secret_acl` resource I'm coming across a few scope validation issues.

The Databricks CLI / API allows for scopes to be created with a `/` character, this behaviour however is not consistent with the validation observed against this terraform `databricks_secret_acl` resource.

### Configuration
```hcl
resource "databricks_secret_acl" "scope_acl1" {
  principal  = databricks_group.developers.display_name
  permission = "READ"
  scope      = "myapplication/master"
}
```

### Expected Behavior

I expect the validation of the scope `"myapplication/master"` to be valid which is inline with the API.

### Actual Behavior

An error is thrown by the resource indicating the scopes `"myapplication/master"` is invalid.

> Error: invalid value for scope (Must consist of alphanumeric characters, dashes, underscores, and periods, and may not exceed 128 characters.)

### Potential Fix

The behaviour looks to be coming from this function https://github.com/databrickslabs/terraform-provider-databricks/blob/master/access/resource_secret_scope.go#L113 - which validates against the regex `^[\w\.@_-]{1,128}$`.

This can be updated to `^[\w\.@_/-]{1,128}$` to allow the `/` character.

**Comment by nfx** [comment]
@tylangesmith just keep in mind we're separating scope and key with `|||` within resource ID, which is highly unlikely to occur in the name of real-world secret scope

**Comment by nfx** [comment]
@tylangesmith where did PR go?
