### ISSUE TITLE
[ISSUE] auto_stop_mins = 0 for endpoint is not respected

### ISSUE THREAD

**Issue by arikitkis** [databrickslabs/terraform-provider-databricks#896]
auto_stop_mins = 0 is not respected. Endpoint is created with 15 auto stop.
updating from 15->30 via terraform works with no issues
updating to 0 also is NOT working

### Configuration
```hcl
resource "databricks_sql_endpoint" "my-endpoint" {
  name = "my_name"
  provider = databricks.nonprod
  instance_profile_arn = databricks_instance_profile.instance_profile-dataeng.instance_profile_arn
  cluster_size = "X-Large"
  auto_stop_mins = 0 #auto stop is disabled
  min_num_clusters = 1
  max_num_clusters = 2
  enable_photon = true
```

### Expected Behavior
endpoint with auto_stop disabled should be created

### Actual Behavior
endpoint with 15 min setting is created

### Steps to Reproduce
`terraform apply`

### Terraform and provider versions
terraform version
Terraform v1.0.10
on darwin_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.3.9
+ provider registry.terraform.io/hashicorp/aws v3.61.0

**Comment by nfx** [comment]
it's related to the way of serialising entities. zero values not supported, unless there's huge demand. for now, terraform plugin won't support it. please set `auto_stop_mins` to big value, like 86400.
