### ISSUE TITLE
[ISSUE] Path (\Repos\Customer) doesn't start with '/'

### ISSUE THREAD

**Issue by troyinsight** [databrickslabs/terraform-provider-databricks#911]
G'day,

I'm having trouble creating a Repo using v0.3.11. This was working perfectly with v0.3.10. As you can see, I'm using a forward slash in my HCL code, but the error message clearly displays a backslash. The Customer folder already exists within the Repos folder.

### Configuration
```hcl
resource "databricks_repo" "customer_repo" {
  git_provider = "gitHub"
  url = data.github_repository.customer_databricks_repository.http_clone_url
  path = "/Repos/Customer/Notebooks"
}
```

### Expected Behavior
Repo called Notebooks is created under Repos/Customer folder

### Actual Behavior
Error: Path (\Repos\Customer) doesn't start with '/'

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions
Terraform v1.0.11
on windows_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.3.11
+ provider registry.terraform.io/hashicorp/azuread v2.9.0
+ provider registry.terraform.io/hashicorp/azurerm v2.85.0
+ provider registry.terraform.io/hashicorp/random v3.1.0
+ provider registry.terraform.io/integrations/github v4.18.0
+ provider registry.terraform.io/microsoft/azuredevops v0.1.7

### Important Factoids
I'm using Windows 11

**Comment by alexott** [comment]
it looks like `filepath` always converts paths into OS-specific variant :-(  It wasn't caught because we're not using windows
it's broken by following piece: https://github.com/databrickslabs/terraform-provider-databricks/blob/master/workspace/resource_repo.go#L63

fix is easy, can you try to build with #912 ?

**Comment by troyinsight** [comment]
Sure, I can give it a test. How do I point my provider at this particular branch? Sorry, I've never done this for a provider

**Comment by alexott** [comment]
You need to build from source code. I'm not sure that we have instructions for that for Windows. You'll need install Go language, etc.

Can you run provider from Linux or Mac?

**Comment by troyinsight** [comment]
Not a problem, I can give it a go over the weekend. Yes, I've got access to both Linux and Mac.

**Comment by alexott** [comment]
it works just fine on Mac. Really, I did miss the fact that `filepath` library converts paths into OS-specific format.

**Comment by nfx** [comment]
Yep, there was a problem related to local paths with dbfs files or notebooks. Should not be the case for remote paths
