### ISSUE TITLE
[DOC] Document `position` on Resource `databricks_global_init_script`

### ISSUE THREAD

**Issue by matan129** [databrickslabs/terraform-provider-databricks#916]
### Affected Resource(s)
`databricks_global_init_script`

### Expected Details
The REST API supports the `position` attribute, and the provider seems to support it as well in-code, but it's undocumented for some reason.

### List of things to potentially add/remove:
- [ ] Document the variable.

### Important Factoids
[Global Init Script Docs](https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/global_init_script)

cc @grozen

**Comment by nfx** [comment]
@matan129 your PR is more than welcome

**Comment by nfx** [comment]
Closed in #924
