### ISSUE TITLE
[ISSUE] Adding Azure Devops repository using databricks_repo

### ISSUE THREAD

**Issue by Freia3** [databrickslabs/terraform-provider-databricks#919]
Hi,

I'm having an issue adding our azure devops repository to databricks using databricks_repo. The error I get is "Encountered an error with your Azure Active Directory credentials. Please try logging out of Azure Active Directory (https://portal.azure.com) and logging back in. Alternatively, you may also visit User Settings > Git Integration to set up an Azure DevOps personal access token."

We're authenticating with Azure Service Principal, so I guess the terraform service principal tries to pull the azure devops repository, which fails. Is it possible to add a property in databricks_repo so we can authenticate using a PAT token?

### Configuration
```hcl
resource "databricks_repo" "dbks_client_repo" {
  url    = "https://dev.azure.com/org/project/_git/clientrepo"
  path   = "/Repos/client-repository/clientrepo"
  branch = "master"
}
```

### Expected Behavior
databricks repo should have been created
terraform plan
```hcl
databricks_repo.dbks_client_repo will be created
  + resource "databricks_repo" "dbks_client_repo" {
      + branch       = "master"
      + commit_hash  = (known after apply)
      + git_provider = (known after apply)
      + id           = (known after apply)
      + path         = "/Repos/client-repository/clientrepo"
      + url          = "https://dev.azure.com/org/project/_git/clientrepo"
    }
```

### Actual Behavior
terraform apply fails with:
│ Error: Encountered an error with your Azure Active Directory credentials. Please try logging out of Azure Active Directory (https://portal.azure.com) and logging back in. Alternatively, you may also visit User Settings > Git Integration to set up an Azure DevOps personal access token.

### Steps to Reproduce
 `terraform apply`

### Terraform and provider versions
    databrickslabs/databricks: 0.3.11

**Comment by alexott** [comment]
It's not possible yet, as DevOps PAT needs to be configured and we don't have REST API for that (work in progress)

**Comment by w0ut0** [comment]
@alexott, is it possible to supply the credentials in the url field? eg. 
```
url          = "https://user:<PAT>@dev.azure.com/org/project/_git/clientrepo"
```

**Comment by alexott** [comment]
I don't know.

**Comment by nfx** [comment]
@Freia3 please talk to your Azure representatives to prioritize AAD SPN OBO flow for Azure Databricks and Azure DevOps integration. This is purely platform feature, not terraform plugin.
