### ISSUE TITLE
Manually deleted workspace with secret scope results in error on plan

### ISSUE THREAD

**Issue by EliiseS** [databrickslabs/terraform-provider-databricks#92]
Creating a workspace with a secret scope, cluster or possibly other references and then manually deleting the workspace after creating, results in an error on terraform plan/apply.

### Terraform Version
0.12.24

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_workspace
- databricks_job

### Terraform Configuration Files
```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Panic Output

```
Error: parse :///api/2.0/secrets/scopes/list?: missing protocol scheme
Error: parse :///api/2.0/clusters/get?cluster_id=0610-100720-loss540: missing protocol scheme
```

### Expected Behavior
Deleting an existing workspace, previously created by terrafrom, waits for a new workspace be created before querying for secret scopes, clusters etc.

### Actual Behavior
Deleting an existing workspace, previously created by terrafrom, results in an error on terraform plan/apply.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Create a workspace with secret scope, cluster, etc in terraform
1. Manually delete the workspace (on Azure in this case)
1. `terraform plan`

### Important Factoids

- Ran on Azure
- SP authentication

### Other panic output

Error output of a workspace with cluster, secrets and ADAL Gen2 mount, that was manually deleted:
![image](https://user-images.githubusercontent.com/12761692/84287612-021a0780-ab38-11ea-8018-2ffe6b38a142.png)

### Configuration

```terraform
variable "user" {
  type        = string
}

variable "password" {
  type        = string
}

variable "client_id" {
  type        = string
}

variable "client_secret" {
  type        = string
}

variable "tenant_id" {
  type        = string
}

variable "subscription_id" {
  type        = string
}

provider "azurerm" {
    version = "~> 2.10"
    client_id         = var.client_id
    client_secret     = var.client_secret
    tenant_id         = var.tenant_id
    subscription_id   = var.subscription_id
    features {}
    skip_provider_registration = true

}

resource "azurerm_resource_group" "db" {
  name     = "db-labs-resources"
  location = "West Europe"
}

resource "azurerm_databricks_workspace" "module" {
  name                        = "db-labs-worspace"
  resource_group_name         = azurerm_resource_group.db.name
  location                    = azurerm_resource_group.db.location
  sku                         = "premium"
}

data "azurerm_client_config" "current" {}

provider "databricks" {
  version = "~> 0.1"

  azure_auth = {
    managed_resource_group = azurerm_databricks_workspace.module.managed_resource_group_name
    azure_region           = azurerm_databricks_workspace.module.location
    workspace_name         = azurerm_databricks_workspace.module.name
    resource_group         = azurerm_databricks_workspace.module.resource_group_name
    client_id               = var.client_id
    client_secret           = var.client_secret
    tenant_id               = var.tenant_id
    subscription_id         = var.subscription_id
}

resource "databricks_secret_scope" "sandbox_storage" {
  name                     = "sandbox-storage"
  initial_manage_principal = "users"
}

resource "databricks_secret" "secret" {
  key          = "secret"
  string_value = "I am a secret"
  scope        = databricks_secret_scope.sandbox_storage.name
}
```

**Comment by EliiseS** [comment]
Hey! Thanks for getting back to me so quickly, sorry for the delay on my part.
I've updated the issue with an example config to reproduce the issue. I've discovered this issue with SP, which I think is the only scenario this would make sense in, since the workspace is being created in the same terraform. Correct me if I'm wrong in that assumption.

_So is the expected behavior that we propagate the knowledge that the workspace is not found to all the resources to identify them to be recreated?_

I'd say so, since you'd want to be able to reprovision a workspace if it's accidentally deleted with everything it originally had.

**Comment by EliiseS** [comment]
I'd like to pick up this and try to work out a solution if you don't mind? I'd love to hear if you have ideas for a solution too!

**Comment by lawrencegripper** [comment]
This may help as the workspace URL would change as the workspace was recreated https://github.com/databrickslabs/terraform-provider-databricks/issues/34

**Comment by stikkireddy** [comment]
@lawrencegripper @EliiseS if my understanding is correct both, urls, the old pattern and new pattern should work but yes i agree with Lawrence that with the new changes to the workspace in azurerm we should probably migrate to the new url scheme.

**Comment by EliiseS** [comment]
The issue persists after testing with the new ´workspace_url´ field from #114

tfplan result:
```terraform
10:22 # tf plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

azurerm_resource_group.db: Refreshing state... [id=/subscriptions/19b90cba-b368-4869-8408-5756739802cd/resourceGroups/db-labs-resources1]
data.azurerm_client_config.current: Refreshing state...
azurerm_databricks_workspace.module: Refreshing state... [id=/subscriptions/19b90cba-b368-4869-8408-5756739802cd/resourceGroups/db-labs-resources1/providers/Microsoft.Databricks/workspaces/db-labs-workspace]
databricks_secret_scope.sandbox_storage: Refreshing state... [id=sandbox-storage]

Error: parse :///api/2.0/secrets/scopes/list?: missing protocol scheme
```

**Comment by stikkireddy** [comment]
Can you please paste your provider hcl code @EliiseS ?

**Comment by EliiseS** [comment]
Waiting on #158 to see if it fixes the issues. Otherwise, the recommended approach  by terraform for initalizating providers with output from resources can be found here: https://github.com/hashicorp/terraform/issues/25314

**Comment by nfx** [comment]
@EliiseS from the looks of it, errors are in older format. now `APIError` returns a nice struct without any HTML. New `make install` should work as well.

**Comment by EliiseS** [comment]
@nfx yeah, I'm waiting for #158 to be ready so I can see if that solves the problem.

**Comment by nfx** [comment]
@EliiseS can you confirm current master branch fixes the issue?
