### ISSUE TITLE
[ISSUE] Provider issue - Databricks not authenticating Service Principal via ARM_* env variables.

### ISSUE THREAD

**Issue by dhuys** [databrickslabs/terraform-provider-databricks#920]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Configuration
```hcl
# Copy-paste your Terraform configuration here

resource "azurerm_databricks_workspace" "databricks_sandbox" {
  name                = "ADB-example"
  resource_group_name = var.resource_group_name
  location            = var.primary_location
  sku                 = "standard"

}

provider "databricks" {
  # token = var.databricks_workspace_token
  host = azurerm_databricks_workspace.databricks_sandbox.workspace_url
}

```

### Expected Behavior
What should have happened?
This should authenticate via azurerm using environment variables `ARM_*` which is set to use a Service Principal

### Actual Behavior
What actually happened?
I am presented with the following error
```
│ Warning: Argument is deprecated
│ 
│   with module.core.provider["registry.terraform.io/databrickslabs/databricks"],
│   on modules/core/main.tf line 48, in provider "databricks":
│   48: provider "databricks" {
│ 
│ `azure_subscription_id` is deprecated and would be removed in v0.4.0. Please rewrite provider configuration with `host = data.azurerm_databricks_workspace.example.workspace_url` to achieve the same effect. ARM_* environment variables would continue to be used as
│ they're used by `azurerm` provider. See https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/databricks_workspace#workspace_url for details
│ 
│ (and one more similar warning elsewhere)
╵
╷
│ Error: User not authorized
│ 
│   with module.core.data.databricks_spark_version.latest_lts,
│   on modules/core/main.tf line 59, in data "databricks_spark_version" "latest_lts":
│   59: data "databricks_spark_version" "latest_lts" {
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. export ` ARM_*` variables to appropriate values
1. `terraform plan`

### Terraform and provider versions

Please paste the output of `terraform version`. If version of `databricks` provider is not the latest (https://github.com/databrickslabs/terraform-provider-databricks/releases), please make sure to use the latest one.
```
Terraform v1.0.10
on linux_amd64
+ provider registry.terraform.io/databrickslabs/databricks v0.3.11
+ provider registry.terraform.io/hashicorp/azurerm v2.85.0
```
### Debug Output
Please add turn on logging, e.g. `TF_LOG=DEBUG terraform apply` and run command again, paste it to gist & provide the link to gist. If you're still willing to paste in log output, make sure you provide only relevant log lines with requests.

It would make it more readable, if you pipe the log through `| grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'`, e.g.:

[Link](https://pastebin.com/B04T3Z6u) to output log
```
TF_LOG=DEBUG terraform plan 2>&1 | grep databricks | sed -E 's/^.* plugin[^:]+: (.*)$/\1/'
```

If Terraform produced a panic, please provide a link to a GitHub Gist containing the output of the `crash.log`.

### Important Factoids
Are there anything atypical about your accounts that we should know? 

It is confirmed the credentials used in `ARM_*` has contributor rights to manipulate databricks.

**Comment by nfx** [comment]
@dhuys there's no `ARM_*` variable, as env variables cannot contain non-alphanumeric characters.

Supported env vars are:

- ARM_USE_MSI
- ARM_CLIENT_SECRET
- ARM_CLIENT_ID
- ARM_TENANT_ID
- ARM_ENVIRONMENT

**Comment by nfx** [comment]
> 2021-11-16T17:12:28.559Z [INFO]  provider.terraform-provider-databricks_v0.3.11: Explicit and implicit attributes: azure_client_id, azure_client_secret, azure_subscription_id, azure_tenant_id, host: timestamp=2021-11-16T17:12:28.558Z
okay, correct env vars were used. 

i'm not sure why you're getting this error - the user creating the workspace must be able to authenticate to it. it's part of our integration testing pipeline.

**Comment by dhuys** [comment]
I would like to reopen this. I must be more explicit in the ticket. 

The following ARM_* variables are set.

Such as 

* ARM_CLIENT_ID
* ARM_TENANT_ID
* ARM_CLIENT_SECRET
* ARM_SUBSCRIPTION_ID

The `ARM_*` was a reference to all the environment variables set.

**Comment by dhuys** [comment]
> i'm not sure why you're getting this error - the user creating the workspace must be able to authenticate to it. it's part of our integration testing pipeline.

@nfx if you are not sure why I am getting this error, then why close the issue? The proper ARM variables are set. These credentials are against a SP that have been validated with the right contributor permissions.

**Comment by nfx** [comment]
@dhuys add `azure_workspace_resource_id` to provider block -  https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs#azure_workspace_resource_id

**Comment by ekhaydarov** [comment]
Just encountered this issue when upgrading azurerm from 2.70.0 to 2.92.0. the this error
```
Error: cannot read global init script: cannot configure azure-client-secret auth: cannot get workspace: somehow resource id is not set. Environment variables used: ARM_CLIENT_SECRET, ARM_CLIENT_ID, ARM_TENANT_ID.
```

However the provider has it set and has been working fine in the previous version. Looking at the release notes theres nothing to suggest about changes to auth. Therefore this has to be an undocumented change or a bug
```
provider "databricks" {
  alias                       = "db"
  azure_workspace_resource_id = module.databricks_workspace.azure_id
  azure_client_id             = "xxx"
  azure_client_secret         = "xxx"
}
```

Any help on this issue would be greatly appreciated

**Comment by FnayouSeif** [comment]
> @dhuys add `azure_workspace_resource_id` to provider block - https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs#azure_workspace_resource_id

Hi, 

I am facing similar issues with the data object defined as below: 

```
data "databricks_spark_version" "latest_lts" {
  long_term_support = true

   depends_on = [
     azurerm_databricks_workspace.core
   ]
}
``` 

Error: 

```
 Error: cannot configure azure-client-secret auth: cannot get workspace: please set `azure_workspace_resource_id` provider argument. Environment variables used: ARM_CLIENT_SECRET, ARM_CLIENT_ID, ARM_TENANT_ID. Please check https://registry.terraform.io/providers/databricks/databricks/latest/docs#authentication for details
 ``` 
 
What is strange is that it's friend data `databricks_node_type` works fine. 

```
data "databricks_node_type" "basic" {
  local_disk  = true
  min_cores   = 4
  gb_per_core = 4

   depends_on = [
     azurerm_databricks_workspace.core
   ]
}
``` 

Where I defined providers as :

```
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=3.13.0"
    }
``` 
```
provider "databricks" {
  azure_workspace_resource_id = azurerm_databricks_workspace.core.id
  host                        = azurerm_databricks_workspace.workspace_url
  alias                       = "azure_account"
  
  # ARM_USE_MSI environment variable is recommended
  azure_use_msi = true
  
}

```

**It feels that this is something related to the data object.

 If I setup `export DATABRICKS_AZURE_RESOURCE_ID=<VALUE_RESOURCE_ID>` in my session before running `terraform`, then the scripts work just fine.

**  


Thanks!
