### ISSUE TITLE
[ISSUE] Provider issue

### ISSUE THREAD

**Issue by anthonybench** [databrickslabs/terraform-provider-databricks#925]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Configuration
```hcl
resource "databricks_job" "this" {

  dynamic "new_cluster" {
    dynamic "library" {
      for_each = var.pypi_libs
      content {
        pypi {
          package = library.value
        }
      }
    }
  }

}
```
*Note: I've elided irrelevant fields.*

### Expected Behavior
Already works in `databricks_cluster` module. Should simply provision the job cluster the same way, with those libraries (according to the documentation).

### Actual Behavior
```
Error: Unsupported block type
│ 
│   on main.tf line 114, in resource "databricks_job" "this":
│  114:       dynamic "library" {
│ 
│ Blocks of type "library" are not expected here.
ERRO[0013] 1 error occurred:
        * exit status 1
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Terraform and provider versions
```
Terraform v1.0.7
on darwin_amd64

Terragrunt version v0.31.0
```

**Comment by nfx** [comment]
Library is a top-level block - https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs/resources/job#library, not within `new_cluster`, rewrite as 

```
resource "databricks_job" "this" {
    // other things

    dynamic "library" {
      for_each = var.pypi_libs
      content {
        pypi {
          package = library.value
        }
      }
  }

}
```

**Comment by anthonybench** [comment]
Thanks!
