### ISSUE TITLE
[DOC] databricks_job resource doc missing *Attribute Reference* section.

### ISSUE THREAD

**Issue by anthonybench** [databrickslabs/terraform-provider-databricks#929]
### Affected Resource(s)
`databricks_job` resource (within the *compute* section).

### Expected Details
A list of attributes. There's an attribute mentioned in the first example `url`, and naturally I could guess what some others might be, but would rather have them enumerated like in other resource docs.

### List of things to potentially add/remove:
*Attribute Reference* section.

**Comment by nfx** [comment]
@anthonybench PR welcome

**Comment by anthonybench** [comment]
@nfx Cool, where could I find them? I peeked in the `/jobs/resource_job.go` file, but it wasn't obvious to me.
