### ISSUE TITLE
[ISSUE] databricks_azure_adls_gen2_mount does not validate directory

### ISSUE THREAD

**Issue by storey247** [databrickslabs/terraform-provider-databricks#94]
### Terraform Version
`Terraform v0.12.26`

### Affected Resource(s)
Please list the resources as a list, for example:
- databricks_azure_adls_gen2_mount

### Terraform Configuration Files
```hcl
resource "databricks_azure_adls_gen2_mount" "mount_wibble" {
  cluster_id             = databricks_cluster.cluster.id
  container_name         = "wibble"
  storage_account_name   = "storeageaccount"
  directory              = "wibble"
  mount_name             = "wibbledir"
  tenant_id              = "<tentant_id>"
  client_secret_scope    = databricks_secret_scope.terraform.name
  client_secret_key      = databricks_secret.client_secret.key
  initialize_file_system = true
}
```

### Debug Output
```
Error: Response from server (403) <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 403 Invalid access token.</title>
</head>
<body><h2>HTTP ERROR 403</h2>
<p>Problem accessing /api/1.2/commands/status. Reason:
<pre>    Invalid access token.</pre></p>
</body>
</html>
```

### Panic Output
N/A

### Expected Behavior
The `tf plan` should throw an error saying that the directory does not match the validation logic of starting with a `/`

### Actual Behavior
No validation error, instead get an error about invalid access token, looks like the `db.fs.mount` being called behind scenes does not have a timeout and because it is looking up an invalid uri everything just times out.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`

**Comment by stikkireddy** [comment]
Hey @storey247 is this sporadic or always like this? when the above scenario is there.

**Comment by stikkireddy** [comment]
and could this be potentially tied to #66?

**Comment by storey247** [comment]
So the issue am fixing here is just the inconsistent validation of the schema in the ADLS gen 2 mount. Looks like the issue on #66 is the same error I was seeing and happens when the execution context times out.

In my situation though the timeout was happening as without the `/` the directory merges with the adfs uri and then ends up with a request that takes forever.

**Comment by nfx** [comment]
@storey247 , does it work as expected in 0.2.4?

**Comment by nfx** [comment]
Closing this issue, as it is without any response. Feel free to reopen it, once it’s again relevant.
