### ISSUE TITLE
[ISSUE] "databricks_repo" with a private GitLab repository

### ISSUE THREAD

**Issue by Pravez** [databrickslabs/terraform-provider-databricks#945]
Hi :)

First of all, thank you for your work.
I am trying to connect with the resource "databricks_repo" a GitLab private repository with my workspace, through Terraform and under Azure.

### Configuration
```hcl
resource "databricks_repo" "repo" {
  git_provider = "gitLab"
  url          = "https://gitlab.com/address.git"
  branch       = "databricks-${terraform.workspace}"
  path         = "/Repos/jobs/databricks-job"
}
```

### Expected Behavior
Terraform should create the repository.

### Actual Behavior

I get the following error : 
**Error: Missing Git provider credentials. Go to User Settings > Git Integration to add your personal access token.**

### Terraform and provider versions
```hcl
    databricks = {
      source = "databrickslabs/databricks"
      version = "0.3.11"
    }
```
As I can guess, I suppose that this feature has not yet been implemented, and that I need to manually go into my workspace to add the credential, and then run my terraform to create the repository. I thought I could create in a one-shot my entire terraform data architecture, with data factory connected to an automatically provisioned databricks.

Thank you for your help !

**Comment by nfx** [comment]
Hi @Pravez this is not the issue of Terraform provider, so closing this one.

Please consult with your Databricks sales team on the current workarounds for private Git repositories.

**Comment by alexott** [comment]
Setting of Git credentials isn't supported right now due the missing API
