### ISSUE TITLE
How to modify "Admin Console/Workspace Settings - Files in Repo"

### ISSUE THREAD

**Issue by Krebsmar** [databrickslabs/terraform-provider-databricks#950]
Hello there,
I've come across an issue by adding a Repo with the "databricks_repo" resource. My Repo is already containing a Notebook, but without setting "Files in Repo" to enabled in Settings/Admin Console/Workspace Settings on UI, Databricks won't display my Notebook.

Do you have a solution for that problem within the Terraform provider?

Greats,
Mario!

**Comment by nfx** [comment]
@Krebsmar You can enable this with setting enableWorkspaceFilesystem flag through databricks_workspace_conf resource. This flag will be removed though when Repo Files will be generally available.
