### ISSUE TITLE
cannot create mws workspaces: cannot create token: cannot configure direct auth: host is empty, but is required by basic_auth. Environment variables used: DATABRICKS_HOST, DATABRICKS_USERNAME, DATABRICKS_PASSWORD

### ISSUE THREAD

**Issue by nfx** [databrickslabs/terraform-provider-databricks#994]
* Using directly configured host+basic_auth authentication
* Configured direct auth: host=https://XXXXX.cloud.databricks.com, token=***REDACTED***, username=user@domain, password=***REDACTED***, azure_use_msi=false
* GET /api/2.0/token/list
* 200 OK {} <- GET /api/2.0/token/list
* Creating client for host  based on host=https://accounts.cloud.databricks.com, token=***REDACTED***, username=user@domain, password=***REDACTED***, azure_use_msi=false
* Using basic auth for user 'user@domain'
* error: cannot create mws workspaces: cannot create token: cannot configure direct auth: host is empty, but is required by basic_auth. Environment variables used: DATABRICKS_HOST, DATABRICKS_USERNAME, DATABRICKS_PASSWORD. Please check https://registry.terraform.io/providers/databrickslabs/databricks/latest/docs#authentication for details

**Comment by AndreasSko** [comment]
We are facing the same issue as described here. It seems to be related to https://github.com/databrickslabs/terraform-provider-databricks/pull/969.
The following workaround works for us: Create the workspace without the `token` block first. After that Terraform run has finished, the `token` block can be added back in and works as expected.

**Comment by nfx** [comment]
@AndreasSko yes, token block was introduced then. You can also create a token in a separately-aliased provider, though it's a bit complex. Do you also see `Creating client for host based on host` in log messages or do you see `Creating client for host https://XXXXX.cloud.databricks.com based on host`?

Probably the fix will be to explicitly do d.

**Comment by AndreasSko** [comment]
> Do you also see `Creating client for host based on host` in log messages or do you see `Creating client for host https://XXXXX.cloud.databricks.com based on host`?

I see the latter:  `Creating client for host https://xxxxxx.cloud.databricks.com based on host=https://accounts.cloud.databricks.com, token=***REDACTED***, username=xxxxxx, password=***REDACTED***, azure_use_msi=false`

**Comment by nfx** [comment]
@AndreasSko but is it on create or other states?
