### ISSUE TITLE
[DOC] Make it clear workspaces can't be created and managed in the same plan

### ISSUE THREAD

**Issue by craigmaclachlan** [databrickslabs/terraform-provider-databricks#995]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Databricks Provider issue tracker reserved for bug reports and feature requests. For general Terraform questions, please see: https://www.terraform.io/community.html.
This template is for both adding enhancement as well as pointing out issues with the provider documentation.

### Affected Resource(s)
https://github.com/databrickslabs/terraform-provider-databricks/blob/71a6984289a42c5ce207f58d67e537d56a63cb51/docs/guides/aws-workspace.md?plain=1#L284-L293

### Expected Details
I have been trying to set up and configure a workspace in the same terraform project. As far as I can tell, the recommendation in the documentation here does not work. [The terraform documentation states](https://www.terraform.io/language/providers/configuration):

> You can use expressions in the values of these configuration arguments, but can only reference values that are known before the configuration is applied. This means you can safely reference input variables, but not attributes exported by resources (with an exception for resource arguments that are specified directly in the configuration). 

So you can't use the hostname and token value created in an `databricks_mws_workspaces` resource because these are only know during the apply stage.

### List of things to potentially add/remove:
This is a list of things to manipulate in the docs:
- [ ] explain more clearly if there is a way to create and manage in a single plan

### Important Factoids
https://www.terraform.io/language/providers/configuration

### References
N/A

**Comment by nfx** [comment]
@craigmaclachlan documentation clearly recommends using multiple modules https://github.com/databrickslabs/terraform-provider-databricks/blob/71a6984289a42c5ce207f58d67e537d56a63cb51/docs/guides/aws-workspace.md?plain=1#L50
